# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3DParameterVisualization_Vst.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OutputWindow(object):
	def setupUi(self, OutputWindow):
		OutputWindow.setObjectName("OutputWindow")
		OutputWindow.resize(1321, 872)
		font = QtGui.QFont()
		font.setPointSize(9)
		OutputWindow.setFont(font)
		self.centralwidget = QtWidgets.QWidget(OutputWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.label = QtWidgets.QLabel(self.centralwidget)
		self.label.setGeometry(QtCore.QRect(10, -3, 381, 31))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label.setFont(font)
		self.label.setObjectName("label")
		self.label_2 = QtWidgets.QLabel(self.centralwidget)
		self.label_2.setGeometry(QtCore.QRect(10, 40, 53, 16))
		self.label_2.setText("")
		self.label_2.setObjectName("label_2")
		self.label_3 = QtWidgets.QLabel(self.centralwidget)
		self.label_3.setGeometry(QtCore.QRect(10, 30, 91, 21))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_3.setFont(font)
		self.label_3.setObjectName("label_3")
		self.ow3DParameterVisualizationParameter_comboBox = QtWidgets.QComboBox(self.centralwidget)
		self.ow3DParameterVisualizationParameter_comboBox.setGeometry(QtCore.QRect(110, 28, 301, 27))
		self.ow3DParameterVisualizationParameter_comboBox.setObjectName("ow3DParameterVisualizationParameter_comboBox")
		self.ow3DParameterVisualization_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
		self.ow3DParameterVisualization_tableWidget.setGeometry(QtCore.QRect(10, 63, 401, 590))
		self.ow3DParameterVisualization_tableWidget.setObjectName("ow3DParameterVisualization_tableWidget")
		self.ow3DParameterVisualization_tableWidget.setColumnCount(0)
		self.ow3DParameterVisualization_tableWidget.setRowCount(0)
		self.label_4 = QtWidgets.QLabel(self.centralwidget)
		self.label_4.setGeometry(QtCore.QRect(10, 666, 211, 20))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_4.setFont(font)
		self.label_4.setObjectName("label_4")
		self.label_5 = QtWidgets.QLabel(self.centralwidget)
		self.label_5.setGeometry(QtCore.QRect(10, 700, 211, 20))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_5.setFont(font)
		self.label_5.setObjectName("label_5")
		self.ow3DParameterVisualizationMinValue_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
		self.ow3DParameterVisualizationMinValue_lineEdit.setGeometry(QtCore.QRect(340, 660, 71, 27))
		self.ow3DParameterVisualizationMinValue_lineEdit.setObjectName("ow3DParameterVisualizationMinValue_lineEdit")
		self.ow3DParameterVisualizationMaxValue_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
		self.ow3DParameterVisualizationMaxValue_lineEdit.setGeometry(QtCore.QRect(340, 694, 71, 27))
		self.ow3DParameterVisualizationMaxValue_lineEdit.setObjectName("ow3DParameterVisualizationMaxValue_lineEdit")
		self.ow3DParameterVisualization3DView_pushButton = QtWidgets.QPushButton(self.centralwidget)
		self.ow3DParameterVisualization3DView_pushButton.setGeometry(QtCore.QRect(290, 730, 121, 30))
		self.ow3DParameterVisualization3DView_pushButton.setObjectName("ow3DParameterVisualization3DView_pushButton")
		self.ow3DParameterVisualizationMaxMin_pushButton = QtWidgets.QPushButton(self.centralwidget)
		self.ow3DParameterVisualizationMaxMin_pushButton.setGeometry(QtCore.QRect(10, 730, 121, 30))
		self.ow3DParameterVisualizationMaxMin_pushButton.setObjectName("ow3DParameterVisualizationMaxMin_pushButton")
		self.ow3DParameterVisualizationUp_pushButton = QtWidgets.QPushButton(self.centralwidget)
		self.ow3DParameterVisualizationUp_pushButton.setGeometry(QtCore.QRect(420, 63, 31, 31))
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("iconos/arrow-up-double.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.ow3DParameterVisualizationUp_pushButton.setIcon(icon)
		self.ow3DParameterVisualizationUp_pushButton.setObjectName("ow3DParameterVisualizationUp_pushButton")
		self.ow3DParameterVisualizationDown_pushButton = QtWidgets.QPushButton(self.centralwidget)
		self.ow3DParameterVisualizationDown_pushButton.setGeometry(QtCore.QRect(420, 100, 31, 31))
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap("iconos/arrow-down-double.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.ow3DParameterVisualizationDown_pushButton.setIcon(icon1)
		self.ow3DParameterVisualizationDown_pushButton.setObjectName("ow3DParameterVisualizationDown_pushButton")
		self.ow3DParameterVisualization_graphicsView = Matplotlib3DWidget(self.centralwidget)
		self.ow3DParameterVisualization_graphicsView.setGeometry(QtCore.QRect(460, 0, 861, 807))
		self.ow3DParameterVisualization_graphicsView.setObjectName("ow3DParameterVisualization_graphicsView")
		OutputWindow.setCentralWidget(self.centralwidget)
		self.iw_toolBar = QtWidgets.QToolBar(OutputWindow)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.iw_toolBar.setFont(font)
		self.iw_toolBar.setIconSize(QtCore.QSize(30, 30))
		self.iw_toolBar.setObjectName("iw_toolBar")
		OutputWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.iw_toolBar)
		self.menubar = QtWidgets.QMenuBar(OutputWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1321, 26))
		self.menubar.setObjectName("menubar")
		self.menuUtilities = QtWidgets.QMenu(self.menubar)
		self.menuUtilities.setObjectName("menuUtilities")
		self.menuClose = QtWidgets.QMenu(self.menubar)
		self.menuClose.setObjectName("menuClose")
		OutputWindow.setMenuBar(self.menubar)
		self.actionNew = QtWidgets.QAction(OutputWindow)
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap("iconos/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionNew.setIcon(icon2)
		self.actionNew.setObjectName("actionNew")
		self.actionOpen = QtWidgets.QAction(OutputWindow)
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap("iconos/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionOpen.setIcon(icon3)
		self.actionOpen.setObjectName("actionOpen")
		self.actionSave = QtWidgets.QAction(OutputWindow)
		icon4 = QtGui.QIcon()
		icon4.addPixmap(QtGui.QPixmap("iconos/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionSave.setIcon(icon4)
		self.actionSave.setObjectName("actionSave")
		self.actionSave_As = QtWidgets.QAction(OutputWindow)
		self.actionSave_As.setObjectName("actionSave_As")
		self.actionPrint = QtWidgets.QAction(OutputWindow)
		self.actionPrint.setObjectName("actionPrint")
		self.actionPrint_2 = QtWidgets.QAction(OutputWindow)
		icon5 = QtGui.QIcon()
		icon5.addPixmap(QtGui.QPixmap("iconos/document-print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionPrint_2.setIcon(icon5)
		self.actionPrint_2.setObjectName("actionPrint_2")
		self.actionExit = QtWidgets.QAction(OutputWindow)
		self.actionExit.setObjectName("actionExit")
		self.actionCopy_Selection = QtWidgets.QAction(OutputWindow)
		self.actionCopy_Selection.setObjectName("actionCopy_Selection")
		self.actionPaste = QtWidgets.QAction(OutputWindow)
		self.actionPaste.setObjectName("actionPaste")
		self.actionOne_Span_Analysis = QtWidgets.QAction(OutputWindow)
		icon6 = QtGui.QIcon()
		icon6.addPixmap(QtGui.QPixmap("iconos/games-solve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionOne_Span_Analysis.setIcon(icon6)
		self.actionOne_Span_Analysis.setObjectName("actionOne_Span_Analysis")
		self.actionUnit_Setting = QtWidgets.QAction(OutputWindow)
		self.actionUnit_Setting.setObjectName("actionUnit_Setting")
		self.actionUnit_Conversion = QtWidgets.QAction(OutputWindow)
		icon7 = QtGui.QIcon()
		icon7.addPixmap(QtGui.QPixmap("iconos/measure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionUnit_Conversion.setIcon(icon7)
		self.actionUnit_Conversion.setObjectName("actionUnit_Conversion")
		self.actionCalculator = QtWidgets.QAction(OutputWindow)
		icon8 = QtGui.QIcon()
		icon8.addPixmap(QtGui.QPixmap("iconos/accessories-calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionCalculator.setIcon(icon8)
		self.actionCalculator.setObjectName("actionCalculator")
		self.actionNotepad = QtWidgets.QAction(OutputWindow)
		icon9 = QtGui.QIcon()
		icon9.addPixmap(QtGui.QPixmap("iconos/story-editor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionNotepad.setIcon(icon9)
		self.actionNotepad.setObjectName("actionNotepad")
		self.actionAbout = QtWidgets.QAction(OutputWindow)
		icon10 = QtGui.QIcon()
		icon10.addPixmap(QtGui.QPixmap("iconos/system-help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionAbout.setIcon(icon10)
		self.actionAbout.setObjectName("actionAbout")
		self.actionAbbreviation = QtWidgets.QAction(OutputWindow)
		self.actionAbbreviation.setObjectName("actionAbbreviation")
		self.actionDisclaimer = QtWidgets.QAction(OutputWindow)
		self.actionDisclaimer.setObjectName("actionDisclaimer")
		self.actionStar_Calculation = QtWidgets.QAction(OutputWindow)
		icon11 = QtGui.QIcon()
		icon11.addPixmap(QtGui.QPixmap("iconos/arrow-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionStar_Calculation.setIcon(icon11)
		self.actionStar_Calculation.setObjectName("actionStar_Calculation")
		self.actionReturn_to_Input_Window = QtWidgets.QAction(OutputWindow)
		self.actionReturn_to_Input_Window.setObjectName("actionReturn_to_Input_Window")
		self.actionPrint_All = QtWidgets.QAction(OutputWindow)
		self.actionPrint_All.setIcon(icon5)
		self.actionPrint_All.setObjectName("actionPrint_All")
		self.actionPrint_Summary_Only = QtWidgets.QAction(OutputWindow)
		self.actionPrint_Summary_Only.setObjectName("actionPrint_Summary_Only")
		self.actionGenerate_Report = QtWidgets.QAction(OutputWindow)
		self.actionGenerate_Report.setObjectName("actionGenerate_Report")
		self.actionStandoff_Profile = QtWidgets.QAction(OutputWindow)
		self.actionStandoff_Profile.setObjectName("actionStandoff_Profile")
		self.action3D_Wellpath = QtWidgets.QAction(OutputWindow)
		self.action3D_Wellpath.setObjectName("action3D_Wellpath")
		self.actionCentralizer = QtWidgets.QAction(OutputWindow)
		self.actionCentralizer.setObjectName("actionCentralizer")
		self.actionGraph_Settings = QtWidgets.QAction(OutputWindow)
		self.actionGraph_Settings.setObjectName("actionGraph_Settings")
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionStar_Calculation)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionUnit_Conversion)
		self.iw_toolBar.addAction(self.actionCalculator)
		self.iw_toolBar.addAction(self.actionNotepad)
		self.iw_toolBar.addSeparator()
		self.menuUtilities.addAction(self.actionUnit_Conversion)
		self.menuUtilities.addAction(self.actionCalculator)
		self.menuUtilities.addAction(self.actionNotepad)
		self.menubar.addAction(self.menuClose.menuAction())
		self.menubar.addAction(self.menuUtilities.menuAction())

		self.retranslateUi(OutputWindow)
		self.actionExit.triggered.connect(OutputWindow.close)
		QtCore.QMetaObject.connectSlotsByName(OutputWindow)

	def retranslateUi(self, OutputWindow):
		_translate = QtCore.QCoreApplication.translate
		OutputWindow.setWindowTitle(_translate("OutputWindow", "Central Software - 3D Parameter Visualization"))
		self.label.setText(_translate("OutputWindow", "3D color visualization for user-defined parameters."))
		self.label_3.setText(_translate("OutputWindow", "Parameter:"))
		self.label_4.setText(_translate("OutputWindow", "Parameter minimum value:"))
		self.label_5.setText(_translate("OutputWindow", "Parameter maximum value:"))
		self.ow3DParameterVisualization3DView_pushButton.setText(_translate("OutputWindow", "3D View..."))
		self.ow3DParameterVisualizationMaxMin_pushButton.setText(_translate("OutputWindow", "Max. and Min."))
		self.iw_toolBar.setWindowTitle(_translate("OutputWindow", "toolBar"))
		self.menuUtilities.setTitle(_translate("OutputWindow", "Utilities"))
		self.menuClose.setTitle(_translate("OutputWindow", "Close"))
		self.actionNew.setText(_translate("OutputWindow", "New"))
		self.actionNew.setShortcut(_translate("OutputWindow", "Ctrl+N"))
		self.actionOpen.setText(_translate("OutputWindow", "Open..."))
		self.actionOpen.setShortcut(_translate("OutputWindow", "Ctrl+O"))
		self.actionSave.setText(_translate("OutputWindow", "Save"))
		self.actionSave.setShortcut(_translate("OutputWindow", "Ctrl+S"))
		self.actionSave_As.setText(_translate("OutputWindow", "Save As..."))
		self.actionPrint.setText(_translate("OutputWindow", "Print Preview..."))
		self.actionPrint_2.setText(_translate("OutputWindow", "Print.."))
		self.actionPrint_2.setShortcut(_translate("OutputWindow", "Ctrl+P"))
		self.actionExit.setText(_translate("OutputWindow", "Exit"))
		self.actionCopy_Selection.setText(_translate("OutputWindow", "Copy Selection"))
		self.actionPaste.setText(_translate("OutputWindow", "Paste"))
		self.actionOne_Span_Analysis.setText(_translate("OutputWindow", "One Span Analysis..."))
		self.actionUnit_Setting.setText(_translate("OutputWindow", "Unit Setting..."))
		self.actionUnit_Conversion.setText(_translate("OutputWindow", "Unit Conversion..."))
		self.actionCalculator.setText(_translate("OutputWindow", "Calculator..."))
		self.actionNotepad.setText(_translate("OutputWindow", "Notepad..."))
		self.actionAbout.setText(_translate("OutputWindow", "About..."))
		self.actionAbbreviation.setText(_translate("OutputWindow", "Abbreviation..."))
		self.actionDisclaimer.setText(_translate("OutputWindow", "Disclaimer..."))
		self.actionStar_Calculation.setText(_translate("OutputWindow", "Star Calculation"))
		self.actionStar_Calculation.setShortcut(_translate("OutputWindow", "F5"))
		self.actionReturn_to_Input_Window.setText(_translate("OutputWindow", "Return to Input Window"))
		self.actionPrint_All.setText(_translate("OutputWindow", "Print Report ..."))
		self.actionPrint_Summary_Only.setText(_translate("OutputWindow", "Print Summary Only ..."))
		self.actionGenerate_Report.setText(_translate("OutputWindow", "Generate Report ..."))
		self.actionStandoff_Profile.setText(_translate("OutputWindow", "Standoff Profile ..."))
		self.action3D_Wellpath.setText(_translate("OutputWindow", "3D Parameter Visualization ..."))
		self.actionCentralizer.setText(_translate("OutputWindow", "Centralizer Spacing Sensitivity Analysis ..."))
		self.actionGraph_Settings.setText(_translate("OutputWindow", "Graph Settings ..."))

from matplotlibwidget import Matplotlib3DWidget
