# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CaliperImport_Vst.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CaliperImport(object):
	def setupUi(self, CaliperImport):
		CaliperImport.setObjectName("CaliperImport")
		CaliperImport.resize(1336, 823)
		self.ciOpenFile_pushButton = QtWidgets.QPushButton(CaliperImport)
		self.ciOpenFile_pushButton.setGeometry(QtCore.QRect(40, 20, 161, 30))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciOpenFile_pushButton.setFont(font)
		self.ciOpenFile_pushButton.setObjectName("ciOpenFile_pushButton")
		self.ciColumnIndexes_groupBox = QtWidgets.QGroupBox(CaliperImport)
		self.ciColumnIndexes_groupBox.setEnabled(False)
		self.ciColumnIndexes_groupBox.setGeometry(QtCore.QRect(598, 430, 301, 181))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciColumnIndexes_groupBox.setFont(font)
		self.ciColumnIndexes_groupBox.setToolTip("")
		self.ciColumnIndexes_groupBox.setObjectName("ciColumnIndexes_groupBox")
		self.label_5 = QtWidgets.QLabel(self.ciColumnIndexes_groupBox)
		self.label_5.setGeometry(QtCore.QRect(30, 35, 31, 21))
		self.label_5.setObjectName("label_5")
		self.label_6 = QtWidgets.QLabel(self.ciColumnIndexes_groupBox)
		self.label_6.setGeometry(QtCore.QRect(180, 35, 71, 21))
		self.label_6.setObjectName("label_6")
		self.ciMDcolumnIndex_spinBox = QtWidgets.QSpinBox(self.ciColumnIndexes_groupBox)
		self.ciMDcolumnIndex_spinBox.setGeometry(QtCore.QRect(30, 70, 70, 27))
		self.ciMDcolumnIndex_spinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.ciMDcolumnIndex_spinBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.ciMDcolumnIndex_spinBox.setMinimum(1)
		self.ciMDcolumnIndex_spinBox.setObjectName("ciMDcolumnIndex_spinBox")
		self.ciH1columnIndex_spinBox = QtWidgets.QSpinBox(self.ciColumnIndexes_groupBox)
		self.ciH1columnIndex_spinBox.setGeometry(QtCore.QRect(180, 70, 70, 27))
		self.ciH1columnIndex_spinBox.setMinimum(1)
		self.ciH1columnIndex_spinBox.setProperty("value", 2)
		self.ciH1columnIndex_spinBox.setObjectName("ciH1columnIndex_spinBox")
		self.ciH2columnIndex_spinBox = QtWidgets.QSpinBox(self.ciColumnIndexes_groupBox)
		self.ciH2columnIndex_spinBox.setGeometry(QtCore.QRect(180, 110, 70, 27))
		self.ciH2columnIndex_spinBox.setMinimum(0)
		self.ciH2columnIndex_spinBox.setProperty("value", 3)
		self.ciH2columnIndex_spinBox.setObjectName("ciH2columnIndex_spinBox")
		self.label = QtWidgets.QLabel(self.ciColumnIndexes_groupBox)
		self.label.setGeometry(QtCore.QRect(130, 70, 51, 20))
		self.label.setObjectName("label")
		self.label_9 = QtWidgets.QLabel(self.ciColumnIndexes_groupBox)
		self.label_9.setGeometry(QtCore.QRect(150, 110, 31, 21))
		self.label_9.setObjectName("label_9")
		self.ciFilter_groupBox = QtWidgets.QGroupBox(CaliperImport)
		self.ciFilter_groupBox.setEnabled(False)
		self.ciFilter_groupBox.setGeometry(QtCore.QRect(598, 620, 301, 131))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciFilter_groupBox.setFont(font)
		self.ciFilter_groupBox.setObjectName("ciFilter_groupBox")
		self.ciMinimumID_entry = QtWidgets.QLineEdit(self.ciFilter_groupBox)
		self.ciMinimumID_entry.setGeometry(QtCore.QRect(20, 80, 80, 27))
		self.ciMinimumID_entry.setAccessibleDescription("")
		self.ciMinimumID_entry.setObjectName("ciMinimumID_entry")
		self.ciMaximumID_entry = QtWidgets.QLineEdit(self.ciFilter_groupBox)
		self.ciMaximumID_entry.setGeometry(QtCore.QRect(180, 80, 80, 27))
		self.ciMaximumID_entry.setObjectName("ciMaximumID_entry")
		self.ciMinimumMD_entry = QtWidgets.QLineEdit(self.ciFilter_groupBox)
		self.ciMinimumMD_entry.setGeometry(QtCore.QRect(20, 40, 80, 27))
		self.ciMinimumMD_entry.setWhatsThis("")
		self.ciMinimumMD_entry.setObjectName("ciMinimumMD_entry")
		self.ciMaximumMD_entry = QtWidgets.QLineEdit(self.ciFilter_groupBox)
		self.ciMaximumMD_entry.setGeometry(QtCore.QRect(180, 40, 80, 27))
		self.ciMaximumMD_entry.setStatusTip("")
		self.ciMaximumMD_entry.setObjectName("ciMaximumMD_entry")
		self.label_3 = QtWidgets.QLabel(self.ciFilter_groupBox)
		self.label_3.setGeometry(QtCore.QRect(110, 40, 60, 27))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(11)
		self.label_3.setFont(font)
		self.label_3.setObjectName("label_3")
		self.label_4 = QtWidgets.QLabel(self.ciFilter_groupBox)
		self.label_4.setGeometry(QtCore.QRect(110, 80, 60, 27))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(11)
		self.label_4.setFont(font)
		self.label_4.setObjectName("label_4")
		self.ciValueFeatures_groupBox = QtWidgets.QGroupBox(CaliperImport)
		self.ciValueFeatures_groupBox.setEnabled(False)
		self.ciValueFeatures_groupBox.setGeometry(QtCore.QRect(598, 50, 301, 261))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciValueFeatures_groupBox.setFont(font)
		self.ciValueFeatures_groupBox.setObjectName("ciValueFeatures_groupBox")
		self.layoutWidget = QtWidgets.QWidget(self.ciValueFeatures_groupBox)
		self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 281, 71))
		self.layoutWidget.setObjectName("layoutWidget")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.ciValueDecimalPoint_radioButton = QtWidgets.QRadioButton(self.layoutWidget)
		self.ciValueDecimalPoint_radioButton.setChecked(True)
		self.ciValueDecimalPoint_radioButton.setObjectName("ciValueDecimalPoint_radioButton")
		self.verticalLayout.addWidget(self.ciValueDecimalPoint_radioButton)
		self.ciValueDecimalComma_radioButton = QtWidgets.QRadioButton(self.layoutWidget)
		self.ciValueDecimalComma_radioButton.setObjectName("ciValueDecimalComma_radioButton")
		self.verticalLayout.addWidget(self.ciValueDecimalComma_radioButton)
		self.formLayoutWidget_2 = QtWidgets.QWidget(self.ciValueFeatures_groupBox)
		self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 110, 281, 151))
		self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
		self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
		self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
		self.formLayout_2.setContentsMargins(0, 0, 0, 0)
		self.formLayout_2.setHorizontalSpacing(15)
		self.formLayout_2.setVerticalSpacing(10)
		self.formLayout_2.setObjectName("formLayout_2")
		self.ciIDvalueUnit_comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciIDvalueUnit_comboBox.setFont(font)
		self.ciIDvalueUnit_comboBox.setObjectName("ciIDvalueUnit_comboBox")
		self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ciIDvalueUnit_comboBox)
		self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_11.setFont(font)
		self.label_11.setObjectName("label_11")
		self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
		self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_12.setFont(font)
		self.label_12.setObjectName("label_12")
		self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
		self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_13.setFont(font)
		self.label_13.setObjectName("label_13")
		self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
		self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_7.setFont(font)
		self.label_7.setObjectName("label_7")
		self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
		self.ciMDvalueUnit_comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciMDvalueUnit_comboBox.setFont(font)
		self.ciMDvalueUnit_comboBox.setObjectName("ciMDvalueUnit_comboBox")
		self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ciMDvalueUnit_comboBox)
		self.ciStartingRow_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_2)
		self.ciStartingRow_spinBox.setMinimum(1)
		self.ciStartingRow_spinBox.setMaximum(50000)
		self.ciStartingRow_spinBox.setSingleStep(1)
		self.ciStartingRow_spinBox.setProperty("value", 1)
		self.ciStartingRow_spinBox.setObjectName("ciStartingRow_spinBox")
		self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ciStartingRow_spinBox)
		self.ciEndingRow_spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_2)
		self.ciEndingRow_spinBox.setMinimum(0)
		self.ciEndingRow_spinBox.setMaximum(50000)
		self.ciEndingRow_spinBox.setSingleStep(1)
		self.ciEndingRow_spinBox.setProperty("value", 0)
		self.ciEndingRow_spinBox.setObjectName("ciEndingRow_spinBox")
		self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ciEndingRow_spinBox)
		self.ciDelimiters_groupBox = QtWidgets.QGroupBox(CaliperImport)
		self.ciDelimiters_groupBox.setEnabled(False)
		self.ciDelimiters_groupBox.setGeometry(QtCore.QRect(598, 320, 301, 101))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciDelimiters_groupBox.setFont(font)
		self.ciDelimiters_groupBox.setObjectName("ciDelimiters_groupBox")
		self.ciSpacesDelimiter_checkBox = QtWidgets.QCheckBox(self.ciDelimiters_groupBox)
		self.ciSpacesDelimiter_checkBox.setGeometry(QtCore.QRect(20, 60, 120, 25))
		self.ciSpacesDelimiter_checkBox.setChecked(False)
		self.ciSpacesDelimiter_checkBox.setObjectName("ciSpacesDelimiter_checkBox")
		self.ciSemicolonDelimiter_checkBox = QtWidgets.QCheckBox(self.ciDelimiters_groupBox)
		self.ciSemicolonDelimiter_checkBox.setGeometry(QtCore.QRect(160, 30, 120, 25))
		self.ciSemicolonDelimiter_checkBox.setObjectName("ciSemicolonDelimiter_checkBox")
		self.ciTabDelimiter_checkBox = QtWidgets.QCheckBox(self.ciDelimiters_groupBox)
		self.ciTabDelimiter_checkBox.setGeometry(QtCore.QRect(20, 30, 120, 25))
		self.ciTabDelimiter_checkBox.setChecked(True)
		self.ciTabDelimiter_checkBox.setObjectName("ciTabDelimiter_checkBox")
		self.ciCommaDelimiter_checkBox = QtWidgets.QCheckBox(self.ciDelimiters_groupBox)
		self.ciCommaDelimiter_checkBox.setGeometry(QtCore.QRect(160, 60, 120, 25))
		self.ciCommaDelimiter_checkBox.setObjectName("ciCommaDelimiter_checkBox")
		self.ciApplyAndDraw_pushButton = QtWidgets.QPushButton(CaliperImport)
		self.ciApplyAndDraw_pushButton.setEnabled(False)
		self.ciApplyAndDraw_pushButton.setGeometry(QtCore.QRect(770, 760, 131, 30))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciApplyAndDraw_pushButton.setFont(font)
		self.ciApplyAndDraw_pushButton.setObjectName("ciApplyAndDraw_pushButton")
		self.groupBox_5 = QtWidgets.QGroupBox(CaliperImport)
		self.groupBox_5.setGeometry(QtCore.QRect(920, 50, 381, 751))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.groupBox_5.setFont(font)
		self.groupBox_5.setObjectName("groupBox_5")
		self.label_2 = QtWidgets.QLabel(self.groupBox_5)
		self.label_2.setGeometry(QtCore.QRect(300, 660, 61, 30))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_2.setFont(font)
		self.label_2.setObjectName("label_2")
		self.ciHoleIDsmoothing_graphicsView = MatplotlibWidget(self.groupBox_5)
		self.ciHoleIDsmoothing_graphicsView.setEnabled(False)
		self.ciHoleIDsmoothing_graphicsView.setGeometry(QtCore.QRect(10, 30, 361, 621))
		self.ciHoleIDsmoothing_graphicsView.setObjectName("ciHoleIDsmoothing_graphicsView")
		self.ciHoleIDsmoothing_slider = QtWidgets.QSlider(self.groupBox_5)
		self.ciHoleIDsmoothing_slider.setEnabled(False)
		self.ciHoleIDsmoothing_slider.setGeometry(QtCore.QRect(20, 660, 221, 30))
		self.ciHoleIDsmoothing_slider.setMaximum(100)
		self.ciHoleIDsmoothing_slider.setSingleStep(0)
		self.ciHoleIDsmoothing_slider.setPageStep(0)
		self.ciHoleIDsmoothing_slider.setProperty("value", 0)
		self.ciHoleIDsmoothing_slider.setSliderPosition(0)
		self.ciHoleIDsmoothing_slider.setOrientation(QtCore.Qt.Horizontal)
		self.ciHoleIDsmoothing_slider.setObjectName("ciHoleIDsmoothing_slider")
		self.ciHoleIDsmoothing_label = QtWidgets.QLabel(self.groupBox_5)
		self.ciHoleIDsmoothing_label.setGeometry(QtCore.QRect(240, 660, 51, 30))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciHoleIDsmoothing_label.setFont(font)
		self.ciHoleIDsmoothing_label.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.ciHoleIDsmoothing_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.ciHoleIDsmoothing_label.setObjectName("ciHoleIDsmoothing_label")
		self.ciAccept_pushButton = QtWidgets.QPushButton(self.groupBox_5)
		self.ciAccept_pushButton.setEnabled(False)
		self.ciAccept_pushButton.setGeometry(QtCore.QRect(240, 710, 131, 30))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciAccept_pushButton.setFont(font)
		self.ciAccept_pushButton.setObjectName("ciAccept_pushButton")
		self.ciLocationsCount_label = QtWidgets.QLabel(self.groupBox_5)
		self.ciLocationsCount_label.setGeometry(QtCore.QRect(20, 715, 191, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		self.ciLocationsCount_label.setFont(font)
		self.ciLocationsCount_label.setText("")
		self.ciLocationsCount_label.setObjectName("ciLocationsCount_label")
		self.ciFilename_label = QtWidgets.QLabel(CaliperImport)
		self.ciFilename_label.setGeometry(QtCore.QRect(230, 20, 671, 30))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setUnderline(False)
		font.setStrikeOut(False)
		self.ciFilename_label.setFont(font)
		self.ciFilename_label.setObjectName("ciFilename_label")
		self.ciFileText_textEdit = QtWidgets.QTextEdit(CaliperImport)
		self.ciFileText_textEdit.setGeometry(QtCore.QRect(40, 60, 541, 691))
		font = QtGui.QFont()
		font.setFamily("Consolas")
		font.setPointSize(9)
		self.ciFileText_textEdit.setFont(font)
		self.ciFileText_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
		self.ciFileText_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
		self.ciFileText_textEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
		self.ciFileText_textEdit.setTabStopWidth(40)
		self.ciFileText_textEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.ciFileText_textEdit.setObjectName("ciFileText_textEdit")
		self.ciStatus_label = QtWidgets.QLabel(CaliperImport)
		self.ciStatus_label.setGeometry(QtCore.QRect(50, 770, 521, 21))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(True)
		font.setWeight(75)
		self.ciStatus_label.setFont(font)
		self.ciStatus_label.setText("")
		self.ciStatus_label.setObjectName("ciStatus_label")

		self.retranslateUi(CaliperImport)
		QtCore.QMetaObject.connectSlotsByName(CaliperImport)

	def retranslateUi(self, CaliperImport):
		_translate = QtCore.QCoreApplication.translate
		CaliperImport.setWindowTitle(_translate("CaliperImport", "Caliper Data Import"))
		self.ciOpenFile_pushButton.setText(_translate("CaliperImport", "Import DR-CAL ..."))
		self.ciColumnIndexes_groupBox.setTitle(_translate("CaliperImport", "Column Indexes"))
		self.label_5.setToolTip(_translate("CaliperImport", "MD index is a mandatory selection."))
		self.label_5.setText(_translate("CaliperImport", "<html><head/><body><p><span style=\" font-weight:600; color:#d62728;\">MD</span></p></body></html>"))
		self.label_6.setToolTip(_translate("CaliperImport", "Hole ID index is a mandatory selection."))
		self.label_6.setText(_translate("CaliperImport", "<html><head/><body><p><span style=\" font-weight:600; color:#1f77b4;\">Hole ID</span></p></body></html>"))
		self.ciMDcolumnIndex_spinBox.setToolTip(_translate("CaliperImport", "MD and Hole ID indexes have to be different."))
		self.ciH1columnIndex_spinBox.setToolTip(_translate("CaliperImport", "MD and Hole ID indexes have to be different."))
		self.ciH2columnIndex_spinBox.setToolTip(_translate("CaliperImport", "0 means that any column is selected."))
		self.label.setText(_translate("CaliperImport", "From:"))
		self.label_9.setText(_translate("CaliperImport", "To:"))
		self.ciFilter_groupBox.setTitle(_translate("CaliperImport", "Filter"))
		self.ciMinimumID_entry.setToolTip(_translate("CaliperImport", "Empty means 0."))
		self.ciMaximumID_entry.setToolTip(_translate("CaliperImport", "Empty means no maximum limit."))
		self.ciMinimumMD_entry.setToolTip(_translate("CaliperImport", "Empty means 0."))
		self.ciMaximumMD_entry.setToolTip(_translate("CaliperImport", "Empty means no maximum limit."))
		self.label_3.setText(_translate("CaliperImport", "< MD <"))
		self.label_4.setText(_translate("CaliperImport", "< ID <"))
		self.ciValueFeatures_groupBox.setTitle(_translate("CaliperImport", "Value features"))
		self.ciValueDecimalPoint_radioButton.setText(_translate("CaliperImport", "Decimal point ( . )"))
		self.ciValueDecimalComma_radioButton.setText(_translate("CaliperImport", "Decimal comma ( , )"))
		self.label_11.setText(_translate("CaliperImport", "Starting row:"))
		self.label_12.setText(_translate("CaliperImport", "End row: (max 50000)"))
		self.label_13.setText(_translate("CaliperImport", "MD unit:"))
		self.label_7.setText(_translate("CaliperImport", "Hole ID unit:"))
		self.ciEndingRow_spinBox.setToolTip(_translate("CaliperImport", "0 means that last row is selected."))
		self.ciDelimiters_groupBox.setToolTip(_translate("CaliperImport", "It is mandatory to select one delimiter at least."))
		self.ciDelimiters_groupBox.setTitle(_translate("CaliperImport", "Delimiters"))
		self.ciSpacesDelimiter_checkBox.setText(_translate("CaliperImport", "Space(s)"))
		self.ciSemicolonDelimiter_checkBox.setText(_translate("CaliperImport", "Semicolon"))
		self.ciTabDelimiter_checkBox.setText(_translate("CaliperImport", "Tab"))
		self.ciCommaDelimiter_checkBox.setText(_translate("CaliperImport", "Comma"))
		self.ciApplyAndDraw_pushButton.setText(_translate("CaliperImport", "Apply and Draw"))
		self.groupBox_5.setTitle(_translate("CaliperImport", "Hole ID Smoothing"))
		self.label_2.setText(_translate("CaliperImport", "smooth"))
		self.ciHoleIDsmoothing_label.setText(_translate("CaliperImport", "0%"))
		self.ciAccept_pushButton.setText(_translate("CaliperImport", "Accept"))
		self.ciFilename_label.setText(_translate("CaliperImport", "<html><head/><body><p><span style=\" color:#646464;\">-- ANY CURRENT FILE --</span></p></body></html>"))

from matplotlibwidget import MatplotlibWidget
