# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CaliperImport_Vst.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
	_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
	def _fromUtf8(s):
		return s

try:
	_encoding = QtGui.QApplication.UnicodeUTF8
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig)

class Ui_CaliperImport(object):
	def setupUi(self, CaliperImport):
		CaliperImport.setObjectName(_fromUtf8("CaliperImport"))
		CaliperImport.resize(1336, 823)
		self.ciOpenFile_pushButton = QtGui.QPushButton(CaliperImport)
		self.ciOpenFile_pushButton.setGeometry(QtCore.QRect(40, 20, 161, 30))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciOpenFile_pushButton.setFont(font)
		self.ciOpenFile_pushButton.setObjectName(_fromUtf8("ciOpenFile_pushButton"))
		self.ciColumnIndexes_groupBox = QtGui.QGroupBox(CaliperImport)
		self.ciColumnIndexes_groupBox.setEnabled(False)
		self.ciColumnIndexes_groupBox.setGeometry(QtCore.QRect(598, 430, 301, 181))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciColumnIndexes_groupBox.setFont(font)
		self.ciColumnIndexes_groupBox.setToolTip(_fromUtf8(""))
		self.ciColumnIndexes_groupBox.setObjectName(_fromUtf8("ciColumnIndexes_groupBox"))
		self.label_5 = QtGui.QLabel(self.ciColumnIndexes_groupBox)
		self.label_5.setGeometry(QtCore.QRect(20, 35, 31, 21))
		self.label_5.setObjectName(_fromUtf8("label_5"))
		self.label_6 = QtGui.QLabel(self.ciColumnIndexes_groupBox)
		self.label_6.setGeometry(QtCore.QRect(130, 35, 71, 21))
		self.label_6.setObjectName(_fromUtf8("label_6"))
		self.ciMDcolumnIndex_spinBox = QtGui.QSpinBox(self.ciColumnIndexes_groupBox)
		self.ciMDcolumnIndex_spinBox.setGeometry(QtCore.QRect(20, 60, 70, 27))
		self.ciMDcolumnIndex_spinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.ciMDcolumnIndex_spinBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.ciMDcolumnIndex_spinBox.setMinimum(1)
		self.ciMDcolumnIndex_spinBox.setObjectName(_fromUtf8("ciMDcolumnIndex_spinBox"))
		self.ciH1columnIndex_spinBox = QtGui.QSpinBox(self.ciColumnIndexes_groupBox)
		self.ciH1columnIndex_spinBox.setGeometry(QtCore.QRect(130, 60, 70, 27))
		self.ciH1columnIndex_spinBox.setMinimum(1)
		self.ciH1columnIndex_spinBox.setProperty("value", 2)
		self.ciH1columnIndex_spinBox.setObjectName(_fromUtf8("ciH1columnIndex_spinBox"))
		self.ciBScolumnIndex_spinBox = QtGui.QSpinBox(self.ciColumnIndexes_groupBox)
		self.ciBScolumnIndex_spinBox.setGeometry(QtCore.QRect(20, 130, 70, 27))
		self.ciBScolumnIndex_spinBox.setMinimum(0)
		self.ciBScolumnIndex_spinBox.setProperty("value", 0)
		self.ciBScolumnIndex_spinBox.setObjectName(_fromUtf8("ciBScolumnIndex_spinBox"))
		self.label_8 = QtGui.QLabel(self.ciColumnIndexes_groupBox)
		self.label_8.setGeometry(QtCore.QRect(20, 105, 71, 21))
		self.label_8.setObjectName(_fromUtf8("label_8"))
		self.ciODcolumnIndex_spinBox = QtGui.QSpinBox(self.ciColumnIndexes_groupBox)
		self.ciODcolumnIndex_spinBox.setGeometry(QtCore.QRect(130, 130, 70, 27))
		self.ciODcolumnIndex_spinBox.setMinimum(0)
		self.ciODcolumnIndex_spinBox.setProperty("value", 0)
		self.ciODcolumnIndex_spinBox.setObjectName(_fromUtf8("ciODcolumnIndex_spinBox"))
		self.label_9 = QtGui.QLabel(self.ciColumnIndexes_groupBox)
		self.label_9.setGeometry(QtCore.QRect(130, 105, 61, 21))
		self.label_9.setObjectName(_fromUtf8("label_9"))
		self.ciH2columnIndex_spinBox = QtGui.QSpinBox(self.ciColumnIndexes_groupBox)
		self.ciH2columnIndex_spinBox.setGeometry(QtCore.QRect(210, 60, 70, 27))
		self.ciH2columnIndex_spinBox.setMinimum(0)
		self.ciH2columnIndex_spinBox.setProperty("value", 0)
		self.ciH2columnIndex_spinBox.setObjectName(_fromUtf8("ciH2columnIndex_spinBox"))
		self.ciFilter_groupBox = QtGui.QGroupBox(CaliperImport)
		self.ciFilter_groupBox.setEnabled(False)
		self.ciFilter_groupBox.setGeometry(QtCore.QRect(598, 620, 301, 131))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciFilter_groupBox.setFont(font)
		self.ciFilter_groupBox.setObjectName(_fromUtf8("ciFilter_groupBox"))
		self.ciMinimumID_entry = QtGui.QLineEdit(self.ciFilter_groupBox)
		self.ciMinimumID_entry.setGeometry(QtCore.QRect(20, 40, 80, 27))
		self.ciMinimumID_entry.setAccessibleDescription(_fromUtf8(""))
		self.ciMinimumID_entry.setObjectName(_fromUtf8("ciMinimumID_entry"))
		self.ciMaximumID_entry = QtGui.QLineEdit(self.ciFilter_groupBox)
		self.ciMaximumID_entry.setGeometry(QtCore.QRect(180, 40, 80, 27))
		self.ciMaximumID_entry.setObjectName(_fromUtf8("ciMaximumID_entry"))
		self.ciMinimumMD_entry = QtGui.QLineEdit(self.ciFilter_groupBox)
		self.ciMinimumMD_entry.setGeometry(QtCore.QRect(20, 80, 80, 27))
		self.ciMinimumMD_entry.setWhatsThis(_fromUtf8(""))
		self.ciMinimumMD_entry.setObjectName(_fromUtf8("ciMinimumMD_entry"))
		self.ciMaximumMD_entry = QtGui.QLineEdit(self.ciFilter_groupBox)
		self.ciMaximumMD_entry.setGeometry(QtCore.QRect(180, 80, 80, 27))
		self.ciMaximumMD_entry.setStatusTip(_fromUtf8(""))
		self.ciMaximumMD_entry.setObjectName(_fromUtf8("ciMaximumMD_entry"))
		self.label_3 = QtGui.QLabel(self.ciFilter_groupBox)
		self.label_3.setGeometry(QtCore.QRect(110, 40, 60, 27))
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Consolas"))
		font.setPointSize(11)
		self.label_3.setFont(font)
		self.label_3.setObjectName(_fromUtf8("label_3"))
		self.label_4 = QtGui.QLabel(self.ciFilter_groupBox)
		self.label_4.setGeometry(QtCore.QRect(110, 80, 60, 27))
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Consolas"))
		font.setPointSize(11)
		self.label_4.setFont(font)
		self.label_4.setObjectName(_fromUtf8("label_4"))
		self.ciValueFeatures_groupBox = QtGui.QGroupBox(CaliperImport)
		self.ciValueFeatures_groupBox.setEnabled(False)
		self.ciValueFeatures_groupBox.setGeometry(QtCore.QRect(598, 50, 301, 261))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciValueFeatures_groupBox.setFont(font)
		self.ciValueFeatures_groupBox.setObjectName(_fromUtf8("ciValueFeatures_groupBox"))
		self.layoutWidget = QtGui.QWidget(self.ciValueFeatures_groupBox)
		self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 281, 71))
		self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
		self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
		self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
		self.ciValueDecimalPoint_radioButton = QtGui.QRadioButton(self.layoutWidget)
		self.ciValueDecimalPoint_radioButton.setChecked(True)
		self.ciValueDecimalPoint_radioButton.setObjectName(_fromUtf8("ciValueDecimalPoint_radioButton"))
		self.verticalLayout.addWidget(self.ciValueDecimalPoint_radioButton)
		self.ciValueDecimalComma_radioButton = QtGui.QRadioButton(self.layoutWidget)
		self.ciValueDecimalComma_radioButton.setObjectName(_fromUtf8("ciValueDecimalComma_radioButton"))
		self.verticalLayout.addWidget(self.ciValueDecimalComma_radioButton)
		self.formLayoutWidget_2 = QtGui.QWidget(self.ciValueFeatures_groupBox)
		self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 110, 281, 151))
		self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
		self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
		self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
		self.formLayout_2.setHorizontalSpacing(15)
		self.formLayout_2.setVerticalSpacing(10)
		self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
		self.ciIDvalueUnit_comboBox = QtGui.QComboBox(self.formLayoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciIDvalueUnit_comboBox.setFont(font)
		self.ciIDvalueUnit_comboBox.setObjectName(_fromUtf8("ciIDvalueUnit_comboBox"))
		self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.ciIDvalueUnit_comboBox)
		self.label_11 = QtGui.QLabel(self.formLayoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_11.setFont(font)
		self.label_11.setObjectName(_fromUtf8("label_11"))
		self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
		self.label_12 = QtGui.QLabel(self.formLayoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_12.setFont(font)
		self.label_12.setObjectName(_fromUtf8("label_12"))
		self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_12)
		self.label_13 = QtGui.QLabel(self.formLayoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_13.setFont(font)
		self.label_13.setObjectName(_fromUtf8("label_13"))
		self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_13)
		self.label_7 = QtGui.QLabel(self.formLayoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_7.setFont(font)
		self.label_7.setObjectName(_fromUtf8("label_7"))
		self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
		self.ciMDvalueUnit_comboBox = QtGui.QComboBox(self.formLayoutWidget_2)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciMDvalueUnit_comboBox.setFont(font)
		self.ciMDvalueUnit_comboBox.setObjectName(_fromUtf8("ciMDvalueUnit_comboBox"))
		self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.ciMDvalueUnit_comboBox)
		self.ciStartingRow_spinBox = QtGui.QSpinBox(self.formLayoutWidget_2)
		self.ciStartingRow_spinBox.setMinimum(1)
		self.ciStartingRow_spinBox.setMaximum(50000)
		self.ciStartingRow_spinBox.setSingleStep(1)
		self.ciStartingRow_spinBox.setProperty("value", 1)
		self.ciStartingRow_spinBox.setObjectName(_fromUtf8("ciStartingRow_spinBox"))
		self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.ciStartingRow_spinBox)
		self.ciEndingRow_spinBox = QtGui.QSpinBox(self.formLayoutWidget_2)
		self.ciEndingRow_spinBox.setMinimum(0)
		self.ciEndingRow_spinBox.setMaximum(50000)
		self.ciEndingRow_spinBox.setSingleStep(1)
		self.ciEndingRow_spinBox.setProperty("value", 0)
		self.ciEndingRow_spinBox.setObjectName(_fromUtf8("ciEndingRow_spinBox"))
		self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.ciEndingRow_spinBox)
		self.ciDelimiters_groupBox = QtGui.QGroupBox(CaliperImport)
		self.ciDelimiters_groupBox.setEnabled(False)
		self.ciDelimiters_groupBox.setGeometry(QtCore.QRect(598, 320, 301, 101))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciDelimiters_groupBox.setFont(font)
		self.ciDelimiters_groupBox.setObjectName(_fromUtf8("ciDelimiters_groupBox"))
		self.ciSpacesDelimiter_checkBox = QtGui.QCheckBox(self.ciDelimiters_groupBox)
		self.ciSpacesDelimiter_checkBox.setGeometry(QtCore.QRect(20, 60, 120, 25))
		self.ciSpacesDelimiter_checkBox.setChecked(True)
		self.ciSpacesDelimiter_checkBox.setObjectName(_fromUtf8("ciSpacesDelimiter_checkBox"))
		self.ciSemicolonDelimiter_checkBox = QtGui.QCheckBox(self.ciDelimiters_groupBox)
		self.ciSemicolonDelimiter_checkBox.setGeometry(QtCore.QRect(160, 30, 120, 25))
		self.ciSemicolonDelimiter_checkBox.setObjectName(_fromUtf8("ciSemicolonDelimiter_checkBox"))
		self.ciTabDelimiter_checkBox = QtGui.QCheckBox(self.ciDelimiters_groupBox)
		self.ciTabDelimiter_checkBox.setGeometry(QtCore.QRect(20, 30, 120, 25))
		self.ciTabDelimiter_checkBox.setObjectName(_fromUtf8("ciTabDelimiter_checkBox"))
		self.ciCommaDelimiter_checkBox = QtGui.QCheckBox(self.ciDelimiters_groupBox)
		self.ciCommaDelimiter_checkBox.setGeometry(QtCore.QRect(160, 60, 120, 25))
		self.ciCommaDelimiter_checkBox.setObjectName(_fromUtf8("ciCommaDelimiter_checkBox"))
		self.ciApplyAndDraw_pushButton = QtGui.QPushButton(CaliperImport)
		self.ciApplyAndDraw_pushButton.setEnabled(False)
		self.ciApplyAndDraw_pushButton.setGeometry(QtCore.QRect(770, 760, 131, 30))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciApplyAndDraw_pushButton.setFont(font)
		self.ciApplyAndDraw_pushButton.setObjectName(_fromUtf8("ciApplyAndDraw_pushButton"))
		self.groupBox_5 = QtGui.QGroupBox(CaliperImport)
		self.groupBox_5.setGeometry(QtCore.QRect(920, 50, 381, 751))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.groupBox_5.setFont(font)
		self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
		self.label_2 = QtGui.QLabel(self.groupBox_5)
		self.label_2.setGeometry(QtCore.QRect(300, 660, 61, 30))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_2.setFont(font)
		self.label_2.setObjectName(_fromUtf8("label_2"))
		self.ciHoleIDsmoothing_graphicsView = MatplotlibWidget(self.groupBox_5)
		self.ciHoleIDsmoothing_graphicsView.setEnabled(False)
		self.ciHoleIDsmoothing_graphicsView.setGeometry(QtCore.QRect(10, 30, 361, 621))
		self.ciHoleIDsmoothing_graphicsView.setObjectName(_fromUtf8("ciHoleIDsmoothing_graphicsView"))
		self.ciHoleIDsmoothing_slider = QtGui.QSlider(self.groupBox_5)
		self.ciHoleIDsmoothing_slider.setEnabled(False)
		self.ciHoleIDsmoothing_slider.setGeometry(QtCore.QRect(20, 660, 221, 30))
		self.ciHoleIDsmoothing_slider.setMaximum(100)
		self.ciHoleIDsmoothing_slider.setProperty("value", 0)
		self.ciHoleIDsmoothing_slider.setSliderPosition(0)
		self.ciHoleIDsmoothing_slider.setOrientation(QtCore.Qt.Horizontal)
		self.ciHoleIDsmoothing_slider.setObjectName(_fromUtf8("ciHoleIDsmoothing_slider"))
		self.ciHoleIDsmoothing_label = QtGui.QLabel(self.groupBox_5)
		self.ciHoleIDsmoothing_label.setGeometry(QtCore.QRect(240, 660, 51, 30))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciHoleIDsmoothing_label.setFont(font)
		self.ciHoleIDsmoothing_label.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.ciHoleIDsmoothing_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.ciHoleIDsmoothing_label.setObjectName(_fromUtf8("ciHoleIDsmoothing_label"))
		self.ciAccept_pushButton = QtGui.QPushButton(self.groupBox_5)
		self.ciAccept_pushButton.setEnabled(False)
		self.ciAccept_pushButton.setGeometry(QtCore.QRect(240, 710, 131, 30))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.ciAccept_pushButton.setFont(font)
		self.ciAccept_pushButton.setObjectName(_fromUtf8("ciAccept_pushButton"))
		self.ciLocationsCount_label = QtGui.QLabel(self.groupBox_5)
		self.ciLocationsCount_label.setGeometry(QtCore.QRect(20, 715, 191, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		self.ciLocationsCount_label.setFont(font)
		self.ciLocationsCount_label.setText(_fromUtf8(""))
		self.ciLocationsCount_label.setObjectName(_fromUtf8("ciLocationsCount_label"))
		self.ciFilename_label = QtGui.QLabel(CaliperImport)
		self.ciFilename_label.setGeometry(QtCore.QRect(230, 20, 671, 30))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setUnderline(False)
		font.setStrikeOut(False)
		self.ciFilename_label.setFont(font)
		self.ciFilename_label.setObjectName(_fromUtf8("ciFilename_label"))
		self.ciFileText_textEdit = QtGui.QTextEdit(CaliperImport)
		self.ciFileText_textEdit.setGeometry(QtCore.QRect(40, 60, 541, 691))
		font = QtGui.QFont()
		font.setFamily(_fromUtf8("Consolas"))
		font.setPointSize(9)
		self.ciFileText_textEdit.setFont(font)
		self.ciFileText_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
		self.ciFileText_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
		self.ciFileText_textEdit.setLineWrapMode(QtGui.QTextEdit.NoWrap)
		self.ciFileText_textEdit.setTabStopWidth(40)
		self.ciFileText_textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
		self.ciFileText_textEdit.setObjectName(_fromUtf8("ciFileText_textEdit"))

		self.retranslateUi(CaliperImport)
		QtCore.QMetaObject.connectSlotsByName(CaliperImport)

	def retranslateUi(self, CaliperImport):
		CaliperImport.setWindowTitle(_translate("CaliperImport", "Caliper Data Import", None))
		self.ciOpenFile_pushButton.setText(_translate("CaliperImport", "Import DR-CAL ...", None))
		self.ciColumnIndexes_groupBox.setTitle(_translate("CaliperImport", "Column Indexes", None))
		self.label_5.setToolTip(_translate("CaliperImport", "MD index is a mandatory selection.", None))
		self.label_5.setText(_translate("CaliperImport", "<html><head/><body><p><span style=\" font-weight:600; color:#d62728;\">MD</span></p></body></html>", None))
		self.label_6.setToolTip(_translate("CaliperImport", "Hole ID index is a mandatory selection.", None))
		self.label_6.setText(_translate("CaliperImport", "<html><head/><body><p><span style=\" font-weight:600; color:#1f77b4;\">Hole ID</span></p></body></html>", None))
		self.ciMDcolumnIndex_spinBox.setToolTip(_translate("CaliperImport", "MD and Hole ID indexes have to be different.", None))
		self.ciH1columnIndex_spinBox.setToolTip(_translate("CaliperImport", "MD and Hole ID indexes have to be different.", None))
		self.ciBScolumnIndex_spinBox.setToolTip(_translate("CaliperImport", "0 means that any column is selected.", None))
		self.label_8.setToolTip(_translate("CaliperImport", "BS unit must be the same as Hole ID unit,\n"
"in order to show a congruet graph.", None))
		self.label_8.setText(_translate("CaliperImport", "<html><head/><body><p><span style=\" font-weight:600; color:#00aa00;\">BS</span></p></body></html>", None))
		self.ciODcolumnIndex_spinBox.setToolTip(_translate("CaliperImport", "0 means that any column is selected.", None))
		self.label_9.setToolTip(_translate("CaliperImport", "OD unit must be the same as Hole ID unit,\n"
"in order to show a congruet graph. (optional)", None))
		self.label_9.setText(_translate("CaliperImport", "<html><head/><body><p><span style=\" font-weight:600; color:#9467bd;\">IP OD</span></p></body></html>", None))
		self.ciH2columnIndex_spinBox.setToolTip(_translate("CaliperImport", "0 means that any column is selected.", None))
		self.ciFilter_groupBox.setTitle(_translate("CaliperImport", "Filter", None))
		self.ciMinimumID_entry.setToolTip(_translate("CaliperImport", "Empty means 0.", None))
		self.ciMaximumID_entry.setToolTip(_translate("CaliperImport", "Empty means no maximum limit.", None))
		self.ciMinimumMD_entry.setToolTip(_translate("CaliperImport", "Empty means 0.", None))
		self.ciMaximumMD_entry.setToolTip(_translate("CaliperImport", "Empty means no maximum limit.", None))
		self.label_3.setText(_translate("CaliperImport", "< ID <", None))
		self.label_4.setText(_translate("CaliperImport", "< MD <", None))
		self.ciValueFeatures_groupBox.setTitle(_translate("CaliperImport", "Value features", None))
		self.ciValueDecimalPoint_radioButton.setText(_translate("CaliperImport", "Decimal point ( . )", None))
		self.ciValueDecimalComma_radioButton.setText(_translate("CaliperImport", "Decimal comma ( , )", None))
		self.label_11.setText(_translate("CaliperImport", "Starting row:", None))
		self.label_12.setText(_translate("CaliperImport", "End row: (max 50000)", None))
		self.label_13.setText(_translate("CaliperImport", "MD unit:", None))
		self.label_7.setText(_translate("CaliperImport", "Hole ID unit:", None))
		self.ciEndingRow_spinBox.setToolTip(_translate("CaliperImport", "0 means that last row is selected.", None))
		self.ciDelimiters_groupBox.setToolTip(_translate("CaliperImport", "It is mandatory to select one delimiter at least.", None))
		self.ciDelimiters_groupBox.setTitle(_translate("CaliperImport", "Delimiters", None))
		self.ciSpacesDelimiter_checkBox.setText(_translate("CaliperImport", "Space(s)", None))
		self.ciSemicolonDelimiter_checkBox.setText(_translate("CaliperImport", "Semicolon", None))
		self.ciTabDelimiter_checkBox.setText(_translate("CaliperImport", "Tab", None))
		self.ciCommaDelimiter_checkBox.setText(_translate("CaliperImport", "Comma", None))
		self.ciApplyAndDraw_pushButton.setText(_translate("CaliperImport", "Apply and Draw", None))
		self.groupBox_5.setTitle(_translate("CaliperImport", "Hole ID Smoothing", None))
		self.label_2.setText(_translate("CaliperImport", "smooth", None))
		self.ciHoleIDsmoothing_label.setText(_translate("CaliperImport", "0%", None))
		self.ciAccept_pushButton.setText(_translate("CaliperImport", "Accept", None))
		self.ciFilename_label.setText(_translate("CaliperImport", "<html><head/><body><p><span style=\" color:#646464;\">-- ANY CURRENT FILE --</span></p></body></html>", None))

from matplotlibwidget import MatplotlibWidget
