# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CentralizerSpacingSensitivityAnalysis_Vst.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
	_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
	def _fromUtf8(s):
		return s

try:
	_encoding = QtGui.QApplication.UnicodeUTF8
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig)

class Ui_OutputWindow(object):
	def setupUi(self, OutputWindow):
		OutputWindow.setObjectName(_fromUtf8("OutputWindow"))
		OutputWindow.resize(1321, 872)
		font = QtGui.QFont()
		font.setPointSize(9)
		OutputWindow.setFont(font)
		self.centralwidget = QtGui.QWidget(OutputWindow)
		self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
		self.label = QtGui.QLabel(self.centralwidget)
		self.label.setGeometry(QtCore.QRect(10, 10, 421, 31))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label.setFont(font)
		self.label.setObjectName(_fromUtf8("label"))
		self.label_2 = QtGui.QLabel(self.centralwidget)
		self.label_2.setGeometry(QtCore.QRect(10, 40, 53, 16))
		self.label_2.setText(_fromUtf8(""))
		self.label_2.setObjectName(_fromUtf8("label_2"))
		self.label_3 = QtGui.QLabel(self.centralwidget)
		self.label_3.setGeometry(QtCore.QRect(10, 60, 91, 21))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_3.setFont(font)
		self.label_3.setObjectName(_fromUtf8("label_3"))
		self.owSpacingSensitivityPipes_tableWidget = QtGui.QTableWidget(self.centralwidget)
		self.owSpacingSensitivityPipes_tableWidget.setGeometry(QtCore.QRect(10, 100, 401, 411))
		self.owSpacingSensitivityPipes_tableWidget.setObjectName(_fromUtf8("owSpacingSensitivityPipes_tableWidget"))
		self.owSpacingSensitivityPipes_tableWidget.setColumnCount(0)
		self.owSpacingSensitivityPipes_tableWidget.setRowCount(0)
		self.label_4 = QtGui.QLabel(self.centralwidget)
		self.label_4.setGeometry(QtCore.QRect(10, 540, 111, 20))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_4.setFont(font)
		self.label_4.setObjectName(_fromUtf8("label_4"))
		self.owSpacingSensitivityCalculate_pushButton = QtGui.QPushButton(self.centralwidget)
		self.owSpacingSensitivityCalculate_pushButton.setGeometry(QtCore.QRect(220, 660, 191, 30))
		self.owSpacingSensitivityCalculate_pushButton.setObjectName(_fromUtf8("owSpacingSensitivityCalculate_pushButton"))
		self.owSpacingSensitivityMinMaxSpacing_tableWidget = QtGui.QTableWidget(self.centralwidget)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setGeometry(QtCore.QRect(10, 570, 401, 62))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setFont(font)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setAutoFillBackground(False)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setFrameShadow(QtGui.QFrame.Sunken)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setColumnCount(1)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setObjectName(_fromUtf8("owSpacingSensitivityMinMaxSpacing_tableWidget"))
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setRowCount(2)
		item = QtGui.QTableWidgetItem()
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setVerticalHeaderItem(0, item)
		item = QtGui.QTableWidgetItem()
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setVerticalHeaderItem(1, item)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.horizontalHeader().setVisible(False)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.horizontalHeader().setCascadingSectionResizes(False)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.horizontalHeader().setDefaultSectionSize(130)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.horizontalHeader().setHighlightSections(True)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.horizontalHeader().setMinimumSectionSize(55)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.horizontalHeader().setSortIndicatorShown(False)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.horizontalHeader().setStretchLastSection(False)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.verticalHeader().setDefaultSectionSize(30)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.verticalHeader().setMinimumSectionSize(28)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.verticalHeader().setSortIndicatorShown(False)
		self.tabWidget = QtGui.QTabWidget(self.centralwidget)
		self.tabWidget.setGeometry(QtCore.QRect(440, 0, 881, 806))
		self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
		self.tab = QtGui.QWidget()
		self.tab.setObjectName(_fromUtf8("tab"))
		self.owSpacingSensitivityStandoffMidSpan_graphicsView = MatplotlibWidget(self.tab)
		self.owSpacingSensitivityStandoffMidSpan_graphicsView.setGeometry(QtCore.QRect(0, 0, 891, 781))
		self.owSpacingSensitivityStandoffMidSpan_graphicsView.setObjectName(_fromUtf8("owSpacingSensitivityStandoffMidSpan_graphicsView"))
		self.tabWidget.addTab(self.tab, _fromUtf8(""))
		self.tab_2 = QtGui.QWidget()
		self.tab_2.setObjectName(_fromUtf8("tab_2"))
		self.owSpacingSensitivityStandoffCentr_graphicsView = MatplotlibWidget(self.tab_2)
		self.owSpacingSensitivityStandoffCentr_graphicsView.setGeometry(QtCore.QRect(0, 0, 891, 779))
		self.owSpacingSensitivityStandoffCentr_graphicsView.setObjectName(_fromUtf8("owSpacingSensitivityStandoffCentr_graphicsView"))
		self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
		self.tab_3 = QtGui.QWidget()
		self.tab_3.setObjectName(_fromUtf8("tab_3"))
		self.owSpacingSensitivityStandoff_tableWidget = QtGui.QTableWidget(self.tab_3)
		self.owSpacingSensitivityStandoff_tableWidget.setGeometry(QtCore.QRect(0, 40, 881, 735))
		self.owSpacingSensitivityStandoff_tableWidget.setObjectName(_fromUtf8("owSpacingSensitivityStandoff_tableWidget"))
		self.owSpacingSensitivityStandoff_tableWidget.setColumnCount(0)
		self.owSpacingSensitivityStandoff_tableWidget.setRowCount(0)
		self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
		OutputWindow.setCentralWidget(self.centralwidget)
		self.iw_toolBar = QtGui.QToolBar(OutputWindow)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.iw_toolBar.setFont(font)
		self.iw_toolBar.setIconSize(QtCore.QSize(30, 30))
		self.iw_toolBar.setObjectName(_fromUtf8("iw_toolBar"))
		OutputWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.iw_toolBar)
		self.menubar = QtGui.QMenuBar(OutputWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1321, 26))
		self.menubar.setObjectName(_fromUtf8("menubar"))
		self.menuClose = QtGui.QMenu(self.menubar)
		self.menuClose.setObjectName(_fromUtf8("menuClose"))
		OutputWindow.setMenuBar(self.menubar)
		self.actionNew = QtGui.QAction(OutputWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/document-new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionNew.setIcon(icon)
		self.actionNew.setObjectName(_fromUtf8("actionNew"))
		self.actionOpen = QtGui.QAction(OutputWindow)
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/document-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionOpen.setIcon(icon1)
		self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
		self.actionSave = QtGui.QAction(OutputWindow)
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/document-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionSave.setIcon(icon2)
		self.actionSave.setObjectName(_fromUtf8("actionSave"))
		self.actionSave_As = QtGui.QAction(OutputWindow)
		self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
		self.actionPrint = QtGui.QAction(OutputWindow)
		self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
		self.actionPrint_2 = QtGui.QAction(OutputWindow)
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/document-print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionPrint_2.setIcon(icon3)
		self.actionPrint_2.setObjectName(_fromUtf8("actionPrint_2"))
		self.actionExit = QtGui.QAction(OutputWindow)
		self.actionExit.setObjectName(_fromUtf8("actionExit"))
		self.actionCopy_Selection = QtGui.QAction(OutputWindow)
		self.actionCopy_Selection.setObjectName(_fromUtf8("actionCopy_Selection"))
		self.actionPaste = QtGui.QAction(OutputWindow)
		self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
		self.actionOne_Span_Analysis = QtGui.QAction(OutputWindow)
		icon4 = QtGui.QIcon()
		icon4.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/games-solve.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionOne_Span_Analysis.setIcon(icon4)
		self.actionOne_Span_Analysis.setObjectName(_fromUtf8("actionOne_Span_Analysis"))
		self.actionUnit_Setting = QtGui.QAction(OutputWindow)
		self.actionUnit_Setting.setObjectName(_fromUtf8("actionUnit_Setting"))
		self.actionUnit_Conversion = QtGui.QAction(OutputWindow)
		icon5 = QtGui.QIcon()
		icon5.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/measure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionUnit_Conversion.setIcon(icon5)
		self.actionUnit_Conversion.setObjectName(_fromUtf8("actionUnit_Conversion"))
		self.actionCalculator = QtGui.QAction(OutputWindow)
		icon6 = QtGui.QIcon()
		icon6.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/accessories-calculator.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionCalculator.setIcon(icon6)
		self.actionCalculator.setObjectName(_fromUtf8("actionCalculator"))
		self.actionNotepad = QtGui.QAction(OutputWindow)
		icon7 = QtGui.QIcon()
		icon7.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/story-editor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionNotepad.setIcon(icon7)
		self.actionNotepad.setObjectName(_fromUtf8("actionNotepad"))
		self.actionAbout = QtGui.QAction(OutputWindow)
		icon8 = QtGui.QIcon()
		icon8.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/system-help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionAbout.setIcon(icon8)
		self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
		self.actionAbbreviation = QtGui.QAction(OutputWindow)
		self.actionAbbreviation.setObjectName(_fromUtf8("actionAbbreviation"))
		self.actionDisclaimer = QtGui.QAction(OutputWindow)
		self.actionDisclaimer.setObjectName(_fromUtf8("actionDisclaimer"))
		self.actionStar_Calculation = QtGui.QAction(OutputWindow)
		icon9 = QtGui.QIcon()
		icon9.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/arrow-left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionStar_Calculation.setIcon(icon9)
		self.actionStar_Calculation.setObjectName(_fromUtf8("actionStar_Calculation"))
		self.actionReturn_to_Input_Window = QtGui.QAction(OutputWindow)
		self.actionReturn_to_Input_Window.setObjectName(_fromUtf8("actionReturn_to_Input_Window"))
		self.actionPrint_All = QtGui.QAction(OutputWindow)
		self.actionPrint_All.setIcon(icon3)
		self.actionPrint_All.setObjectName(_fromUtf8("actionPrint_All"))
		self.actionPrint_Summary_Only = QtGui.QAction(OutputWindow)
		self.actionPrint_Summary_Only.setObjectName(_fromUtf8("actionPrint_Summary_Only"))
		self.actionGenerate_Report = QtGui.QAction(OutputWindow)
		self.actionGenerate_Report.setObjectName(_fromUtf8("actionGenerate_Report"))
		self.actionStandoff_Profile = QtGui.QAction(OutputWindow)
		self.actionStandoff_Profile.setObjectName(_fromUtf8("actionStandoff_Profile"))
		self.action3D_Wellpath = QtGui.QAction(OutputWindow)
		self.action3D_Wellpath.setObjectName(_fromUtf8("action3D_Wellpath"))
		self.actionCentralizer = QtGui.QAction(OutputWindow)
		self.actionCentralizer.setObjectName(_fromUtf8("actionCentralizer"))
		self.actionGraph_Settings = QtGui.QAction(OutputWindow)
		self.actionGraph_Settings.setObjectName(_fromUtf8("actionGraph_Settings"))
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionStar_Calculation)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionUnit_Conversion)
		self.iw_toolBar.addAction(self.actionCalculator)
		self.iw_toolBar.addAction(self.actionNotepad)
		self.iw_toolBar.addSeparator()
		self.menubar.addAction(self.menuClose.menuAction())

		self.retranslateUi(OutputWindow)
		self.tabWidget.setCurrentIndex(0)
		QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), OutputWindow.close)
		QtCore.QMetaObject.connectSlotsByName(OutputWindow)

	def retranslateUi(self, OutputWindow):
		OutputWindow.setWindowTitle(_translate("OutputWindow", "Central Software - Centralizer Spacing Sensitivity Analysis", None))
		self.label.setText(_translate("OutputWindow", "Sensitivity study is only for the <Specify spacing> mode.", None))
		self.label_3.setText(_translate("OutputWindow", "Pipes:", None))
		self.label_4.setText(_translate("OutputWindow", "Spacing range:", None))
		self.owSpacingSensitivityCalculate_pushButton.setText(_translate("OutputWindow", "Calculate", None))
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setSortingEnabled(False)
		item = self.owSpacingSensitivityMinMaxSpacing_tableWidget.verticalHeaderItem(0)
		item.setText(_translate("OutputWindow", "Min. spacing                                ", None))
		item = self.owSpacingSensitivityMinMaxSpacing_tableWidget.verticalHeaderItem(1)
		item.setText(_translate("OutputWindow", "Max. spacing                               ", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("OutputWindow", "Standoff @ Mid Span", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("OutputWindow", "Standoff @ cent.", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("OutputWindow", "Table", None))
		self.iw_toolBar.setWindowTitle(_translate("OutputWindow", "toolBar", None))
		self.menuClose.setTitle(_translate("OutputWindow", "Close", None))
		self.actionNew.setText(_translate("OutputWindow", "New", None))
		self.actionNew.setShortcut(_translate("OutputWindow", "Ctrl+N", None))
		self.actionOpen.setText(_translate("OutputWindow", "Open...", None))
		self.actionOpen.setShortcut(_translate("OutputWindow", "Ctrl+O", None))
		self.actionSave.setText(_translate("OutputWindow", "Save", None))
		self.actionSave.setShortcut(_translate("OutputWindow", "Ctrl+S", None))
		self.actionSave_As.setText(_translate("OutputWindow", "Save As...", None))
		self.actionPrint.setText(_translate("OutputWindow", "Print Preview...", None))
		self.actionPrint_2.setText(_translate("OutputWindow", "Print..", None))
		self.actionPrint_2.setShortcut(_translate("OutputWindow", "Ctrl+P", None))
		self.actionExit.setText(_translate("OutputWindow", "Exit", None))
		self.actionCopy_Selection.setText(_translate("OutputWindow", "Copy Selection", None))
		self.actionPaste.setText(_translate("OutputWindow", "Paste", None))
		self.actionOne_Span_Analysis.setText(_translate("OutputWindow", "One Span Analysis...", None))
		self.actionUnit_Setting.setText(_translate("OutputWindow", "Unit Setting...", None))
		self.actionUnit_Conversion.setText(_translate("OutputWindow", "Unit Conversion...", None))
		self.actionCalculator.setText(_translate("OutputWindow", "Calculator...", None))
		self.actionNotepad.setText(_translate("OutputWindow", "Notepad...", None))
		self.actionAbout.setText(_translate("OutputWindow", "About...", None))
		self.actionAbbreviation.setText(_translate("OutputWindow", "Abbreviation...", None))
		self.actionDisclaimer.setText(_translate("OutputWindow", "Disclaimer...", None))
		self.actionStar_Calculation.setText(_translate("OutputWindow", "Star Calculation", None))
		self.actionStar_Calculation.setShortcut(_translate("OutputWindow", "F5", None))
		self.actionReturn_to_Input_Window.setText(_translate("OutputWindow", "Return to Input Window", None))
		self.actionPrint_All.setText(_translate("OutputWindow", "Print Report ...", None))
		self.actionPrint_Summary_Only.setText(_translate("OutputWindow", "Print Summary Only ...", None))
		self.actionGenerate_Report.setText(_translate("OutputWindow", "Generate Report ...", None))
		self.actionStandoff_Profile.setText(_translate("OutputWindow", "Standoff Profile ...", None))
		self.action3D_Wellpath.setText(_translate("OutputWindow", "3D Parameter Visualization ...", None))
		self.actionCentralizer.setText(_translate("OutputWindow", "Centralizer Spacing Sensitivity Analysis ...", None))
		self.actionGraph_Settings.setText(_translate("OutputWindow", "Graph Settings ...", None))

from matplotlibwidget import MatplotlibWidget
