# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CentralizerSpacingSensitivityAnalysis_Vst.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OutputWindow(object):
	def setupUi(self, OutputWindow):
		OutputWindow.setObjectName("OutputWindow")
		OutputWindow.resize(1321, 872)
		font = QtGui.QFont()
		font.setPointSize(9)
		OutputWindow.setFont(font)
		self.centralwidget = QtWidgets.QWidget(OutputWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.label = QtWidgets.QLabel(self.centralwidget)
		self.label.setGeometry(QtCore.QRect(10, 10, 421, 31))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label.setFont(font)
		self.label.setObjectName("label")
		self.label_2 = QtWidgets.QLabel(self.centralwidget)
		self.label_2.setGeometry(QtCore.QRect(10, 40, 53, 16))
		self.label_2.setText("")
		self.label_2.setObjectName("label_2")
		self.label_3 = QtWidgets.QLabel(self.centralwidget)
		self.label_3.setGeometry(QtCore.QRect(10, 60, 91, 21))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_3.setFont(font)
		self.label_3.setObjectName("label_3")
		self.owSpacingSensitivityPipes_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
		self.owSpacingSensitivityPipes_tableWidget.setGeometry(QtCore.QRect(10, 100, 401, 411))
		self.owSpacingSensitivityPipes_tableWidget.setObjectName("owSpacingSensitivityPipes_tableWidget")
		self.owSpacingSensitivityPipes_tableWidget.setColumnCount(0)
		self.owSpacingSensitivityPipes_tableWidget.setRowCount(0)
		self.label_4 = QtWidgets.QLabel(self.centralwidget)
		self.label_4.setGeometry(QtCore.QRect(10, 540, 111, 20))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label_4.setFont(font)
		self.label_4.setObjectName("label_4")
		self.owSpacingSensitivityCalculate_pushButton = QtWidgets.QPushButton(self.centralwidget)
		self.owSpacingSensitivityCalculate_pushButton.setGeometry(QtCore.QRect(220, 660, 191, 30))
		self.owSpacingSensitivityCalculate_pushButton.setObjectName("owSpacingSensitivityCalculate_pushButton")
		self.owSpacingSensitivityMinMaxSpacing_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setGeometry(QtCore.QRect(10, 570, 401, 62))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setFont(font)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setAutoFillBackground(False)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setColumnCount(1)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setObjectName("owSpacingSensitivityMinMaxSpacing_tableWidget")
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setRowCount(2)
		item = QtWidgets.QTableWidgetItem()
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setVerticalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setVerticalHeaderItem(1, item)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.horizontalHeader().setVisible(False)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.horizontalHeader().setCascadingSectionResizes(False)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.horizontalHeader().setDefaultSectionSize(130)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.horizontalHeader().setHighlightSections(True)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.horizontalHeader().setMinimumSectionSize(55)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.horizontalHeader().setSortIndicatorShown(False)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.horizontalHeader().setStretchLastSection(False)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.verticalHeader().setDefaultSectionSize(30)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.verticalHeader().setMinimumSectionSize(28)
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.verticalHeader().setSortIndicatorShown(False)
		self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
		self.tabWidget.setGeometry(QtCore.QRect(440, 0, 881, 806))
		self.tabWidget.setObjectName("tabWidget")
		self.tab = QtWidgets.QWidget()
		self.tab.setObjectName("tab")
		self.owSpacingSensitivityStandoffMidSpan_graphicsView = MatplotlibWidget(self.tab)
		self.owSpacingSensitivityStandoffMidSpan_graphicsView.setGeometry(QtCore.QRect(0, 0, 891, 781))
		self.owSpacingSensitivityStandoffMidSpan_graphicsView.setObjectName("owSpacingSensitivityStandoffMidSpan_graphicsView")
		self.tabWidget.addTab(self.tab, "")
		self.tab_2 = QtWidgets.QWidget()
		self.tab_2.setObjectName("tab_2")
		self.owSpacingSensitivityStandoffCentr_graphicsView = MatplotlibWidget(self.tab_2)
		self.owSpacingSensitivityStandoffCentr_graphicsView.setGeometry(QtCore.QRect(0, 0, 891, 779))
		self.owSpacingSensitivityStandoffCentr_graphicsView.setObjectName("owSpacingSensitivityStandoffCentr_graphicsView")
		self.tabWidget.addTab(self.tab_2, "")
		self.tab_3 = QtWidgets.QWidget()
		self.tab_3.setObjectName("tab_3")
		self.owSpacingSensitivityStandoff_tableWidget = QtWidgets.QTableWidget(self.tab_3)
		self.owSpacingSensitivityStandoff_tableWidget.setGeometry(QtCore.QRect(0, 40, 881, 735))
		self.owSpacingSensitivityStandoff_tableWidget.setObjectName("owSpacingSensitivityStandoff_tableWidget")
		self.owSpacingSensitivityStandoff_tableWidget.setColumnCount(0)
		self.owSpacingSensitivityStandoff_tableWidget.setRowCount(0)
		self.tabWidget.addTab(self.tab_3, "")
		OutputWindow.setCentralWidget(self.centralwidget)
		self.iw_toolBar = QtWidgets.QToolBar(OutputWindow)
		font = QtGui.QFont()
		font.setPointSize(10)
		self.iw_toolBar.setFont(font)
		self.iw_toolBar.setIconSize(QtCore.QSize(30, 30))
		self.iw_toolBar.setObjectName("iw_toolBar")
		OutputWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.iw_toolBar)
		self.menubar = QtWidgets.QMenuBar(OutputWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1321, 26))
		self.menubar.setObjectName("menubar")
		self.menuClose = QtWidgets.QMenu(self.menubar)
		self.menuClose.setObjectName("menuClose")
		OutputWindow.setMenuBar(self.menubar)
		self.actionNew = QtWidgets.QAction(OutputWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("iconos/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionNew.setIcon(icon)
		self.actionNew.setObjectName("actionNew")
		self.actionOpen = QtWidgets.QAction(OutputWindow)
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap("iconos/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionOpen.setIcon(icon1)
		self.actionOpen.setObjectName("actionOpen")
		self.actionSave = QtWidgets.QAction(OutputWindow)
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap("iconos/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionSave.setIcon(icon2)
		self.actionSave.setObjectName("actionSave")
		self.actionSave_As = QtWidgets.QAction(OutputWindow)
		self.actionSave_As.setObjectName("actionSave_As")
		self.actionPrint = QtWidgets.QAction(OutputWindow)
		self.actionPrint.setObjectName("actionPrint")
		self.actionPrint_2 = QtWidgets.QAction(OutputWindow)
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap("iconos/document-print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionPrint_2.setIcon(icon3)
		self.actionPrint_2.setObjectName("actionPrint_2")
		self.actionExit = QtWidgets.QAction(OutputWindow)
		self.actionExit.setObjectName("actionExit")
		self.actionCopy_Selection = QtWidgets.QAction(OutputWindow)
		self.actionCopy_Selection.setObjectName("actionCopy_Selection")
		self.actionPaste = QtWidgets.QAction(OutputWindow)
		self.actionPaste.setObjectName("actionPaste")
		self.actionOne_Span_Analysis = QtWidgets.QAction(OutputWindow)
		icon4 = QtGui.QIcon()
		icon4.addPixmap(QtGui.QPixmap("iconos/games-solve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionOne_Span_Analysis.setIcon(icon4)
		self.actionOne_Span_Analysis.setObjectName("actionOne_Span_Analysis")
		self.actionUnit_Setting = QtWidgets.QAction(OutputWindow)
		self.actionUnit_Setting.setObjectName("actionUnit_Setting")
		self.actionUnit_Conversion = QtWidgets.QAction(OutputWindow)
		icon5 = QtGui.QIcon()
		icon5.addPixmap(QtGui.QPixmap("iconos/measure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionUnit_Conversion.setIcon(icon5)
		self.actionUnit_Conversion.setObjectName("actionUnit_Conversion")
		self.actionCalculator = QtWidgets.QAction(OutputWindow)
		icon6 = QtGui.QIcon()
		icon6.addPixmap(QtGui.QPixmap("iconos/accessories-calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionCalculator.setIcon(icon6)
		self.actionCalculator.setObjectName("actionCalculator")
		self.actionNotepad = QtWidgets.QAction(OutputWindow)
		icon7 = QtGui.QIcon()
		icon7.addPixmap(QtGui.QPixmap("iconos/story-editor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionNotepad.setIcon(icon7)
		self.actionNotepad.setObjectName("actionNotepad")
		self.actionAbout = QtWidgets.QAction(OutputWindow)
		icon8 = QtGui.QIcon()
		icon8.addPixmap(QtGui.QPixmap("iconos/system-help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionAbout.setIcon(icon8)
		self.actionAbout.setObjectName("actionAbout")
		self.actionAbbreviation = QtWidgets.QAction(OutputWindow)
		self.actionAbbreviation.setObjectName("actionAbbreviation")
		self.actionDisclaimer = QtWidgets.QAction(OutputWindow)
		self.actionDisclaimer.setObjectName("actionDisclaimer")
		self.actionStar_Calculation = QtWidgets.QAction(OutputWindow)
		icon9 = QtGui.QIcon()
		icon9.addPixmap(QtGui.QPixmap("iconos/arrow-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionStar_Calculation.setIcon(icon9)
		self.actionStar_Calculation.setObjectName("actionStar_Calculation")
		self.actionReturn_to_Input_Window = QtWidgets.QAction(OutputWindow)
		self.actionReturn_to_Input_Window.setObjectName("actionReturn_to_Input_Window")
		self.actionPrint_All = QtWidgets.QAction(OutputWindow)
		self.actionPrint_All.setIcon(icon3)
		self.actionPrint_All.setObjectName("actionPrint_All")
		self.actionPrint_Summary_Only = QtWidgets.QAction(OutputWindow)
		self.actionPrint_Summary_Only.setObjectName("actionPrint_Summary_Only")
		self.actionGenerate_Report = QtWidgets.QAction(OutputWindow)
		self.actionGenerate_Report.setObjectName("actionGenerate_Report")
		self.actionStandoff_Profile = QtWidgets.QAction(OutputWindow)
		self.actionStandoff_Profile.setObjectName("actionStandoff_Profile")
		self.action3D_Wellpath = QtWidgets.QAction(OutputWindow)
		self.action3D_Wellpath.setObjectName("action3D_Wellpath")
		self.actionCentralizer = QtWidgets.QAction(OutputWindow)
		self.actionCentralizer.setObjectName("actionCentralizer")
		self.actionGraph_Settings = QtWidgets.QAction(OutputWindow)
		self.actionGraph_Settings.setObjectName("actionGraph_Settings")
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionStar_Calculation)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionUnit_Conversion)
		self.iw_toolBar.addAction(self.actionCalculator)
		self.iw_toolBar.addAction(self.actionNotepad)
		self.iw_toolBar.addSeparator()
		self.menubar.addAction(self.menuClose.menuAction())

		self.retranslateUi(OutputWindow)
		self.tabWidget.setCurrentIndex(0)
		self.actionExit.triggered.connect(OutputWindow.close)
		QtCore.QMetaObject.connectSlotsByName(OutputWindow)

	def retranslateUi(self, OutputWindow):
		_translate = QtCore.QCoreApplication.translate
		OutputWindow.setWindowTitle(_translate("OutputWindow", "Central Software - Centralizer Spacing Sensitivity Analysis"))
		self.label.setText(_translate("OutputWindow", "Sensitivity study is only for the <Specify spacing> mode."))
		self.label_3.setText(_translate("OutputWindow", "Pipes:"))
		self.label_4.setText(_translate("OutputWindow", "Spacing range:"))
		self.owSpacingSensitivityCalculate_pushButton.setText(_translate("OutputWindow", "Calculate"))
		self.owSpacingSensitivityMinMaxSpacing_tableWidget.setSortingEnabled(False)
		item = self.owSpacingSensitivityMinMaxSpacing_tableWidget.verticalHeaderItem(0)
		item.setText(_translate("OutputWindow", "Min. spacing                                "))
		item = self.owSpacingSensitivityMinMaxSpacing_tableWidget.verticalHeaderItem(1)
		item.setText(_translate("OutputWindow", "Max. spacing                               "))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("OutputWindow", "Standoff @ Mid Span"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("OutputWindow", "Standoff @ cent."))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("OutputWindow", "Table"))
		self.iw_toolBar.setWindowTitle(_translate("OutputWindow", "toolBar"))
		self.menuClose.setTitle(_translate("OutputWindow", "Close"))
		self.actionNew.setText(_translate("OutputWindow", "New"))
		self.actionNew.setShortcut(_translate("OutputWindow", "Ctrl+N"))
		self.actionOpen.setText(_translate("OutputWindow", "Open..."))
		self.actionOpen.setShortcut(_translate("OutputWindow", "Ctrl+O"))
		self.actionSave.setText(_translate("OutputWindow", "Save"))
		self.actionSave.setShortcut(_translate("OutputWindow", "Ctrl+S"))
		self.actionSave_As.setText(_translate("OutputWindow", "Save As..."))
		self.actionPrint.setText(_translate("OutputWindow", "Print Preview..."))
		self.actionPrint_2.setText(_translate("OutputWindow", "Print.."))
		self.actionPrint_2.setShortcut(_translate("OutputWindow", "Ctrl+P"))
		self.actionExit.setText(_translate("OutputWindow", "Exit"))
		self.actionCopy_Selection.setText(_translate("OutputWindow", "Copy Selection"))
		self.actionPaste.setText(_translate("OutputWindow", "Paste"))
		self.actionOne_Span_Analysis.setText(_translate("OutputWindow", "One Span Analysis..."))
		self.actionUnit_Setting.setText(_translate("OutputWindow", "Unit Setting..."))
		self.actionUnit_Conversion.setText(_translate("OutputWindow", "Unit Conversion..."))
		self.actionCalculator.setText(_translate("OutputWindow", "Calculator..."))
		self.actionNotepad.setText(_translate("OutputWindow", "Notepad..."))
		self.actionAbout.setText(_translate("OutputWindow", "About..."))
		self.actionAbbreviation.setText(_translate("OutputWindow", "Abbreviation..."))
		self.actionDisclaimer.setText(_translate("OutputWindow", "Disclaimer..."))
		self.actionStar_Calculation.setText(_translate("OutputWindow", "Star Calculation"))
		self.actionStar_Calculation.setShortcut(_translate("OutputWindow", "F5"))
		self.actionReturn_to_Input_Window.setText(_translate("OutputWindow", "Return to Input Window"))
		self.actionPrint_All.setText(_translate("OutputWindow", "Print Report ..."))
		self.actionPrint_Summary_Only.setText(_translate("OutputWindow", "Print Summary Only ..."))
		self.actionGenerate_Report.setText(_translate("OutputWindow", "Generate Report ..."))
		self.actionStandoff_Profile.setText(_translate("OutputWindow", "Standoff Profile ..."))
		self.action3D_Wellpath.setText(_translate("OutputWindow", "3D Parameter Visualization ..."))
		self.actionCentralizer.setText(_translate("OutputWindow", "Centralizer Spacing Sensitivity Analysis ..."))
		self.actionGraph_Settings.setText(_translate("OutputWindow", "Graph Settings ..."))

from matplotlibwidget import MatplotlibWidget
