# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InputWindow_Vst.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InputWindow(object):
	def setupUi(self, InputWindow):
		InputWindow.setObjectName("InputWindow")
		InputWindow.resize(1366, 913)
		self.centralwidget = QtWidgets.QWidget(InputWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.Menu = QtWidgets.QTabWidget(self.centralwidget)
		self.Menu.setEnabled(True)
		self.Menu.setGeometry(QtCore.QRect(15, 10, 1341, 785))
		font = QtGui.QFont()
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		font.setStyleStrategy(QtGui.QFont.PreferDefault)
		self.Menu.setFont(font)
		self.Menu.setTabPosition(QtWidgets.QTabWidget.West)
		self.Menu.setTabShape(QtWidgets.QTabWidget.Rounded)
		self.Menu.setIconSize(QtCore.QSize(20, 20))
		self.Menu.setElideMode(QtCore.Qt.ElideNone)
		self.Menu.setObjectName("Menu")
		self.tab = QtWidgets.QWidget()
		self.tab.setObjectName("tab")
		self.groupBox = QtWidgets.QGroupBox(self.tab)
		self.groupBox.setGeometry(QtCore.QRect(30, 50, 1051, 541))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.groupBox.setFont(font)
		self.groupBox.setObjectName("groupBox")
		self.s1Info_tableWidget = QtWidgets.QTableWidget(self.groupBox)
		self.s1Info_tableWidget.setGeometry(QtCore.QRect(40, 50, 691, 371))
		self.s1Info_tableWidget.setColumnCount(1)
		self.s1Info_tableWidget.setObjectName("s1Info_tableWidget")
		self.s1Info_tableWidget.setRowCount(6)
		item = QtWidgets.QTableWidgetItem()
		self.s1Info_tableWidget.setVerticalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.s1Info_tableWidget.setVerticalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.s1Info_tableWidget.setVerticalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.s1Info_tableWidget.setVerticalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.s1Info_tableWidget.setVerticalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.s1Info_tableWidget.setVerticalHeaderItem(5, item)
		self.s1Info_tableWidget.horizontalHeader().setVisible(False)
		self.s1Info_tableWidget.horizontalHeader().setDefaultSectionSize(600)
		self.s1Info_tableWidget.verticalHeader().setDefaultSectionSize(60)
		self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
		self.groupBox_2.setGeometry(QtCore.QRect(750, 40, 231, 241))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.groupBox_2.setFont(font)
		self.groupBox_2.setObjectName("groupBox_2")
		self.s1USOF_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
		self.s1USOF_radioButton.setGeometry(QtCore.QRect(40, 40, 141, 25))
		self.s1USOF_radioButton.setObjectName("s1USOF_radioButton")
		self.s1Metric_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
		self.s1Metric_radioButton.setGeometry(QtCore.QRect(40, 80, 141, 25))
		self.s1Metric_radioButton.setObjectName("s1Metric_radioButton")
		self.s1Customized_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
		self.s1Customized_radioButton.setGeometry(QtCore.QRect(40, 120, 141, 28))
		self.s1Customized_radioButton.setChecked(True)
		self.s1Customized_radioButton.setObjectName("s1Customized_radioButton")
		self.s1UnitSetting_pushButton = QtWidgets.QPushButton(self.groupBox_2)
		self.s1UnitSetting_pushButton.setGeometry(QtCore.QRect(30, 170, 171, 41))
		self.s1UnitSetting_pushButton.setObjectName("s1UnitSetting_pushButton")
		self.s1SelectDirectory_pushButton = QtWidgets.QPushButton(self.groupBox)
		self.s1SelectDirectory_pushButton.setGeometry(QtCore.QRect(780, 360, 171, 41))
		self.s1SelectDirectory_pushButton.setObjectName("s1SelectDirectory_pushButton")
		self.Menu.addTab(self.tab, "")
		self.tab_3 = QtWidgets.QWidget()
		self.tab_3.setObjectName("tab_3")
		self.tabWidget = QtWidgets.QTabWidget(self.tab_3)
		self.tabWidget.setEnabled(True)
		self.tabWidget.setGeometry(QtCore.QRect(10, 0, 1471, 911))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.tabWidget.setFont(font)
		self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
		self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
		self.tabWidget.setUsesScrollButtons(True)
		self.tabWidget.setDocumentMode(False)
		self.tabWidget.setTabsClosable(False)
		self.tabWidget.setMovable(False)
		self.tabWidget.setTabBarAutoHide(False)
		self.tabWidget.setObjectName("tabWidget")
		self.tab_5 = QtWidgets.QWidget()
		self.tab_5.setObjectName("tab_5")
		self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_5)
		self.verticalLayoutWidget.setGeometry(QtCore.QRect(930, 10, 191, 151))
		self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setSpacing(0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.s2Import_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
		self.s2Import_pushButton.setObjectName("s2Import_pushButton")
		self.verticalLayout.addWidget(self.s2Import_pushButton)
		self.s2Remove_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
		self.s2Remove_pushButton.setObjectName("s2Remove_pushButton")
		self.verticalLayout.addWidget(self.s2Remove_pushButton)
		self.s2Calculate_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.s2Calculate_pushButton.setFont(font)
		self.s2Calculate_pushButton.setObjectName("s2Calculate_pushButton")
		self.verticalLayout.addWidget(self.s2Calculate_pushButton)
		self.s2SurveyTortuosity_groupBox = QtWidgets.QGroupBox(self.tab_5)
		self.s2SurveyTortuosity_groupBox.setEnabled(False)
		self.s2SurveyTortuosity_groupBox.setGeometry(QtCore.QRect(20, 480, 891, 241))
		self.s2SurveyTortuosity_groupBox.setObjectName("s2SurveyTortuosity_groupBox")
		self.s2SurveyTortuosity_tableWidget = QtWidgets.QTableWidget(self.s2SurveyTortuosity_groupBox)
		self.s2SurveyTortuosity_tableWidget.setGeometry(QtCore.QRect(10, 50, 541, 171))
		self.s2SurveyTortuosity_tableWidget.setStyleSheet("")
		self.s2SurveyTortuosity_tableWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
		self.s2SurveyTortuosity_tableWidget.setAlternatingRowColors(True)
		self.s2SurveyTortuosity_tableWidget.setRowCount(10)
		self.s2SurveyTortuosity_tableWidget.setObjectName("s2SurveyTortuosity_tableWidget")
		self.s2SurveyTortuosity_tableWidget.setColumnCount(4)
		item = QtWidgets.QTableWidgetItem()
		self.s2SurveyTortuosity_tableWidget.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.s2SurveyTortuosity_tableWidget.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.s2SurveyTortuosity_tableWidget.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.s2SurveyTortuosity_tableWidget.setHorizontalHeaderItem(3, item)
		self.s2SurveyTortuosity_tableWidget.horizontalHeader().setDefaultSectionSize(121)
		self.s2SurveyTortuosity_tableWidget.verticalHeader().setDefaultSectionSize(25)
		self.s2SurveyTortuosity_tableWidget.verticalHeader().setMinimumSectionSize(25)
		self.s2TortuosityInterval_tableWidget = QtWidgets.QTableWidget(self.s2SurveyTortuosity_groupBox)
		self.s2TortuosityInterval_tableWidget.setGeometry(QtCore.QRect(570, 50, 261, 32))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.s2TortuosityInterval_tableWidget.setFont(font)
		self.s2TortuosityInterval_tableWidget.setAutoFillBackground(False)
		self.s2TortuosityInterval_tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.s2TortuosityInterval_tableWidget.setColumnCount(1)
		self.s2TortuosityInterval_tableWidget.setObjectName("s2TortuosityInterval_tableWidget")
		self.s2TortuosityInterval_tableWidget.setRowCount(1)
		item = QtWidgets.QTableWidgetItem()
		self.s2TortuosityInterval_tableWidget.setVerticalHeaderItem(0, item)
		self.s2TortuosityInterval_tableWidget.horizontalHeader().setVisible(False)
		self.s2TortuosityInterval_tableWidget.horizontalHeader().setCascadingSectionResizes(False)
		self.s2TortuosityInterval_tableWidget.horizontalHeader().setDefaultSectionSize(140)
		self.s2TortuosityInterval_tableWidget.horizontalHeader().setHighlightSections(True)
		self.s2TortuosityInterval_tableWidget.horizontalHeader().setSortIndicatorShown(False)
		self.s2TortuosityInterval_tableWidget.horizontalHeader().setStretchLastSection(False)
		self.s2TortuosityInterval_tableWidget.verticalHeader().setDefaultSectionSize(30)
		self.s2TortuosityInterval_tableWidget.verticalHeader().setMinimumSectionSize(28)
		self.s2TortuosityInterval_tableWidget.verticalHeader().setSortIndicatorShown(False)
		self.s2DataSurvey_tableWidget = QtWidgets.QTableWidget(self.tab_5)
		self.s2DataSurvey_tableWidget.setGeometry(QtCore.QRect(20, 10, 891, 451))
		self.s2DataSurvey_tableWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
		self.s2DataSurvey_tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.s2DataSurvey_tableWidget.setStyleSheet("")
		self.s2DataSurvey_tableWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
		self.s2DataSurvey_tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.s2DataSurvey_tableWidget.setMidLineWidth(1)
		self.s2DataSurvey_tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
		self.s2DataSurvey_tableWidget.setAutoScrollMargin(16)
		self.s2DataSurvey_tableWidget.setAlternatingRowColors(True)
		self.s2DataSurvey_tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
		self.s2DataSurvey_tableWidget.setGridStyle(QtCore.Qt.SolidLine)
		self.s2DataSurvey_tableWidget.setWordWrap(True)
		self.s2DataSurvey_tableWidget.setCornerButtonEnabled(True)
		self.s2DataSurvey_tableWidget.setRowCount(1000)
		self.s2DataSurvey_tableWidget.setColumnCount(8)
		self.s2DataSurvey_tableWidget.setObjectName("s2DataSurvey_tableWidget")
		item = QtWidgets.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setHorizontalHeaderItem(5, item)
		item = QtWidgets.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setHorizontalHeaderItem(6, item)
		item = QtWidgets.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setHorizontalHeaderItem(7, item)
		item = QtWidgets.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setItem(0, 0, item)
		item = QtWidgets.QTableWidgetItem()
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.NoBrush)
		item.setForeground(brush)
		self.s2DataSurvey_tableWidget.setItem(0, 3, item)
		self.s2DataSurvey_tableWidget.horizontalHeader().setCascadingSectionResizes(False)
		self.s2DataSurvey_tableWidget.horizontalHeader().setDefaultSectionSize(115)
		self.s2DataSurvey_tableWidget.horizontalHeader().setHighlightSections(True)
		self.s2DataSurvey_tableWidget.horizontalHeader().setMinimumSectionSize(100)
		self.s2DataSurvey_tableWidget.horizontalHeader().setSortIndicatorShown(False)
		self.s2DataSurvey_tableWidget.horizontalHeader().setStretchLastSection(False)
		self.s2DataSurvey_tableWidget.verticalHeader().setCascadingSectionResizes(False)
		self.s2DataSurvey_tableWidget.verticalHeader().setDefaultSectionSize(25)
		self.s2DataSurvey_tableWidget.verticalHeader().setMinimumSectionSize(25)
		self.s2DataSurvey_tableWidget.verticalHeader().setSortIndicatorShown(False)
		self.s2DataSurvey_tableWidget.verticalHeader().setStretchLastSection(False)
		self.s2SurveyTortuosity_checkBox = QtWidgets.QCheckBox(self.tab_5)
		self.s2SurveyTortuosity_checkBox.setGeometry(QtCore.QRect(930, 240, 221, 31))
		self.s2SurveyTortuosity_checkBox.setChecked(False)
		self.s2SurveyTortuosity_checkBox.setObjectName("s2SurveyTortuosity_checkBox")
		self.s2KOP_tableWidget = QtWidgets.QTableWidget(self.tab_5)
		self.s2KOP_tableWidget.setGeometry(QtCore.QRect(930, 180, 231, 32))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.s2KOP_tableWidget.setFont(font)
		self.s2KOP_tableWidget.setAutoFillBackground(False)
		self.s2KOP_tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.s2KOP_tableWidget.setColumnCount(1)
		self.s2KOP_tableWidget.setObjectName("s2KOP_tableWidget")
		self.s2KOP_tableWidget.setRowCount(1)
		item = QtWidgets.QTableWidgetItem()
		self.s2KOP_tableWidget.setVerticalHeaderItem(0, item)
		self.s2KOP_tableWidget.horizontalHeader().setVisible(False)
		self.s2KOP_tableWidget.horizontalHeader().setCascadingSectionResizes(False)
		self.s2KOP_tableWidget.horizontalHeader().setDefaultSectionSize(140)
		self.s2KOP_tableWidget.horizontalHeader().setHighlightSections(True)
		self.s2KOP_tableWidget.horizontalHeader().setSortIndicatorShown(False)
		self.s2KOP_tableWidget.horizontalHeader().setStretchLastSection(False)
		self.s2KOP_tableWidget.verticalHeader().setDefaultSectionSize(30)
		self.s2KOP_tableWidget.verticalHeader().setMinimumSectionSize(28)
		self.s2KOP_tableWidget.verticalHeader().setSortIndicatorShown(False)
		self.tabWidget.addTab(self.tab_5, "")
		self.tab_6 = QtWidgets.QWidget()
		self.tab_6.setObjectName("tab_6")
		self.s2SectionView_graphicsView = MatplotlibWidget(self.tab_6)
		self.s2SectionView_graphicsView.setGeometry(QtCore.QRect(60, 20, 790, 710))
		self.s2SectionView_graphicsView.setObjectName("s2SectionView_graphicsView")
		self.tabWidget.addTab(self.tab_6, "")
		self.tab_8 = QtWidgets.QWidget()
		self.tab_8.setObjectName("tab_8")
		self.s2TriDView_graphicsView = Matplotlib3DWidget(self.tab_8)
		self.s2TriDView_graphicsView.setGeometry(QtCore.QRect(60, 20, 790, 710))
		self.s2TriDView_graphicsView.setObjectName("s2TriDView_graphicsView")
		self.tabWidget.addTab(self.tab_8, "")
		self.tab_7 = QtWidgets.QWidget()
		self.tab_7.setObjectName("tab_7")
		self.s2PlanView_graphicsView = MatplotlibWidget(self.tab_7)
		self.s2PlanView_graphicsView.setGeometry(QtCore.QRect(60, 20, 790, 710))
		self.s2PlanView_graphicsView.setObjectName("s2PlanView_graphicsView")
		self.tabWidget.addTab(self.tab_7, "")
		self.tab_9 = QtWidgets.QWidget()
		self.tab_9.setObjectName("tab_9")
		self.s2Dogleg_graphicsView = MatplotlibWidget(self.tab_9)
		self.s2Dogleg_graphicsView.setGeometry(QtCore.QRect(60, 20, 790, 710))
		self.s2Dogleg_graphicsView.setObjectName("s2Dogleg_graphicsView")
		self.tabWidget.addTab(self.tab_9, "")
		self.Menu.addTab(self.tab_3, "")
		self.tab_4 = QtWidgets.QWidget()
		self.tab_4.setObjectName("tab_4")
		self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
		self.groupBox_4.setEnabled(True)
		self.groupBox_4.setGeometry(QtCore.QRect(10, 6, 1281, 194))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.groupBox_4.setFont(font)
		self.groupBox_4.setObjectName("groupBox_4")
		self.s3WellboreOuterStages_tableWidget = QtWidgets.QTableWidget(self.groupBox_4)
		self.s3WellboreOuterStages_tableWidget.setGeometry(QtCore.QRect(11, 30, 981, 155))
		self.s3WellboreOuterStages_tableWidget.setStyleSheet("")
		self.s3WellboreOuterStages_tableWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
		self.s3WellboreOuterStages_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
		self.s3WellboreOuterStages_tableWidget.setAlternatingRowColors(True)
		self.s3WellboreOuterStages_tableWidget.setRowCount(500)
		self.s3WellboreOuterStages_tableWidget.setObjectName("s3WellboreOuterStages_tableWidget")
		self.s3WellboreOuterStages_tableWidget.setColumnCount(6)
		item = QtWidgets.QTableWidgetItem()
		self.s3WellboreOuterStages_tableWidget.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3WellboreOuterStages_tableWidget.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3WellboreOuterStages_tableWidget.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3WellboreOuterStages_tableWidget.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3WellboreOuterStages_tableWidget.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3WellboreOuterStages_tableWidget.setHorizontalHeaderItem(5, item)
		self.s3WellboreOuterStages_tableWidget.horizontalHeader().setDefaultSectionSize(150)
		self.s3WellboreOuterStages_tableWidget.verticalHeader().setDefaultSectionSize(28)
		self.groupBox_5 = QtWidgets.QGroupBox(self.tab_4)
		self.groupBox_5.setGeometry(QtCore.QRect(10, 205, 1281, 567))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.groupBox_5.setFont(font)
		self.groupBox_5.setObjectName("groupBox_5")
		self.frame = QtWidgets.QFrame(self.groupBox_5)
		self.frame.setGeometry(QtCore.QRect(10, 30, 561, 521))
		self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
		self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame.setObjectName("frame")
		self.s3WellboreInnerStages_tableWidget = QtWidgets.QTableWidget(self.frame)
		self.s3WellboreInnerStages_tableWidget.setGeometry(QtCore.QRect(9, 10, 542, 431))
		self.s3WellboreInnerStages_tableWidget.setStyleSheet("")
		self.s3WellboreInnerStages_tableWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
		self.s3WellboreInnerStages_tableWidget.setAlternatingRowColors(True)
		self.s3WellboreInnerStages_tableWidget.setRowCount(10)
		self.s3WellboreInnerStages_tableWidget.setObjectName("s3WellboreInnerStages_tableWidget")
		self.s3WellboreInnerStages_tableWidget.setColumnCount(3)
		item = QtWidgets.QTableWidgetItem()
		self.s3WellboreInnerStages_tableWidget.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3WellboreInnerStages_tableWidget.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3WellboreInnerStages_tableWidget.setHorizontalHeaderItem(2, item)
		self.s3WellboreInnerStages_tableWidget.horizontalHeader().setDefaultSectionSize(160)
		self.s3WellboreInnerStages_tableWidget.horizontalHeader().setSortIndicatorShown(False)
		self.s3WellboreInnerStages_tableWidget.horizontalHeader().setStretchLastSection(False)
		self.s3WellboreInnerStages_tableWidget.verticalHeader().setDefaultSectionSize(56)
		self.s3WellboreInnerStages_tableWidget.verticalHeader().setMinimumSectionSize(50)
		self.s3UpdateInnerStages_pushButton = QtWidgets.QPushButton(self.frame)
		self.s3UpdateInnerStages_pushButton.setGeometry(QtCore.QRect(10, 460, 221, 41))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.s3UpdateInnerStages_pushButton.setFont(font)
		self.s3UpdateInnerStages_pushButton.setObjectName("s3UpdateInnerStages_pushButton")
		self.s3InnerStageToolkit_tabWidget = QtWidgets.QTabWidget(self.groupBox_5)
		self.s3InnerStageToolkit_tabWidget.setEnabled(False)
		self.s3InnerStageToolkit_tabWidget.setGeometry(QtCore.QRect(590, 15, 691, 461))
		self.s3InnerStageToolkit_tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.s3InnerStageToolkit_tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
		self.s3InnerStageToolkit_tabWidget.setObjectName("s3InnerStageToolkit_tabWidget")
		self.tab_10 = QtWidgets.QWidget()
		self.tab_10.setObjectName("tab_10")
		self.s3ODID_pushButton = QtWidgets.QPushButton(self.tab_10)
		self.s3ODID_pushButton.setGeometry(QtCore.QRect(490, 80, 111, 31))
		self.s3ODID_pushButton.setObjectName("s3ODID_pushButton")
		self.s3ODWt_pushButton = QtWidgets.QPushButton(self.tab_10)
		self.s3ODWt_pushButton.setGeometry(QtCore.QRect(490, 140, 111, 31))
		self.s3ODWt_pushButton.setObjectName("s3ODWt_pushButton")
		self.s3PipeProperties_tableWidget = QtWidgets.QTableWidget(self.tab_10)
		self.s3PipeProperties_tableWidget.setGeometry(QtCore.QRect(14, 50, 461, 332))
		font = QtGui.QFont()
		font.setPointSize(9)
		self.s3PipeProperties_tableWidget.setFont(font)
		self.s3PipeProperties_tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.s3PipeProperties_tableWidget.setColumnCount(1)
		self.s3PipeProperties_tableWidget.setObjectName("s3PipeProperties_tableWidget")
		self.s3PipeProperties_tableWidget.setRowCount(11)
		item = QtWidgets.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setKerning(False)
		item.setFont(font)
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(5, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(6, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(7, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(8, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(9, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(10, item)
		self.s3PipeProperties_tableWidget.horizontalHeader().setVisible(False)
		self.s3PipeProperties_tableWidget.horizontalHeader().setDefaultSectionSize(250)
		self.s3PipeProperties_tableWidget.horizontalHeader().setMinimumSectionSize(120)
		self.s3PipeProperties_tableWidget.verticalHeader().setDefaultSectionSize(30)
		self.s3PipeProperties_tableWidget.verticalHeader().setMinimumSectionSize(20)
		self.s3StageNumber_label1 = QtWidgets.QLabel(self.tab_10)
		self.s3StageNumber_label1.setGeometry(QtCore.QRect(510, 10, 100, 30))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.s3StageNumber_label1.setFont(font)
		self.s3StageNumber_label1.setObjectName("s3StageNumber_label1")
		self.s3InnerStageToolkit_tabWidget.addTab(self.tab_10, "")
		self.tab_11 = QtWidgets.QWidget()
		self.tab_11.setObjectName("tab_11")
		self.ABC_tabWidget = QtWidgets.QTabWidget(self.tab_11)
		self.ABC_tabWidget.setEnabled(False)
		self.ABC_tabWidget.setGeometry(QtCore.QRect(10, 50, 611, 371))
		font = QtGui.QFont()
		font.setBold(False)
		font.setWeight(50)
		font.setStrikeOut(False)
		font.setKerning(True)
		self.ABC_tabWidget.setFont(font)
		self.ABC_tabWidget.setMouseTracking(False)
		self.ABC_tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
		self.ABC_tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
		self.ABC_tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
		self.ABC_tabWidget.setIconSize(QtCore.QSize(20, 20))
		self.ABC_tabWidget.setElideMode(QtCore.Qt.ElideNone)
		self.ABC_tabWidget.setDocumentMode(False)
		self.ABC_tabWidget.setTabsClosable(False)
		self.ABC_tabWidget.setMovable(False)
		self.ABC_tabWidget.setObjectName("ABC_tabWidget")
		self.tab_A = QtWidgets.QWidget()
		self.tab_A.setObjectName("tab_A")
		self.s3BowSpringCentralizer_radioButton_A = QtWidgets.QRadioButton(self.tab_A)
		self.s3BowSpringCentralizer_radioButton_A.setGeometry(QtCore.QRect(24, 20, 109, 25))
		self.s3BowSpringCentralizer_radioButton_A.setChecked(True)
		self.s3BowSpringCentralizer_radioButton_A.setObjectName("s3BowSpringCentralizer_radioButton_A")
		self.s3ResinCentralizer_radioButton_A = QtWidgets.QRadioButton(self.tab_A)
		self.s3ResinCentralizer_radioButton_A.setGeometry(QtCore.QRect(24, 70, 64, 25))
		self.s3ResinCentralizer_radioButton_A.setObjectName("s3ResinCentralizer_radioButton_A")
		self.s3CentralizerProperties_tableWidget_A = QtWidgets.QTableWidget(self.tab_A)
		self.s3CentralizerProperties_tableWidget_A.setGeometry(QtCore.QRect(20, 160, 340, 200))
		self.s3CentralizerProperties_tableWidget_A.setFocusPolicy(QtCore.Qt.WheelFocus)
		self.s3CentralizerProperties_tableWidget_A.setRowCount(10)
		self.s3CentralizerProperties_tableWidget_A.setColumnCount(1)
		self.s3CentralizerProperties_tableWidget_A.setObjectName("s3CentralizerProperties_tableWidget_A")
		self.s3CentralizerProperties_tableWidget_A.horizontalHeader().setVisible(False)
		self.s3CentralizerProperties_tableWidget_A.horizontalHeader().setDefaultSectionSize(150)
		self.s3CentralizerProperties_tableWidget_A.horizontalHeader().setMinimumSectionSize(120)
		self.s3CentralizerProperties_tableWidget_A.verticalHeader().setDefaultSectionSize(30)
		self.s3CentralizerProperties_tableWidget_A.verticalHeader().setMinimumSectionSize(28)
		self.s3Location_label_A = QtWidgets.QLabel(self.tab_A)
		self.s3Location_label_A.setGeometry(QtCore.QRect(380, 20, 71, 21))
		self.s3Location_label_A.setObjectName("s3Location_label_A")
		self.s3CentralizerRunningForce_tableWidget_A = QtWidgets.QTableWidget(self.tab_A)
		self.s3CentralizerRunningForce_tableWidget_A.setEnabled(False)
		self.s3CentralizerRunningForce_tableWidget_A.setGeometry(QtCore.QRect(50, 210, 293, 111))
		font = QtGui.QFont()
		font.setPointSize(9)
		self.s3CentralizerRunningForce_tableWidget_A.setFont(font)
		self.s3CentralizerRunningForce_tableWidget_A.setStyleSheet("")
		self.s3CentralizerRunningForce_tableWidget_A.setFrameShape(QtWidgets.QFrame.WinPanel)
		self.s3CentralizerRunningForce_tableWidget_A.setAlternatingRowColors(True)
		self.s3CentralizerRunningForce_tableWidget_A.setRowCount(10)
		self.s3CentralizerRunningForce_tableWidget_A.setObjectName("s3CentralizerRunningForce_tableWidget_A")
		self.s3CentralizerRunningForce_tableWidget_A.setColumnCount(2)
		item = QtWidgets.QTableWidgetItem()
		self.s3CentralizerRunningForce_tableWidget_A.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3CentralizerRunningForce_tableWidget_A.setHorizontalHeaderItem(1, item)
		self.s3CentralizerRunningForce_tableWidget_A.horizontalHeader().setDefaultSectionSize(120)
		self.s3CentralizerRunningForce_tableWidget_A.horizontalHeader().setMinimumSectionSize(100)
		self.s3CentralizerRunningForce_tableWidget_A.verticalHeader().setDefaultSectionSize(25)
		self.s3CentralizerDB_pushButton_A = QtWidgets.QPushButton(self.tab_A)
		self.s3CentralizerDB_pushButton_A.setGeometry(QtCore.QRect(170, 40, 141, 41))
		self.s3CentralizerDB_pushButton_A.setObjectName("s3CentralizerDB_pushButton_A")
		self.s3CentralizerLocation_tableWidget_A = QtWidgets.QTableWidget(self.tab_A)
		self.s3CentralizerLocation_tableWidget_A.setGeometry(QtCore.QRect(380, 50, 175, 310))
		font = QtGui.QFont()
		font.setPointSize(9)
		self.s3CentralizerLocation_tableWidget_A.setFont(font)
		self.s3CentralizerLocation_tableWidget_A.setStyleSheet("")
		self.s3CentralizerLocation_tableWidget_A.setFrameShape(QtWidgets.QFrame.WinPanel)
		self.s3CentralizerLocation_tableWidget_A.setAlternatingRowColors(True)
		self.s3CentralizerLocation_tableWidget_A.setRowCount(1000)
		self.s3CentralizerLocation_tableWidget_A.setObjectName("s3CentralizerLocation_tableWidget_A")
		self.s3CentralizerLocation_tableWidget_A.setColumnCount(1)
		item = QtWidgets.QTableWidgetItem()
		self.s3CentralizerLocation_tableWidget_A.setHorizontalHeaderItem(0, item)
		self.s3CentralizerLocation_tableWidget_A.horizontalHeader().setDefaultSectionSize(125)
		self.s3CentralizerLocation_tableWidget_A.verticalHeader().setDefaultSectionSize(25)
		self.label = QtWidgets.QLabel(self.tab_A)
		self.label.setGeometry(QtCore.QRect(20, 120, 121, 31))
		self.label.setObjectName("label")
		self.s3CentralizationPattern_spinBox = QtWidgets.QSpinBox(self.tab_A)
		self.s3CentralizationPattern_spinBox.setGeometry(QtCore.QRect(150, 120, 51, 31))
		self.s3CentralizationPattern_spinBox.setMinimum(1)
		self.s3CentralizationPattern_spinBox.setProperty("value", 1)
		self.s3CentralizationPattern_spinBox.setObjectName("s3CentralizationPattern_spinBox")
		self.label_2 = QtWidgets.QLabel(self.tab_A)
		self.label_2.setGeometry(QtCore.QRect(220, 120, 71, 31))
		self.label_2.setObjectName("label_2")
		self.s3CentralizationOffset_spinBox = QtWidgets.QSpinBox(self.tab_A)
		self.s3CentralizationOffset_spinBox.setGeometry(QtCore.QRect(300, 120, 51, 31))
		self.s3CentralizationOffset_spinBox.setMinimum(0)
		self.s3CentralizationOffset_spinBox.setProperty("value", 0)
		self.s3CentralizationOffset_spinBox.setObjectName("s3CentralizationOffset_spinBox")
		self.s3CentralizerRunningForce_tableWidget_A.raise_()
		self.s3BowSpringCentralizer_radioButton_A.raise_()
		self.s3ResinCentralizer_radioButton_A.raise_()
		self.s3CentralizerProperties_tableWidget_A.raise_()
		self.s3Location_label_A.raise_()
		self.s3CentralizerDB_pushButton_A.raise_()
		self.s3CentralizerLocation_tableWidget_A.raise_()
		self.label.raise_()
		self.s3CentralizationPattern_spinBox.raise_()
		self.label_2.raise_()
		self.s3CentralizationOffset_spinBox.raise_()
		self.ABC_tabWidget.addTab(self.tab_A, "")
		self.tab_B = QtWidgets.QWidget()
		self.tab_B.setObjectName("tab_B")
		self.s3CentralizerLocation_tableWidget_B = QtWidgets.QTableWidget(self.tab_B)
		self.s3CentralizerLocation_tableWidget_B.setEnabled(False)
		self.s3CentralizerLocation_tableWidget_B.setGeometry(QtCore.QRect(380, 50, 175, 310))
		font = QtGui.QFont()
		font.setPointSize(9)
		self.s3CentralizerLocation_tableWidget_B.setFont(font)
		self.s3CentralizerLocation_tableWidget_B.setStyleSheet("")
		self.s3CentralizerLocation_tableWidget_B.setFrameShape(QtWidgets.QFrame.WinPanel)
		self.s3CentralizerLocation_tableWidget_B.setAlternatingRowColors(True)
		self.s3CentralizerLocation_tableWidget_B.setRowCount(1000)
		self.s3CentralizerLocation_tableWidget_B.setObjectName("s3CentralizerLocation_tableWidget_B")
		self.s3CentralizerLocation_tableWidget_B.setColumnCount(1)
		item = QtWidgets.QTableWidgetItem()
		self.s3CentralizerLocation_tableWidget_B.setHorizontalHeaderItem(0, item)
		self.s3CentralizerLocation_tableWidget_B.horizontalHeader().setDefaultSectionSize(125)
		self.s3CentralizerLocation_tableWidget_B.verticalHeader().setDefaultSectionSize(25)
		self.s3CentralizerRunningForce_tableWidget_B = QtWidgets.QTableWidget(self.tab_B)
		self.s3CentralizerRunningForce_tableWidget_B.setEnabled(False)
		self.s3CentralizerRunningForce_tableWidget_B.setGeometry(QtCore.QRect(50, 210, 293, 71))
		font = QtGui.QFont()
		font.setPointSize(9)
		self.s3CentralizerRunningForce_tableWidget_B.setFont(font)
		self.s3CentralizerRunningForce_tableWidget_B.setStyleSheet("")
		self.s3CentralizerRunningForce_tableWidget_B.setFrameShape(QtWidgets.QFrame.WinPanel)
		self.s3CentralizerRunningForce_tableWidget_B.setAlternatingRowColors(True)
		self.s3CentralizerRunningForce_tableWidget_B.setRowCount(10)
		self.s3CentralizerRunningForce_tableWidget_B.setObjectName("s3CentralizerRunningForce_tableWidget_B")
		self.s3CentralizerRunningForce_tableWidget_B.setColumnCount(2)
		item = QtWidgets.QTableWidgetItem()
		self.s3CentralizerRunningForce_tableWidget_B.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3CentralizerRunningForce_tableWidget_B.setHorizontalHeaderItem(1, item)
		self.s3CentralizerRunningForce_tableWidget_B.horizontalHeader().setDefaultSectionSize(120)
		self.s3CentralizerRunningForce_tableWidget_B.horizontalHeader().setMinimumSectionSize(100)
		self.s3CentralizerRunningForce_tableWidget_B.verticalHeader().setDefaultSectionSize(25)
		self.s3ResinCentralizer_radioButton_B = QtWidgets.QRadioButton(self.tab_B)
		self.s3ResinCentralizer_radioButton_B.setGeometry(QtCore.QRect(24, 70, 64, 25))
		self.s3ResinCentralizer_radioButton_B.setObjectName("s3ResinCentralizer_radioButton_B")
		self.s3CentralizerProperties_tableWidget_B = QtWidgets.QTableWidget(self.tab_B)
		self.s3CentralizerProperties_tableWidget_B.setEnabled(False)
		self.s3CentralizerProperties_tableWidget_B.setGeometry(QtCore.QRect(20, 160, 340, 200))
		self.s3CentralizerProperties_tableWidget_B.setFocusPolicy(QtCore.Qt.WheelFocus)
		self.s3CentralizerProperties_tableWidget_B.setRowCount(10)
		self.s3CentralizerProperties_tableWidget_B.setColumnCount(1)
		self.s3CentralizerProperties_tableWidget_B.setObjectName("s3CentralizerProperties_tableWidget_B")
		self.s3CentralizerProperties_tableWidget_B.horizontalHeader().setVisible(False)
		self.s3CentralizerProperties_tableWidget_B.horizontalHeader().setDefaultSectionSize(150)
		self.s3CentralizerProperties_tableWidget_B.horizontalHeader().setMinimumSectionSize(120)
		self.s3CentralizerProperties_tableWidget_B.verticalHeader().setDefaultSectionSize(30)
		self.s3CentralizerProperties_tableWidget_B.verticalHeader().setMinimumSectionSize(28)
		self.s3CentralizerDB_pushButton_B = QtWidgets.QPushButton(self.tab_B)
		self.s3CentralizerDB_pushButton_B.setEnabled(False)
		self.s3CentralizerDB_pushButton_B.setGeometry(QtCore.QRect(170, 40, 141, 41))
		self.s3CentralizerDB_pushButton_B.setObjectName("s3CentralizerDB_pushButton_B")
		self.s3BowSpringCentralizer_radioButton_B = QtWidgets.QRadioButton(self.tab_B)
		self.s3BowSpringCentralizer_radioButton_B.setGeometry(QtCore.QRect(24, 20, 109, 25))
		self.s3BowSpringCentralizer_radioButton_B.setObjectName("s3BowSpringCentralizer_radioButton_B")
		self.s3Location_label_B = QtWidgets.QLabel(self.tab_B)
		self.s3Location_label_B.setGeometry(QtCore.QRect(380, 20, 71, 21))
		self.s3Location_label_B.setObjectName("s3Location_label_B")
		self.s3NoneCentralizer_radioButton_B = QtWidgets.QRadioButton(self.tab_B)
		self.s3NoneCentralizer_radioButton_B.setGeometry(QtCore.QRect(24, 120, 95, 25))
		self.s3NoneCentralizer_radioButton_B.setChecked(True)
		self.s3NoneCentralizer_radioButton_B.setObjectName("s3NoneCentralizer_radioButton_B")
		self.ABC_tabWidget.addTab(self.tab_B, "")
		self.tab_C = QtWidgets.QWidget()
		self.tab_C.setObjectName("tab_C")
		self.s3BowSpringCentralizer_radioButton_C = QtWidgets.QRadioButton(self.tab_C)
		self.s3BowSpringCentralizer_radioButton_C.setGeometry(QtCore.QRect(24, 20, 109, 25))
		self.s3BowSpringCentralizer_radioButton_C.setObjectName("s3BowSpringCentralizer_radioButton_C")
		self.s3ResinCentralizer_radioButton_C = QtWidgets.QRadioButton(self.tab_C)
		self.s3ResinCentralizer_radioButton_C.setGeometry(QtCore.QRect(24, 70, 64, 25))
		self.s3ResinCentralizer_radioButton_C.setObjectName("s3ResinCentralizer_radioButton_C")
		self.s3CentralizerProperties_tableWidget_C = QtWidgets.QTableWidget(self.tab_C)
		self.s3CentralizerProperties_tableWidget_C.setEnabled(False)
		self.s3CentralizerProperties_tableWidget_C.setGeometry(QtCore.QRect(20, 160, 340, 200))
		self.s3CentralizerProperties_tableWidget_C.setRowCount(10)
		self.s3CentralizerProperties_tableWidget_C.setColumnCount(1)
		self.s3CentralizerProperties_tableWidget_C.setObjectName("s3CentralizerProperties_tableWidget_C")
		self.s3CentralizerProperties_tableWidget_C.horizontalHeader().setVisible(False)
		self.s3CentralizerProperties_tableWidget_C.horizontalHeader().setDefaultSectionSize(150)
		self.s3CentralizerProperties_tableWidget_C.horizontalHeader().setMinimumSectionSize(120)
		self.s3CentralizerProperties_tableWidget_C.verticalHeader().setDefaultSectionSize(30)
		self.s3CentralizerProperties_tableWidget_C.verticalHeader().setMinimumSectionSize(28)
		self.s3Location_label_C = QtWidgets.QLabel(self.tab_C)
		self.s3Location_label_C.setGeometry(QtCore.QRect(380, 20, 71, 21))
		self.s3Location_label_C.setObjectName("s3Location_label_C")
		self.s3CentralizerRunningForce_tableWidget_C = QtWidgets.QTableWidget(self.tab_C)
		self.s3CentralizerRunningForce_tableWidget_C.setEnabled(False)
		self.s3CentralizerRunningForce_tableWidget_C.setGeometry(QtCore.QRect(60, 190, 293, 61))
		font = QtGui.QFont()
		font.setPointSize(9)
		self.s3CentralizerRunningForce_tableWidget_C.setFont(font)
		self.s3CentralizerRunningForce_tableWidget_C.setStyleSheet("")
		self.s3CentralizerRunningForce_tableWidget_C.setFrameShape(QtWidgets.QFrame.WinPanel)
		self.s3CentralizerRunningForce_tableWidget_C.setAlternatingRowColors(True)
		self.s3CentralizerRunningForce_tableWidget_C.setRowCount(10)
		self.s3CentralizerRunningForce_tableWidget_C.setObjectName("s3CentralizerRunningForce_tableWidget_C")
		self.s3CentralizerRunningForce_tableWidget_C.setColumnCount(2)
		item = QtWidgets.QTableWidgetItem()
		self.s3CentralizerRunningForce_tableWidget_C.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.s3CentralizerRunningForce_tableWidget_C.setHorizontalHeaderItem(1, item)
		self.s3CentralizerRunningForce_tableWidget_C.horizontalHeader().setDefaultSectionSize(120)
		self.s3CentralizerRunningForce_tableWidget_C.horizontalHeader().setMinimumSectionSize(100)
		self.s3CentralizerRunningForce_tableWidget_C.verticalHeader().setDefaultSectionSize(25)
		self.s3CentralizerDB_pushButton_C = QtWidgets.QPushButton(self.tab_C)
		self.s3CentralizerDB_pushButton_C.setEnabled(False)
		self.s3CentralizerDB_pushButton_C.setGeometry(QtCore.QRect(170, 40, 141, 41))
		self.s3CentralizerDB_pushButton_C.setObjectName("s3CentralizerDB_pushButton_C")
		self.s3CentralizerLocation_tableWidget_C = QtWidgets.QTableWidget(self.tab_C)
		self.s3CentralizerLocation_tableWidget_C.setEnabled(False)
		self.s3CentralizerLocation_tableWidget_C.setGeometry(QtCore.QRect(380, 50, 175, 310))
		font = QtGui.QFont()
		font.setPointSize(9)
		self.s3CentralizerLocation_tableWidget_C.setFont(font)
		self.s3CentralizerLocation_tableWidget_C.setStyleSheet("")
		self.s3CentralizerLocation_tableWidget_C.setFrameShape(QtWidgets.QFrame.WinPanel)
		self.s3CentralizerLocation_tableWidget_C.setAlternatingRowColors(True)
		self.s3CentralizerLocation_tableWidget_C.setRowCount(1000)
		self.s3CentralizerLocation_tableWidget_C.setObjectName("s3CentralizerLocation_tableWidget_C")
		self.s3CentralizerLocation_tableWidget_C.setColumnCount(1)
		item = QtWidgets.QTableWidgetItem()
		self.s3CentralizerLocation_tableWidget_C.setHorizontalHeaderItem(0, item)
		self.s3CentralizerLocation_tableWidget_C.horizontalHeader().setDefaultSectionSize(125)
		self.s3CentralizerLocation_tableWidget_C.verticalHeader().setDefaultSectionSize(25)
		self.s3NoneCentralizer_radioButton_C = QtWidgets.QRadioButton(self.tab_C)
		self.s3NoneCentralizer_radioButton_C.setGeometry(QtCore.QRect(24, 120, 95, 25))
		self.s3NoneCentralizer_radioButton_C.setChecked(True)
		self.s3NoneCentralizer_radioButton_C.setObjectName("s3NoneCentralizer_radioButton_C")
		self.s3CentralizerRunningForce_tableWidget_C.raise_()
		self.s3BowSpringCentralizer_radioButton_C.raise_()
		self.s3ResinCentralizer_radioButton_C.raise_()
		self.s3CentralizerProperties_tableWidget_C.raise_()
		self.s3Location_label_C.raise_()
		self.s3CentralizerDB_pushButton_C.raise_()
		self.s3CentralizerLocation_tableWidget_C.raise_()
		self.s3NoneCentralizer_radioButton_C.raise_()
		self.ABC_tabWidget.addTab(self.tab_C, "")
		self.s3EnableCentralization_checkBox = QtWidgets.QCheckBox(self.tab_11)
		self.s3EnableCentralization_checkBox.setGeometry(QtCore.QRect(30, 20, 191, 20))
		self.s3EnableCentralization_checkBox.setObjectName("s3EnableCentralization_checkBox")
		self.s3StageNumber_label2 = QtWidgets.QLabel(self.tab_11)
		self.s3StageNumber_label2.setGeometry(QtCore.QRect(510, 10, 100, 30))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.s3StageNumber_label2.setFont(font)
		self.s3StageNumber_label2.setObjectName("s3StageNumber_label2")
		self.s3StageEnsemble_label = QtWidgets.QLabel(self.tab_11)
		self.s3StageEnsemble_label.setGeometry(QtCore.QRect(630, 60, 41, 351))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.s3StageEnsemble_label.setFont(font)
		self.s3StageEnsemble_label.setAlignment(QtCore.Qt.AlignCenter)
		self.s3StageEnsemble_label.setObjectName("s3StageEnsemble_label")
		self.s3InnerStageToolkit_tabWidget.addTab(self.tab_11, "")
		self.s3ManageLocations_pushButton = QtWidgets.QPushButton(self.groupBox_5)
		self.s3ManageLocations_pushButton.setGeometry(QtCore.QRect(600, 500, 251, 41))
		self.s3ManageLocations_pushButton.setObjectName("s3ManageLocations_pushButton")
		self.s3Plot3DSO_pushButton = QtWidgets.QPushButton(self.groupBox_5)
		self.s3Plot3DSO_pushButton.setGeometry(QtCore.QRect(880, 500, 251, 41))
		self.s3Plot3DSO_pushButton.setObjectName("s3Plot3DSO_pushButton")
		self.Menu.addTab(self.tab_4, "")
		self.tab_2 = QtWidgets.QWidget()
		self.tab_2.setObjectName("tab_2")
		self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
		self.groupBox_7.setEnabled(True)
		self.groupBox_7.setGeometry(QtCore.QRect(20, 20, 591, 731))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.groupBox_7.setFont(font)
		self.groupBox_7.setObjectName("groupBox_7")
		self.s4Settings_tableWidget = QtWidgets.QTableWidget(self.groupBox_7)
		self.s4Settings_tableWidget.setGeometry(QtCore.QRect(10, 40, 401, 152))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.s4Settings_tableWidget.setFont(font)
		self.s4Settings_tableWidget.setAutoFillBackground(False)
		self.s4Settings_tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.s4Settings_tableWidget.setColumnCount(1)
		self.s4Settings_tableWidget.setObjectName("s4Settings_tableWidget")
		self.s4Settings_tableWidget.setRowCount(5)
		item = QtWidgets.QTableWidgetItem()
		self.s4Settings_tableWidget.setVerticalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.s4Settings_tableWidget.setVerticalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.s4Settings_tableWidget.setVerticalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.s4Settings_tableWidget.setVerticalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.s4Settings_tableWidget.setVerticalHeaderItem(4, item)
		self.s4Settings_tableWidget.horizontalHeader().setVisible(False)
		self.s4Settings_tableWidget.horizontalHeader().setCascadingSectionResizes(False)
		self.s4Settings_tableWidget.horizontalHeader().setDefaultSectionSize(100)
		self.s4Settings_tableWidget.horizontalHeader().setHighlightSections(True)
		self.s4Settings_tableWidget.horizontalHeader().setMinimumSectionSize(30)
		self.s4Settings_tableWidget.horizontalHeader().setSortIndicatorShown(False)
		self.s4Settings_tableWidget.horizontalHeader().setStretchLastSection(False)
		self.s4Settings_tableWidget.verticalHeader().setDefaultSectionSize(30)
		self.s4Settings_tableWidget.verticalHeader().setMinimumSectionSize(28)
		self.s4Settings_tableWidget.verticalHeader().setSortIndicatorShown(False)
		self.s4TorqueDragSideforce_tableWidget = QtWidgets.QTableWidget(self.groupBox_7)
		self.s4TorqueDragSideforce_tableWidget.setGeometry(QtCore.QRect(10, 220, 561, 481))
		self.s4TorqueDragSideforce_tableWidget.setStyleSheet("")
		self.s4TorqueDragSideforce_tableWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
		self.s4TorqueDragSideforce_tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
		self.s4TorqueDragSideforce_tableWidget.setRowCount(500)
		self.s4TorqueDragSideforce_tableWidget.setColumnCount(7)
		self.s4TorqueDragSideforce_tableWidget.setObjectName("s4TorqueDragSideforce_tableWidget")
		item = QtWidgets.QTableWidgetItem()
		self.s4TorqueDragSideforce_tableWidget.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.s4TorqueDragSideforce_tableWidget.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.s4TorqueDragSideforce_tableWidget.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.s4TorqueDragSideforce_tableWidget.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.s4TorqueDragSideforce_tableWidget.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		self.s4TorqueDragSideforce_tableWidget.setHorizontalHeaderItem(5, item)
		item = QtWidgets.QTableWidgetItem()
		self.s4TorqueDragSideforce_tableWidget.setHorizontalHeaderItem(6, item)
		self.s4TorqueDragSideforce_tableWidget.horizontalHeader().setDefaultSectionSize(100)
		self.s4TorqueDragSideforce_tableWidget.verticalHeader().setDefaultSectionSize(30)
		self.s4TorqueDragSideforce_tableWidget.verticalHeader().setMinimumSectionSize(30)
		self.s4Calculate_pushButton = QtWidgets.QPushButton(self.groupBox_7)
		self.s4Calculate_pushButton.setGeometry(QtCore.QRect(440, 100, 121, 41))
		self.s4Calculate_pushButton.setObjectName("s4Calculate_pushButton")
		self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
		self.tabWidget_2.setEnabled(True)
		self.tabWidget_2.setGeometry(QtCore.QRect(620, 30, 621, 721))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.tabWidget_2.setFont(font)
		self.tabWidget_2.setObjectName("tabWidget_2")
		self.tab_12 = QtWidgets.QWidget()
		self.tab_12.setObjectName("tab_12")
		self.s4Drag_graphicsView = MatplotlibWidget(self.tab_12)
		self.s4Drag_graphicsView.setGeometry(QtCore.QRect(30, 40, 551, 600))
		self.s4Drag_graphicsView.setObjectName("s4Drag_graphicsView")
		self.tabWidget_2.addTab(self.tab_12, "")
		self.tab_13 = QtWidgets.QWidget()
		self.tab_13.setObjectName("tab_13")
		self.s4Torque_graphicsView = MatplotlibWidget(self.tab_13)
		self.s4Torque_graphicsView.setGeometry(QtCore.QRect(30, 40, 551, 600))
		self.s4Torque_graphicsView.setObjectName("s4Torque_graphicsView")
		self.tabWidget_2.addTab(self.tab_13, "")
		self.tab_14 = QtWidgets.QWidget()
		self.tab_14.setObjectName("tab_14")
		self.s4Sideforce_graphicsView = MatplotlibWidget(self.tab_14)
		self.s4Sideforce_graphicsView.setGeometry(QtCore.QRect(30, 40, 551, 600))
		self.s4Sideforce_graphicsView.setObjectName("s4Sideforce_graphicsView")
		self.tabWidget_2.addTab(self.tab_14, "")
		self.tab_15 = QtWidgets.QWidget()
		self.tab_15.setObjectName("tab_15")
		self.s4HookLoad_graphicsView = MatplotlibWidget(self.tab_15)
		self.s4HookLoad_graphicsView.setGeometry(QtCore.QRect(30, 40, 551, 600))
		self.s4HookLoad_graphicsView.setObjectName("s4HookLoad_graphicsView")
		self.tabWidget_2.addTab(self.tab_15, "")
		self.Menu.addTab(self.tab_2, "")
		self.msg_label = QtWidgets.QLabel(self.centralwidget)
		self.msg_label.setGeometry(QtCore.QRect(50, 800, 1251, 41))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(True)
		font.setWeight(75)
		self.msg_label.setFont(font)
		self.msg_label.setText("")
		self.msg_label.setObjectName("msg_label")
		InputWindow.setCentralWidget(self.centralwidget)
		self.iw_toolBar = QtWidgets.QToolBar(InputWindow)
		self.iw_toolBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
		self.iw_toolBar.setMovable(True)
		self.iw_toolBar.setIconSize(QtCore.QSize(30, 30))
		self.iw_toolBar.setFloatable(True)
		self.iw_toolBar.setObjectName("iw_toolBar")
		InputWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.iw_toolBar)
		self.New_action = QtWidgets.QAction(InputWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("iconos/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.New_action.setIcon(icon)
		self.New_action.setObjectName("New_action")
		self.Open_action = QtWidgets.QAction(InputWindow)
		self.Open_action.setCheckable(False)
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap("iconos/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.Open_action.setIcon(icon1)
		self.Open_action.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
		self.Open_action.setObjectName("Open_action")
		self.Save_action = QtWidgets.QAction(InputWindow)
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap("iconos/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.Save_action.setIcon(icon2)
		self.Save_action.setObjectName("Save_action")
		self.actionSave_As = QtWidgets.QAction(InputWindow)
		self.actionSave_As.setShortcutContext(QtCore.Qt.WindowShortcut)
		self.actionSave_As.setObjectName("actionSave_As")
		self.actionPrint = QtWidgets.QAction(InputWindow)
		self.actionPrint.setObjectName("actionPrint")
		self.actionPrint_2 = QtWidgets.QAction(InputWindow)
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap("../../../../../.designer/backup/iconos/document-print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionPrint_2.setIcon(icon3)
		self.actionPrint_2.setObjectName("actionPrint_2")
		self.actionExit = QtWidgets.QAction(InputWindow)
		self.actionExit.setObjectName("actionExit")
		self.actionCopy_Selection = QtWidgets.QAction(InputWindow)
		self.actionCopy_Selection.setObjectName("actionCopy_Selection")
		self.actionPaste = QtWidgets.QAction(InputWindow)
		self.actionPaste.setObjectName("actionPaste")
		self.OneSpanAnalysis_action = QtWidgets.QAction(InputWindow)
		icon4 = QtGui.QIcon()
		icon4.addPixmap(QtGui.QPixmap("iconos/games-solve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.OneSpanAnalysis_action.setIcon(icon4)
		self.OneSpanAnalysis_action.setObjectName("OneSpanAnalysis_action")
		self.actionUnit_Setting = QtWidgets.QAction(InputWindow)
		self.actionUnit_Setting.setObjectName("actionUnit_Setting")
		self.SchematicDiagram_action = QtWidgets.QAction(InputWindow)
		icon5 = QtGui.QIcon()
		icon5.addPixmap(QtGui.QPixmap("iconos/measure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.SchematicDiagram_action.setIcon(icon5)
		self.SchematicDiagram_action.setObjectName("SchematicDiagram_action")
		self.actionCalculator = QtWidgets.QAction(InputWindow)
		icon6 = QtGui.QIcon()
		icon6.addPixmap(QtGui.QPixmap("../../../../../.designer/backup/iconos/accessories-calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionCalculator.setIcon(icon6)
		self.actionCalculator.setObjectName("actionCalculator")
		self.actionNotepad = QtWidgets.QAction(InputWindow)
		icon7 = QtGui.QIcon()
		icon7.addPixmap(QtGui.QPixmap("../../../../../.designer/backup/iconos/story-editor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionNotepad.setIcon(icon7)
		self.actionNotepad.setObjectName("actionNotepad")
		self.About_action = QtWidgets.QAction(InputWindow)
		icon8 = QtGui.QIcon()
		icon8.addPixmap(QtGui.QPixmap("iconos/system-help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.About_action.setIcon(icon8)
		self.About_action.setObjectName("About_action")
		self.actionAbbreviation = QtWidgets.QAction(InputWindow)
		self.actionAbbreviation.setObjectName("actionAbbreviation")
		self.actionDisclaimer = QtWidgets.QAction(InputWindow)
		self.actionDisclaimer.setObjectName("actionDisclaimer")
		self.MakeReport_action = QtWidgets.QAction(InputWindow)
		icon9 = QtGui.QIcon()
		icon9.addPixmap(QtGui.QPixmap("iconos/arrow-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.MakeReport_action.setIcon(icon9)
		self.MakeReport_action.setObjectName("MakeReport_action")
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.New_action)
		self.iw_toolBar.addAction(self.Open_action)
		self.iw_toolBar.addAction(self.Save_action)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.MakeReport_action)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.OneSpanAnalysis_action)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.SchematicDiagram_action)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.About_action)

		self.retranslateUi(InputWindow)
		self.Menu.setCurrentIndex(0)
		self.tabWidget.setCurrentIndex(0)
		self.s3InnerStageToolkit_tabWidget.setCurrentIndex(0)
		self.ABC_tabWidget.setCurrentIndex(0)
		self.tabWidget_2.setCurrentIndex(0)
		self.actionExit.triggered.connect(InputWindow.close)
		QtCore.QMetaObject.connectSlotsByName(InputWindow)

	def retranslateUi(self, InputWindow):
		_translate = QtCore.QCoreApplication.translate
		InputWindow.setWindowTitle(_translate("InputWindow", "Central Software - Main Window"))
		self.Menu.setToolTip(_translate("InputWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
		self.groupBox.setTitle(_translate("InputWindow", "General Information"))
		item = self.s1Info_tableWidget.verticalHeaderItem(0)
		item.setText(_translate("InputWindow", "Well name"))
		item = self.s1Info_tableWidget.verticalHeaderItem(1)
		item.setText(_translate("InputWindow", "Location"))
		item = self.s1Info_tableWidget.verticalHeaderItem(2)
		item.setText(_translate("InputWindow", "Operator"))
		item = self.s1Info_tableWidget.verticalHeaderItem(3)
		item.setText(_translate("InputWindow", "Contractor"))
		item = self.s1Info_tableWidget.verticalHeaderItem(4)
		item.setText(_translate("InputWindow", "Date"))
		item = self.s1Info_tableWidget.verticalHeaderItem(5)
		item.setText(_translate("InputWindow", "Directory"))
		self.groupBox_2.setTitle(_translate("InputWindow", "Units"))
		self.s1USOF_radioButton.setText(_translate("InputWindow", "US oil field"))
		self.s1Metric_radioButton.setText(_translate("InputWindow", "Metric"))
		self.s1Customized_radioButton.setText(_translate("InputWindow", "Customized"))
		self.s1UnitSetting_pushButton.setText(_translate("InputWindow", "Unit Setting..."))
		self.s1SelectDirectory_pushButton.setText(_translate("InputWindow", "Select directory ..."))
		self.Menu.setTabText(self.Menu.indexOf(self.tab), _translate("InputWindow", "General"))
		self.s2Import_pushButton.setText(_translate("InputWindow", "Import Survey"))
		self.s2Remove_pushButton.setText(_translate("InputWindow", "Clear All"))
		self.s2Calculate_pushButton.setText(_translate("InputWindow", "CALCULATE"))
		self.s2SurveyTortuosity_groupBox.setTitle(_translate("InputWindow", "Survey tortuosity"))
		item = self.s2SurveyTortuosity_tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "From"))
		item = self.s2SurveyTortuosity_tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("InputWindow", "To"))
		item = self.s2SurveyTortuosity_tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("InputWindow", "Amplitude"))
		item = self.s2SurveyTortuosity_tableWidget.horizontalHeaderItem(3)
		item.setText(_translate("InputWindow", "Period"))
		self.s2TortuosityInterval_tableWidget.setSortingEnabled(False)
		item = self.s2TortuosityInterval_tableWidget.verticalHeaderItem(0)
		item.setText(_translate("InputWindow", "Interval [unit]"))
		self.s2DataSurvey_tableWidget.setSortingEnabled(False)
		item = self.s2DataSurvey_tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "MD"))
		item = self.s2DataSurvey_tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("InputWindow", "Inc"))
		item = self.s2DataSurvey_tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("InputWindow", "Azi"))
		item = self.s2DataSurvey_tableWidget.horizontalHeaderItem(3)
		item.setText(_translate("InputWindow", "TVD"))
		item = self.s2DataSurvey_tableWidget.horizontalHeaderItem(4)
		item.setText(_translate("InputWindow", "Vsec"))
		item = self.s2DataSurvey_tableWidget.horizontalHeaderItem(5)
		item.setText(_translate("InputWindow", "N+/S-"))
		item = self.s2DataSurvey_tableWidget.horizontalHeaderItem(6)
		item.setText(_translate("InputWindow", "E+/W-"))
		item = self.s2DataSurvey_tableWidget.horizontalHeaderItem(7)
		item.setText(_translate("InputWindow", "Dogleg"))
		__sortingEnabled = self.s2DataSurvey_tableWidget.isSortingEnabled()
		self.s2DataSurvey_tableWidget.setSortingEnabled(False)
		self.s2DataSurvey_tableWidget.setSortingEnabled(__sortingEnabled)
		self.s2SurveyTortuosity_checkBox.setText(_translate("InputWindow", "Include Survey Tortuosity"))
		self.s2KOP_tableWidget.setSortingEnabled(False)
		item = self.s2KOP_tableWidget.verticalHeaderItem(0)
		item.setText(_translate("InputWindow", "KOP [unit]"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("InputWindow", "Data"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("InputWindow", "Section View"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("InputWindow", "3D View"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("InputWindow", "Plan View"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("InputWindow", "Dogleg"))
		self.Menu.setTabText(self.Menu.indexOf(self.tab_3), _translate("InputWindow", "Survey"))
		self.groupBox_4.setTitle(_translate("InputWindow", "Wellbore Outer Stages (from top down)"))
		item = self.s3WellboreOuterStages_tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "Description"))
		item = self.s3WellboreOuterStages_tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("InputWindow", "ID"))
		item = self.s3WellboreOuterStages_tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("InputWindow", "Drift"))
		item = self.s3WellboreOuterStages_tableWidget.horizontalHeaderItem(3)
		item.setText(_translate("InputWindow", "top MD"))
		item = self.s3WellboreOuterStages_tableWidget.horizontalHeaderItem(4)
		item.setText(_translate("InputWindow", "bottom MD"))
		item = self.s3WellboreOuterStages_tableWidget.horizontalHeaderItem(5)
		item.setText(_translate("InputWindow", "Friction factor"))
		self.groupBox_5.setTitle(_translate("InputWindow", "Wellbore Inner Stages (from top down) "))
		item = self.s3WellboreInnerStages_tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "Pipes (from top down)"))
		item = self.s3WellboreInnerStages_tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("InputWindow", "Length"))
		item = self.s3WellboreInnerStages_tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("InputWindow", "MD"))
		self.s3UpdateInnerStages_pushButton.setText(_translate("InputWindow", "UPDATE INNER STAGES"))
		self.s3ODID_pushButton.setText(_translate("InputWindow", "OD, ID -> Wt"))
		self.s3ODWt_pushButton.setText(_translate("InputWindow", "OD, Wt -> ID"))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(0)
		item.setText(_translate("InputWindow", "Pipe"))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(1)
		item.setText(_translate("InputWindow", "Adjusted Wt                                                 "))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(2)
		item.setText(_translate("InputWindow", "OD"))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(3)
		item.setText(_translate("InputWindow", "ID"))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(4)
		item.setText(_translate("InputWindow", "Tensile limit"))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(5)
		item.setText(_translate("InputWindow", "Torsional limit"))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(6)
		item.setText(_translate("InputWindow", "Density"))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(7)
		item.setText(_translate("InputWindow", "E"))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(8)
		item.setText(_translate("InputWindow", "FF reduction"))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(9)
		item.setText(_translate("InputWindow", "Inner mud density"))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(10)
		item.setText(_translate("InputWindow", "Outer mud density"))
		self.s3StageNumber_label1.setText(_translate("InputWindow", "STAGE 1"))
		self.s3InnerStageToolkit_tabWidget.setTabText(self.s3InnerStageToolkit_tabWidget.indexOf(self.tab_10), _translate("InputWindow", "Pipe"))
		self.s3BowSpringCentralizer_radioButton_A.setText(_translate("InputWindow", "Bow Spring"))
		self.s3ResinCentralizer_radioButton_A.setText(_translate("InputWindow", "Resin"))
		self.s3Location_label_A.setText(_translate("InputWindow", "Location:"))
		item = self.s3CentralizerRunningForce_tableWidget_A.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "Hole ID"))
		item = self.s3CentralizerRunningForce_tableWidget_A.horizontalHeaderItem(1)
		item.setText(_translate("InputWindow", "Running F."))
		self.s3CentralizerDB_pushButton_A.setText(_translate("InputWindow", "Centralizer DB..."))
		item = self.s3CentralizerLocation_tableWidget_A.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "MD"))
		self.label.setText(_translate("InputWindow", "PATTERN :  1  /"))
		self.label_2.setText(_translate("InputWindow", "OFFSET :"))
		self.ABC_tabWidget.setTabText(self.ABC_tabWidget.indexOf(self.tab_A), _translate("InputWindow", "A"))
		item = self.s3CentralizerLocation_tableWidget_B.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "MD"))
		item = self.s3CentralizerRunningForce_tableWidget_B.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "Hole ID"))
		item = self.s3CentralizerRunningForce_tableWidget_B.horizontalHeaderItem(1)
		item.setText(_translate("InputWindow", "Running F."))
		self.s3ResinCentralizer_radioButton_B.setText(_translate("InputWindow", "Resin"))
		self.s3CentralizerDB_pushButton_B.setText(_translate("InputWindow", "Centralizer DB..."))
		self.s3BowSpringCentralizer_radioButton_B.setText(_translate("InputWindow", "Bow Spring"))
		self.s3Location_label_B.setText(_translate("InputWindow", "Location:"))
		self.s3NoneCentralizer_radioButton_B.setText(_translate("InputWindow", "None"))
		self.ABC_tabWidget.setTabText(self.ABC_tabWidget.indexOf(self.tab_B), _translate("InputWindow", "B"))
		self.s3BowSpringCentralizer_radioButton_C.setText(_translate("InputWindow", "Bow Spring"))
		self.s3ResinCentralizer_radioButton_C.setText(_translate("InputWindow", "Resin"))
		self.s3Location_label_C.setText(_translate("InputWindow", "Location:"))
		item = self.s3CentralizerRunningForce_tableWidget_C.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "Hole ID"))
		item = self.s3CentralizerRunningForce_tableWidget_C.horizontalHeaderItem(1)
		item.setText(_translate("InputWindow", "Running F."))
		self.s3CentralizerDB_pushButton_C.setText(_translate("InputWindow", "Centralizer DB..."))
		item = self.s3CentralizerLocation_tableWidget_C.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "MD"))
		self.s3NoneCentralizer_radioButton_C.setText(_translate("InputWindow", "None"))
		self.ABC_tabWidget.setTabText(self.ABC_tabWidget.indexOf(self.tab_C), _translate("InputWindow", "C"))
		self.s3EnableCentralization_checkBox.setText(_translate("InputWindow", "enable centralization"))
		self.s3StageNumber_label2.setText(_translate("InputWindow", "STAGE 1"))
		self.s3StageEnsemble_label.setText(_translate("InputWindow", "=\n"
"|\n"
"|\n"
"|\n"
"="))
		self.s3InnerStageToolkit_tabWidget.setTabText(self.s3InnerStageToolkit_tabWidget.indexOf(self.tab_11), _translate("InputWindow", "Centralization"))
		self.s3ManageLocations_pushButton.setText(_translate("InputWindow", "MANAGE LOCATIONS..."))
		self.s3Plot3DSO_pushButton.setText(_translate("InputWindow", "3D SO Visualization"))
		self.Menu.setTabText(self.Menu.indexOf(self.tab_4), _translate("InputWindow", "Wellbore"))
		self.groupBox_7.setTitle(_translate("InputWindow", "Settings and results"))
		self.s4Settings_tableWidget.setSortingEnabled(False)
		item = self.s4Settings_tableWidget.verticalHeaderItem(0)
		item.setText(_translate("InputWindow", "Traveling Assembly Weight (TAW)"))
		item = self.s4Settings_tableWidget.verticalHeaderItem(1)
		item.setText(_translate("InputWindow", "Pipe end drag or WOB"))
		item = self.s4Settings_tableWidget.verticalHeaderItem(2)
		item.setText(_translate("InputWindow", "Pipe end torque or TOB"))
		item = self.s4Settings_tableWidget.verticalHeaderItem(3)
		item.setText(_translate("InputWindow", "Tripping speed"))
		item = self.s4Settings_tableWidget.verticalHeaderItem(4)
		item.setText(_translate("InputWindow", "Rotational speed"))
		item = self.s4TorqueDragSideforce_tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "MD"))
		item = self.s4TorqueDragSideforce_tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("InputWindow", "AxialF"))
		item = self.s4TorqueDragSideforce_tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("InputWindow", "SideF"))
		item = self.s4TorqueDragSideforce_tableWidget.horizontalHeaderItem(3)
		item.setText(_translate("InputWindow", "Torque"))
		item = self.s4TorqueDragSideforce_tableWidget.horizontalHeaderItem(4)
		item.setText(_translate("InputWindow", "Drag s"))
		item = self.s4TorqueDragSideforce_tableWidget.horizontalHeaderItem(5)
		item.setText(_translate("InputWindow", "Drag d"))
		item = self.s4TorqueDragSideforce_tableWidget.horizontalHeaderItem(6)
		item.setText(_translate("InputWindow", "Drag u"))
		self.s4Calculate_pushButton.setText(_translate("InputWindow", "Calculate"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_12), _translate("InputWindow", "Drag"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_13), _translate("InputWindow", "Torque"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_14), _translate("InputWindow", "Side Force"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_15), _translate("InputWindow", "Hook Load"))
		self.Menu.setTabText(self.Menu.indexOf(self.tab_2), _translate("InputWindow", "Torque + Drag"))
		self.iw_toolBar.setWindowTitle(_translate("InputWindow", "toolBar"))
		self.New_action.setText(_translate("InputWindow", "New"))
		self.New_action.setShortcut(_translate("InputWindow", "Ctrl+N"))
		self.Open_action.setText(_translate("InputWindow", "Open..."))
		self.Open_action.setShortcut(_translate("InputWindow", "Ctrl+O"))
		self.Save_action.setText(_translate("InputWindow", "Save"))
		self.Save_action.setShortcut(_translate("InputWindow", "Ctrl+S"))
		self.actionSave_As.setText(_translate("InputWindow", "Save As..."))
		self.actionPrint.setText(_translate("InputWindow", "Print Preview..."))
		self.actionPrint_2.setText(_translate("InputWindow", "Print.."))
		self.actionPrint_2.setShortcut(_translate("InputWindow", "Ctrl+P"))
		self.actionExit.setText(_translate("InputWindow", "Exit"))
		self.actionCopy_Selection.setText(_translate("InputWindow", "Copy Selection"))
		self.actionPaste.setText(_translate("InputWindow", "Paste"))
		self.OneSpanAnalysis_action.setText(_translate("InputWindow", "One Span Analysis..."))
		self.actionUnit_Setting.setText(_translate("InputWindow", "Unit Setting..."))
		self.SchematicDiagram_action.setText(_translate("InputWindow", "Unit Conversion..."))
		self.actionCalculator.setText(_translate("InputWindow", "Calculator..."))
		self.actionNotepad.setText(_translate("InputWindow", "Notepad..."))
		self.About_action.setText(_translate("InputWindow", "About..."))
		self.actionAbbreviation.setText(_translate("InputWindow", "Abbreviation..."))
		self.actionDisclaimer.setText(_translate("InputWindow", "Disclaimer..."))
		self.MakeReport_action.setText(_translate("InputWindow", "Star Calculation"))
		self.MakeReport_action.setShortcut(_translate("InputWindow", "F5"))

from matplotlibwidget import Matplotlib3DWidget, MatplotlibWidget
