# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InputWindow_Vst.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
	_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
	def _fromUtf8(s):
		return s

try:
	_encoding = QtGui.QApplication.UnicodeUTF8
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig)

class Ui_InputWindow(object):
	def setupUi(self, InputWindow):
		InputWindow.setObjectName(_fromUtf8("InputWindow"))
		InputWindow.resize(1321, 913)
		self.centralwidget = QtGui.QWidget(InputWindow)
		self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
		self.Menu = QtGui.QTabWidget(self.centralwidget)
		self.Menu.setGeometry(QtCore.QRect(15, 10, 1291, 785))
		font = QtGui.QFont()
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		font.setStyleStrategy(QtGui.QFont.PreferDefault)
		self.Menu.setFont(font)
		self.Menu.setTabPosition(QtGui.QTabWidget.West)
		self.Menu.setTabShape(QtGui.QTabWidget.Rounded)
		self.Menu.setIconSize(QtCore.QSize(20, 20))
		self.Menu.setElideMode(QtCore.Qt.ElideNone)
		self.Menu.setObjectName(_fromUtf8("Menu"))
		self.tab = QtGui.QWidget()
		self.tab.setObjectName(_fromUtf8("tab"))
		self.groupBox = QtGui.QGroupBox(self.tab)
		self.groupBox.setGeometry(QtCore.QRect(30, 50, 1051, 541))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.groupBox.setFont(font)
		self.groupBox.setObjectName(_fromUtf8("groupBox"))
		self.s1Info_tableWidget = QtGui.QTableWidget(self.groupBox)
		self.s1Info_tableWidget.setGeometry(QtCore.QRect(40, 50, 691, 371))
		self.s1Info_tableWidget.setColumnCount(1)
		self.s1Info_tableWidget.setObjectName(_fromUtf8("s1Info_tableWidget"))
		self.s1Info_tableWidget.setRowCount(6)
		item = QtGui.QTableWidgetItem()
		self.s1Info_tableWidget.setVerticalHeaderItem(0, item)
		item = QtGui.QTableWidgetItem()
		self.s1Info_tableWidget.setVerticalHeaderItem(1, item)
		item = QtGui.QTableWidgetItem()
		self.s1Info_tableWidget.setVerticalHeaderItem(2, item)
		item = QtGui.QTableWidgetItem()
		self.s1Info_tableWidget.setVerticalHeaderItem(3, item)
		item = QtGui.QTableWidgetItem()
		self.s1Info_tableWidget.setVerticalHeaderItem(4, item)
		item = QtGui.QTableWidgetItem()
		self.s1Info_tableWidget.setVerticalHeaderItem(5, item)
		self.s1Info_tableWidget.horizontalHeader().setVisible(False)
		self.s1Info_tableWidget.horizontalHeader().setDefaultSectionSize(600)
		self.s1Info_tableWidget.verticalHeader().setDefaultSectionSize(60)
		self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
		self.groupBox_2.setGeometry(QtCore.QRect(750, 40, 231, 241))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.groupBox_2.setFont(font)
		self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
		self.s1USOF_radioButton = QtGui.QRadioButton(self.groupBox_2)
		self.s1USOF_radioButton.setGeometry(QtCore.QRect(40, 40, 141, 25))
		self.s1USOF_radioButton.setObjectName(_fromUtf8("s1USOF_radioButton"))
		self.s1Metric_radioButton = QtGui.QRadioButton(self.groupBox_2)
		self.s1Metric_radioButton.setGeometry(QtCore.QRect(40, 80, 141, 25))
		self.s1Metric_radioButton.setObjectName(_fromUtf8("s1Metric_radioButton"))
		self.s1Customized_radioButton = QtGui.QRadioButton(self.groupBox_2)
		self.s1Customized_radioButton.setGeometry(QtCore.QRect(40, 120, 141, 28))
		self.s1Customized_radioButton.setChecked(True)
		self.s1Customized_radioButton.setObjectName(_fromUtf8("s1Customized_radioButton"))
		self.s1UnitSetting_pushButton = QtGui.QPushButton(self.groupBox_2)
		self.s1UnitSetting_pushButton.setGeometry(QtCore.QRect(30, 170, 171, 41))
		self.s1UnitSetting_pushButton.setObjectName(_fromUtf8("s1UnitSetting_pushButton"))
		self.s1SelectDirectory_pushButton = QtGui.QPushButton(self.groupBox)
		self.s1SelectDirectory_pushButton.setGeometry(QtCore.QRect(780, 360, 171, 41))
		self.s1SelectDirectory_pushButton.setObjectName(_fromUtf8("s1SelectDirectory_pushButton"))
		self.Menu.addTab(self.tab, _fromUtf8(""))
		self.tab_3 = QtGui.QWidget()
		self.tab_3.setObjectName(_fromUtf8("tab_3"))
		self.tabWidget = QtGui.QTabWidget(self.tab_3)
		self.tabWidget.setEnabled(True)
		self.tabWidget.setGeometry(QtCore.QRect(10, 0, 1471, 911))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.tabWidget.setFont(font)
		self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
		self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
		self.tabWidget.setUsesScrollButtons(True)
		self.tabWidget.setDocumentMode(False)
		self.tabWidget.setTabsClosable(False)
		self.tabWidget.setMovable(False)
		self.tabWidget.setProperty("tabBarAutoHide", False)
		self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
		self.tab_5 = QtGui.QWidget()
		self.tab_5.setObjectName(_fromUtf8("tab_5"))
		self.verticalLayoutWidget = QtGui.QWidget(self.tab_5)
		self.verticalLayoutWidget.setGeometry(QtCore.QRect(930, 10, 191, 151))
		self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
		self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
		self.verticalLayout.setSpacing(0)
		self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
		self.s2Import_pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
		self.s2Import_pushButton.setObjectName(_fromUtf8("s2Import_pushButton"))
		self.verticalLayout.addWidget(self.s2Import_pushButton)
		self.s2Remove_pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
		self.s2Remove_pushButton.setObjectName(_fromUtf8("s2Remove_pushButton"))
		self.verticalLayout.addWidget(self.s2Remove_pushButton)
		self.s2Calculate_pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.s2Calculate_pushButton.setFont(font)
		self.s2Calculate_pushButton.setObjectName(_fromUtf8("s2Calculate_pushButton"))
		self.verticalLayout.addWidget(self.s2Calculate_pushButton)
		self.s2SurveyTortuosity_groupBox = QtGui.QGroupBox(self.tab_5)
		self.s2SurveyTortuosity_groupBox.setEnabled(False)
		self.s2SurveyTortuosity_groupBox.setGeometry(QtCore.QRect(20, 480, 891, 241))
		self.s2SurveyTortuosity_groupBox.setObjectName(_fromUtf8("s2SurveyTortuosity_groupBox"))
		self.s2SurveyTortuosity_tableWidget = QtGui.QTableWidget(self.s2SurveyTortuosity_groupBox)
		self.s2SurveyTortuosity_tableWidget.setGeometry(QtCore.QRect(10, 50, 541, 171))
		self.s2SurveyTortuosity_tableWidget.setStyleSheet(_fromUtf8(""))
		self.s2SurveyTortuosity_tableWidget.setFrameShape(QtGui.QFrame.WinPanel)
		self.s2SurveyTortuosity_tableWidget.setAlternatingRowColors(True)
		self.s2SurveyTortuosity_tableWidget.setRowCount(10)
		self.s2SurveyTortuosity_tableWidget.setObjectName(_fromUtf8("s2SurveyTortuosity_tableWidget"))
		self.s2SurveyTortuosity_tableWidget.setColumnCount(4)
		item = QtGui.QTableWidgetItem()
		self.s2SurveyTortuosity_tableWidget.setHorizontalHeaderItem(0, item)
		item = QtGui.QTableWidgetItem()
		self.s2SurveyTortuosity_tableWidget.setHorizontalHeaderItem(1, item)
		item = QtGui.QTableWidgetItem()
		self.s2SurveyTortuosity_tableWidget.setHorizontalHeaderItem(2, item)
		item = QtGui.QTableWidgetItem()
		self.s2SurveyTortuosity_tableWidget.setHorizontalHeaderItem(3, item)
		self.s2SurveyTortuosity_tableWidget.horizontalHeader().setDefaultSectionSize(121)
		self.s2SurveyTortuosity_tableWidget.verticalHeader().setDefaultSectionSize(25)
		self.s2SurveyTortuosity_tableWidget.verticalHeader().setMinimumSectionSize(25)
		self.s2TortuosityInterval_tableWidget = QtGui.QTableWidget(self.s2SurveyTortuosity_groupBox)
		self.s2TortuosityInterval_tableWidget.setGeometry(QtCore.QRect(570, 50, 261, 32))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.s2TortuosityInterval_tableWidget.setFont(font)
		self.s2TortuosityInterval_tableWidget.setAutoFillBackground(False)
		self.s2TortuosityInterval_tableWidget.setFrameShadow(QtGui.QFrame.Sunken)
		self.s2TortuosityInterval_tableWidget.setColumnCount(1)
		self.s2TortuosityInterval_tableWidget.setObjectName(_fromUtf8("s2TortuosityInterval_tableWidget"))
		self.s2TortuosityInterval_tableWidget.setRowCount(1)
		item = QtGui.QTableWidgetItem()
		self.s2TortuosityInterval_tableWidget.setVerticalHeaderItem(0, item)
		self.s2TortuosityInterval_tableWidget.horizontalHeader().setVisible(False)
		self.s2TortuosityInterval_tableWidget.horizontalHeader().setCascadingSectionResizes(False)
		self.s2TortuosityInterval_tableWidget.horizontalHeader().setDefaultSectionSize(140)
		self.s2TortuosityInterval_tableWidget.horizontalHeader().setHighlightSections(True)
		self.s2TortuosityInterval_tableWidget.horizontalHeader().setSortIndicatorShown(False)
		self.s2TortuosityInterval_tableWidget.horizontalHeader().setStretchLastSection(False)
		self.s2TortuosityInterval_tableWidget.verticalHeader().setDefaultSectionSize(30)
		self.s2TortuosityInterval_tableWidget.verticalHeader().setMinimumSectionSize(28)
		self.s2TortuosityInterval_tableWidget.verticalHeader().setSortIndicatorShown(False)
		self.s2DataSurvey_tableWidget = QtGui.QTableWidget(self.tab_5)
		self.s2DataSurvey_tableWidget.setGeometry(QtCore.QRect(20, 10, 891, 451))
		self.s2DataSurvey_tableWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
		self.s2DataSurvey_tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.s2DataSurvey_tableWidget.setStyleSheet(_fromUtf8(""))
		self.s2DataSurvey_tableWidget.setFrameShape(QtGui.QFrame.WinPanel)
		self.s2DataSurvey_tableWidget.setFrameShadow(QtGui.QFrame.Sunken)
		self.s2DataSurvey_tableWidget.setMidLineWidth(1)
		self.s2DataSurvey_tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
		self.s2DataSurvey_tableWidget.setAutoScrollMargin(16)
		self.s2DataSurvey_tableWidget.setAlternatingRowColors(True)
		self.s2DataSurvey_tableWidget.setGridStyle(QtCore.Qt.SolidLine)
		self.s2DataSurvey_tableWidget.setWordWrap(True)
		self.s2DataSurvey_tableWidget.setCornerButtonEnabled(True)
		self.s2DataSurvey_tableWidget.setRowCount(1000)
		self.s2DataSurvey_tableWidget.setColumnCount(8)
		self.s2DataSurvey_tableWidget.setObjectName(_fromUtf8("s2DataSurvey_tableWidget"))
		item = QtGui.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setHorizontalHeaderItem(0, item)
		item = QtGui.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setHorizontalHeaderItem(1, item)
		item = QtGui.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setHorizontalHeaderItem(2, item)
		item = QtGui.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setHorizontalHeaderItem(3, item)
		item = QtGui.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setHorizontalHeaderItem(4, item)
		item = QtGui.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setHorizontalHeaderItem(5, item)
		item = QtGui.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setHorizontalHeaderItem(6, item)
		item = QtGui.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setHorizontalHeaderItem(7, item)
		item = QtGui.QTableWidgetItem()
		self.s2DataSurvey_tableWidget.setItem(0, 0, item)
		item = QtGui.QTableWidgetItem()
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.NoBrush)
		item.setForeground(brush)
		self.s2DataSurvey_tableWidget.setItem(0, 3, item)
		self.s2DataSurvey_tableWidget.horizontalHeader().setCascadingSectionResizes(False)
		self.s2DataSurvey_tableWidget.horizontalHeader().setDefaultSectionSize(115)
		self.s2DataSurvey_tableWidget.horizontalHeader().setHighlightSections(True)
		self.s2DataSurvey_tableWidget.horizontalHeader().setMinimumSectionSize(100)
		self.s2DataSurvey_tableWidget.horizontalHeader().setSortIndicatorShown(False)
		self.s2DataSurvey_tableWidget.horizontalHeader().setStretchLastSection(False)
		self.s2DataSurvey_tableWidget.verticalHeader().setCascadingSectionResizes(False)
		self.s2DataSurvey_tableWidget.verticalHeader().setDefaultSectionSize(25)
		self.s2DataSurvey_tableWidget.verticalHeader().setMinimumSectionSize(25)
		self.s2DataSurvey_tableWidget.verticalHeader().setSortIndicatorShown(False)
		self.s2DataSurvey_tableWidget.verticalHeader().setStretchLastSection(False)
		self.s2SurveyTortuosity_checkBox = QtGui.QCheckBox(self.tab_5)
		self.s2SurveyTortuosity_checkBox.setGeometry(QtCore.QRect(930, 240, 221, 31))
		self.s2SurveyTortuosity_checkBox.setChecked(False)
		self.s2SurveyTortuosity_checkBox.setObjectName(_fromUtf8("s2SurveyTortuosity_checkBox"))
		self.s2KOP_tableWidget = QtGui.QTableWidget(self.tab_5)
		self.s2KOP_tableWidget.setGeometry(QtCore.QRect(930, 180, 231, 32))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.s2KOP_tableWidget.setFont(font)
		self.s2KOP_tableWidget.setAutoFillBackground(False)
		self.s2KOP_tableWidget.setFrameShadow(QtGui.QFrame.Sunken)
		self.s2KOP_tableWidget.setColumnCount(1)
		self.s2KOP_tableWidget.setObjectName(_fromUtf8("s2KOP_tableWidget"))
		self.s2KOP_tableWidget.setRowCount(1)
		item = QtGui.QTableWidgetItem()
		self.s2KOP_tableWidget.setVerticalHeaderItem(0, item)
		self.s2KOP_tableWidget.horizontalHeader().setVisible(False)
		self.s2KOP_tableWidget.horizontalHeader().setCascadingSectionResizes(False)
		self.s2KOP_tableWidget.horizontalHeader().setDefaultSectionSize(140)
		self.s2KOP_tableWidget.horizontalHeader().setHighlightSections(True)
		self.s2KOP_tableWidget.horizontalHeader().setSortIndicatorShown(False)
		self.s2KOP_tableWidget.horizontalHeader().setStretchLastSection(False)
		self.s2KOP_tableWidget.verticalHeader().setDefaultSectionSize(30)
		self.s2KOP_tableWidget.verticalHeader().setMinimumSectionSize(28)
		self.s2KOP_tableWidget.verticalHeader().setSortIndicatorShown(False)
		self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
		self.tab_6 = QtGui.QWidget()
		self.tab_6.setObjectName(_fromUtf8("tab_6"))
		self.s2SectionView_graphicsView = MatplotlibWidget(self.tab_6)
		self.s2SectionView_graphicsView.setGeometry(QtCore.QRect(60, 60, 600, 500))
		self.s2SectionView_graphicsView.setObjectName(_fromUtf8("s2SectionView_graphicsView"))
		self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
		self.tab_7 = QtGui.QWidget()
		self.tab_7.setObjectName(_fromUtf8("tab_7"))
		self.s2PlanView_graphicsView = MatplotlibWidget(self.tab_7)
		self.s2PlanView_graphicsView.setGeometry(QtCore.QRect(60, 60, 600, 500))
		self.s2PlanView_graphicsView.setObjectName(_fromUtf8("s2PlanView_graphicsView"))
		self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
		self.tab_8 = QtGui.QWidget()
		self.tab_8.setObjectName(_fromUtf8("tab_8"))
		self.s2TriDView_graphicsView = Matplotlib3DWidget(self.tab_8)
		self.s2TriDView_graphicsView.setGeometry(QtCore.QRect(60, 20, 791, 711))
		self.s2TriDView_graphicsView.setObjectName(_fromUtf8("s2TriDView_graphicsView"))
		self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
		self.tab_9 = QtGui.QWidget()
		self.tab_9.setObjectName(_fromUtf8("tab_9"))
		self.s2Dogleg_graphicsView = MatplotlibWidget(self.tab_9)
		self.s2Dogleg_graphicsView.setGeometry(QtCore.QRect(60, 60, 600, 500))
		self.s2Dogleg_graphicsView.setObjectName(_fromUtf8("s2Dogleg_graphicsView"))
		self.tabWidget.addTab(self.tab_9, _fromUtf8(""))
		self.Menu.addTab(self.tab_3, _fromUtf8(""))
		self.tab_4 = QtGui.QWidget()
		self.tab_4.setObjectName(_fromUtf8("tab_4"))
		self.groupBox_4 = QtGui.QGroupBox(self.tab_4)
		self.groupBox_4.setEnabled(True)
		self.groupBox_4.setGeometry(QtCore.QRect(10, 6, 1231, 194))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.groupBox_4.setFont(font)
		self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
		self.s3WellboreIntervals_tableWidget = QtGui.QTableWidget(self.groupBox_4)
		self.s3WellboreIntervals_tableWidget.setGeometry(QtCore.QRect(11, 30, 1101, 155))
		self.s3WellboreIntervals_tableWidget.setStyleSheet(_fromUtf8(""))
		self.s3WellboreIntervals_tableWidget.setFrameShape(QtGui.QFrame.WinPanel)
		self.s3WellboreIntervals_tableWidget.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
		self.s3WellboreIntervals_tableWidget.setAlternatingRowColors(True)
		self.s3WellboreIntervals_tableWidget.setRowCount(500)
		self.s3WellboreIntervals_tableWidget.setObjectName(_fromUtf8("s3WellboreIntervals_tableWidget"))
		self.s3WellboreIntervals_tableWidget.setColumnCount(6)
		item = QtGui.QTableWidgetItem()
		self.s3WellboreIntervals_tableWidget.setHorizontalHeaderItem(0, item)
		item = QtGui.QTableWidgetItem()
		self.s3WellboreIntervals_tableWidget.setHorizontalHeaderItem(1, item)
		item = QtGui.QTableWidgetItem()
		self.s3WellboreIntervals_tableWidget.setHorizontalHeaderItem(2, item)
		item = QtGui.QTableWidgetItem()
		self.s3WellboreIntervals_tableWidget.setHorizontalHeaderItem(3, item)
		item = QtGui.QTableWidgetItem()
		self.s3WellboreIntervals_tableWidget.setHorizontalHeaderItem(4, item)
		item = QtGui.QTableWidgetItem()
		self.s3WellboreIntervals_tableWidget.setHorizontalHeaderItem(5, item)
		self.s3WellboreIntervals_tableWidget.horizontalHeader().setDefaultSectionSize(150)
		self.s3WellboreIntervals_tableWidget.verticalHeader().setDefaultSectionSize(28)
		self.groupBox_5 = QtGui.QGroupBox(self.tab_4)
		self.groupBox_5.setGeometry(QtCore.QRect(10, 205, 1231, 567))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.groupBox_5.setFont(font)
		self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
		self.frame = QtGui.QFrame(self.groupBox_5)
		self.frame.setGeometry(QtCore.QRect(10, 30, 561, 521))
		self.frame.setFrameShape(QtGui.QFrame.WinPanel)
		self.frame.setFrameShadow(QtGui.QFrame.Raised)
		self.frame.setObjectName(_fromUtf8("frame"))
		self.s3PipeCentralizationStage_tableWidget = QtGui.QTableWidget(self.frame)
		self.s3PipeCentralizationStage_tableWidget.setGeometry(QtCore.QRect(9, 10, 542, 431))
		self.s3PipeCentralizationStage_tableWidget.setStyleSheet(_fromUtf8(""))
		self.s3PipeCentralizationStage_tableWidget.setFrameShape(QtGui.QFrame.WinPanel)
		self.s3PipeCentralizationStage_tableWidget.setAlternatingRowColors(True)
		self.s3PipeCentralizationStage_tableWidget.setRowCount(10)
		self.s3PipeCentralizationStage_tableWidget.setObjectName(_fromUtf8("s3PipeCentralizationStage_tableWidget"))
		self.s3PipeCentralizationStage_tableWidget.setColumnCount(3)
		item = QtGui.QTableWidgetItem()
		self.s3PipeCentralizationStage_tableWidget.setHorizontalHeaderItem(0, item)
		item = QtGui.QTableWidgetItem()
		self.s3PipeCentralizationStage_tableWidget.setHorizontalHeaderItem(1, item)
		item = QtGui.QTableWidgetItem()
		self.s3PipeCentralizationStage_tableWidget.setHorizontalHeaderItem(2, item)
		self.s3PipeCentralizationStage_tableWidget.horizontalHeader().setDefaultSectionSize(163)
		self.s3PipeCentralizationStage_tableWidget.verticalHeader().setDefaultSectionSize(56)
		self.s3PipeCentralizationStage_tableWidget.verticalHeader().setMinimumSectionSize(50)
		self.s3UpdateAxialF_pushButton = QtGui.QPushButton(self.frame)
		self.s3UpdateAxialF_pushButton.setGeometry(QtCore.QRect(10, 460, 221, 41))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.s3UpdateAxialF_pushButton.setFont(font)
		self.s3UpdateAxialF_pushButton.setObjectName(_fromUtf8("s3UpdateAxialF_pushButton"))
		self.s3InnerStageToolkit_tabWidget = QtGui.QTabWidget(self.groupBox_5)
		self.s3InnerStageToolkit_tabWidget.setEnabled(False)
		self.s3InnerStageToolkit_tabWidget.setGeometry(QtCore.QRect(590, 15, 631, 471))
		self.s3InnerStageToolkit_tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
		self.s3InnerStageToolkit_tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
		self.s3InnerStageToolkit_tabWidget.setObjectName(_fromUtf8("s3InnerStageToolkit_tabWidget"))
		self.tab_10 = QtGui.QWidget()
		self.tab_10.setObjectName(_fromUtf8("tab_10"))
		self.s3ODID_pushButton = QtGui.QPushButton(self.tab_10)
		self.s3ODID_pushButton.setGeometry(QtCore.QRect(490, 50, 111, 31))
		self.s3ODID_pushButton.setObjectName(_fromUtf8("s3ODID_pushButton"))
		self.s3ODWt_pushButton = QtGui.QPushButton(self.tab_10)
		self.s3ODWt_pushButton.setGeometry(QtCore.QRect(490, 110, 111, 31))
		self.s3ODWt_pushButton.setObjectName(_fromUtf8("s3ODWt_pushButton"))
		self.s3PipeProperties_tableWidget = QtGui.QTableWidget(self.tab_10)
		self.s3PipeProperties_tableWidget.setGeometry(QtCore.QRect(14, 21, 461, 332))
		font = QtGui.QFont()
		font.setPointSize(9)
		self.s3PipeProperties_tableWidget.setFont(font)
		self.s3PipeProperties_tableWidget.setFrameShape(QtGui.QFrame.StyledPanel)
		self.s3PipeProperties_tableWidget.setColumnCount(1)
		self.s3PipeProperties_tableWidget.setObjectName(_fromUtf8("s3PipeProperties_tableWidget"))
		self.s3PipeProperties_tableWidget.setRowCount(11)
		item = QtGui.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(0, item)
		item = QtGui.QTableWidgetItem()
		font = QtGui.QFont()
		font.setKerning(False)
		item.setFont(font)
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(1, item)
		item = QtGui.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(2, item)
		item = QtGui.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(3, item)
		item = QtGui.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(4, item)
		item = QtGui.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(5, item)
		item = QtGui.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(6, item)
		item = QtGui.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(7, item)
		item = QtGui.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(8, item)
		item = QtGui.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(9, item)
		item = QtGui.QTableWidgetItem()
		self.s3PipeProperties_tableWidget.setVerticalHeaderItem(10, item)
		self.s3PipeProperties_tableWidget.horizontalHeader().setVisible(False)
		self.s3PipeProperties_tableWidget.horizontalHeader().setDefaultSectionSize(250)
		self.s3PipeProperties_tableWidget.horizontalHeader().setMinimumSectionSize(120)
		self.s3PipeProperties_tableWidget.verticalHeader().setDefaultSectionSize(30)
		self.s3PipeProperties_tableWidget.verticalHeader().setMinimumSectionSize(20)
		self.s3InnerStageToolkit_tabWidget.addTab(self.tab_10, _fromUtf8(""))
		self.tab_11 = QtGui.QWidget()
		self.tab_11.setObjectName(_fromUtf8("tab_11"))
		self.ABC_tabWidget = QtGui.QTabWidget(self.tab_11)
		self.ABC_tabWidget.setEnabled(False)
		self.ABC_tabWidget.setGeometry(QtCore.QRect(10, 10, 611, 421))
		font = QtGui.QFont()
		font.setBold(False)
		font.setWeight(50)
		font.setStrikeOut(False)
		font.setKerning(True)
		self.ABC_tabWidget.setFont(font)
		self.ABC_tabWidget.setMouseTracking(False)
		self.ABC_tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
		self.ABC_tabWidget.setTabPosition(QtGui.QTabWidget.West)
		self.ABC_tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
		self.ABC_tabWidget.setIconSize(QtCore.QSize(20, 20))
		self.ABC_tabWidget.setElideMode(QtCore.Qt.ElideNone)
		self.ABC_tabWidget.setDocumentMode(False)
		self.ABC_tabWidget.setTabsClosable(False)
		self.ABC_tabWidget.setMovable(False)
		self.ABC_tabWidget.setObjectName(_fromUtf8("ABC_tabWidget"))
		self.tab_A = QtGui.QWidget()
		self.tab_A.setObjectName(_fromUtf8("tab_A"))
		self.s3BowSpringCentralizer_radioButton_A = QtGui.QRadioButton(self.tab_A)
		self.s3BowSpringCentralizer_radioButton_A.setGeometry(QtCore.QRect(24, 20, 109, 25))
		self.s3BowSpringCentralizer_radioButton_A.setChecked(True)
		self.s3BowSpringCentralizer_radioButton_A.setObjectName(_fromUtf8("s3BowSpringCentralizer_radioButton_A"))
		self.s3RigidCentralizer_radioButton_A = QtGui.QRadioButton(self.tab_A)
		self.s3RigidCentralizer_radioButton_A.setGeometry(QtCore.QRect(24, 70, 64, 25))
		self.s3RigidCentralizer_radioButton_A.setObjectName(_fromUtf8("s3RigidCentralizer_radioButton_A"))
		self.s3CentralizerProperties_tableWidget_A = QtGui.QTableWidget(self.tab_A)
		self.s3CentralizerProperties_tableWidget_A.setGeometry(QtCore.QRect(20, 120, 341, 281))
		self.s3CentralizerProperties_tableWidget_A.setFocusPolicy(QtCore.Qt.WheelFocus)
		self.s3CentralizerProperties_tableWidget_A.setRowCount(10)
		self.s3CentralizerProperties_tableWidget_A.setColumnCount(1)
		self.s3CentralizerProperties_tableWidget_A.setObjectName(_fromUtf8("s3CentralizerProperties_tableWidget_A"))
		self.s3CentralizerProperties_tableWidget_A.horizontalHeader().setVisible(False)
		self.s3CentralizerProperties_tableWidget_A.horizontalHeader().setDefaultSectionSize(150)
		self.s3CentralizerProperties_tableWidget_A.horizontalHeader().setMinimumSectionSize(120)
		self.s3CentralizerProperties_tableWidget_A.verticalHeader().setDefaultSectionSize(30)
		self.s3CentralizerProperties_tableWidget_A.verticalHeader().setMinimumSectionSize(28)
		self.s3Location_label_A = QtGui.QLabel(self.tab_A)
		self.s3Location_label_A.setGeometry(QtCore.QRect(380, 20, 71, 21))
		self.s3Location_label_A.setObjectName(_fromUtf8("s3Location_label_A"))
		self.s3CentralizerRunningForce_tableWidget_A = QtGui.QTableWidget(self.tab_A)
		self.s3CentralizerRunningForce_tableWidget_A.setEnabled(False)
		self.s3CentralizerRunningForce_tableWidget_A.setGeometry(QtCore.QRect(50, 210, 293, 111))
		font = QtGui.QFont()
		font.setPointSize(9)
		self.s3CentralizerRunningForce_tableWidget_A.setFont(font)
		self.s3CentralizerRunningForce_tableWidget_A.setStyleSheet(_fromUtf8(""))
		self.s3CentralizerRunningForce_tableWidget_A.setFrameShape(QtGui.QFrame.WinPanel)
		self.s3CentralizerRunningForce_tableWidget_A.setAlternatingRowColors(True)
		self.s3CentralizerRunningForce_tableWidget_A.setRowCount(10)
		self.s3CentralizerRunningForce_tableWidget_A.setObjectName(_fromUtf8("s3CentralizerRunningForce_tableWidget_A"))
		self.s3CentralizerRunningForce_tableWidget_A.setColumnCount(2)
		item = QtGui.QTableWidgetItem()
		self.s3CentralizerRunningForce_tableWidget_A.setHorizontalHeaderItem(0, item)
		item = QtGui.QTableWidgetItem()
		self.s3CentralizerRunningForce_tableWidget_A.setHorizontalHeaderItem(1, item)
		self.s3CentralizerRunningForce_tableWidget_A.horizontalHeader().setDefaultSectionSize(120)
		self.s3CentralizerRunningForce_tableWidget_A.horizontalHeader().setMinimumSectionSize(100)
		self.s3CentralizerRunningForce_tableWidget_A.verticalHeader().setDefaultSectionSize(25)
		self.s3CentralizerDB_pushButton_A = QtGui.QPushButton(self.tab_A)
		self.s3CentralizerDB_pushButton_A.setGeometry(QtCore.QRect(170, 40, 141, 41))
		self.s3CentralizerDB_pushButton_A.setObjectName(_fromUtf8("s3CentralizerDB_pushButton_A"))
		self.s3CentralizerLocation_tableWidget_A = QtGui.QTableWidget(self.tab_A)
		self.s3CentralizerLocation_tableWidget_A.setGeometry(QtCore.QRect(380, 50, 175, 351))
		font = QtGui.QFont()
		font.setPointSize(9)
		self.s3CentralizerLocation_tableWidget_A.setFont(font)
		self.s3CentralizerLocation_tableWidget_A.setStyleSheet(_fromUtf8(""))
		self.s3CentralizerLocation_tableWidget_A.setFrameShape(QtGui.QFrame.WinPanel)
		self.s3CentralizerLocation_tableWidget_A.setAlternatingRowColors(True)
		self.s3CentralizerLocation_tableWidget_A.setRowCount(1000)
		self.s3CentralizerLocation_tableWidget_A.setObjectName(_fromUtf8("s3CentralizerLocation_tableWidget_A"))
		self.s3CentralizerLocation_tableWidget_A.setColumnCount(1)
		item = QtGui.QTableWidgetItem()
		self.s3CentralizerLocation_tableWidget_A.setHorizontalHeaderItem(0, item)
		self.s3CentralizerLocation_tableWidget_A.horizontalHeader().setDefaultSectionSize(125)
		self.s3CentralizerLocation_tableWidget_A.verticalHeader().setDefaultSectionSize(25)
		self.s3CentralizerRunningForce_tableWidget_A.raise_()
		self.s3BowSpringCentralizer_radioButton_A.raise_()
		self.s3RigidCentralizer_radioButton_A.raise_()
		self.s3CentralizerProperties_tableWidget_A.raise_()
		self.s3Location_label_A.raise_()
		self.s3CentralizerDB_pushButton_A.raise_()
		self.s3CentralizerLocation_tableWidget_A.raise_()
		self.ABC_tabWidget.addTab(self.tab_A, _fromUtf8(""))
		self.tab_B = QtGui.QWidget()
		self.tab_B.setObjectName(_fromUtf8("tab_B"))
		self.s3CentralizerLocation_tableWidget_B = QtGui.QTableWidget(self.tab_B)
		self.s3CentralizerLocation_tableWidget_B.setEnabled(False)
		self.s3CentralizerLocation_tableWidget_B.setGeometry(QtCore.QRect(380, 50, 175, 351))
		font = QtGui.QFont()
		font.setPointSize(9)
		self.s3CentralizerLocation_tableWidget_B.setFont(font)
		self.s3CentralizerLocation_tableWidget_B.setStyleSheet(_fromUtf8(""))
		self.s3CentralizerLocation_tableWidget_B.setFrameShape(QtGui.QFrame.WinPanel)
		self.s3CentralizerLocation_tableWidget_B.setAlternatingRowColors(True)
		self.s3CentralizerLocation_tableWidget_B.setRowCount(1000)
		self.s3CentralizerLocation_tableWidget_B.setObjectName(_fromUtf8("s3CentralizerLocation_tableWidget_B"))
		self.s3CentralizerLocation_tableWidget_B.setColumnCount(1)
		item = QtGui.QTableWidgetItem()
		self.s3CentralizerLocation_tableWidget_B.setHorizontalHeaderItem(0, item)
		self.s3CentralizerLocation_tableWidget_B.horizontalHeader().setDefaultSectionSize(125)
		self.s3CentralizerLocation_tableWidget_B.verticalHeader().setDefaultSectionSize(25)
		self.s3CentralizerRunningForce_tableWidget_B = QtGui.QTableWidget(self.tab_B)
		self.s3CentralizerRunningForce_tableWidget_B.setEnabled(False)
		self.s3CentralizerRunningForce_tableWidget_B.setGeometry(QtCore.QRect(50, 210, 293, 71))
		font = QtGui.QFont()
		font.setPointSize(9)
		self.s3CentralizerRunningForce_tableWidget_B.setFont(font)
		self.s3CentralizerRunningForce_tableWidget_B.setStyleSheet(_fromUtf8(""))
		self.s3CentralizerRunningForce_tableWidget_B.setFrameShape(QtGui.QFrame.WinPanel)
		self.s3CentralizerRunningForce_tableWidget_B.setAlternatingRowColors(True)
		self.s3CentralizerRunningForce_tableWidget_B.setRowCount(10)
		self.s3CentralizerRunningForce_tableWidget_B.setObjectName(_fromUtf8("s3CentralizerRunningForce_tableWidget_B"))
		self.s3CentralizerRunningForce_tableWidget_B.setColumnCount(2)
		item = QtGui.QTableWidgetItem()
		self.s3CentralizerRunningForce_tableWidget_B.setHorizontalHeaderItem(0, item)
		item = QtGui.QTableWidgetItem()
		self.s3CentralizerRunningForce_tableWidget_B.setHorizontalHeaderItem(1, item)
		self.s3CentralizerRunningForce_tableWidget_B.horizontalHeader().setDefaultSectionSize(120)
		self.s3CentralizerRunningForce_tableWidget_B.horizontalHeader().setMinimumSectionSize(100)
		self.s3CentralizerRunningForce_tableWidget_B.verticalHeader().setDefaultSectionSize(25)
		self.s3RigidCentralizer_radioButton_B = QtGui.QRadioButton(self.tab_B)
		self.s3RigidCentralizer_radioButton_B.setGeometry(QtCore.QRect(24, 70, 64, 25))
		self.s3RigidCentralizer_radioButton_B.setObjectName(_fromUtf8("s3RigidCentralizer_radioButton_B"))
		self.s3CentralizerProperties_tableWidget_B = QtGui.QTableWidget(self.tab_B)
		self.s3CentralizerProperties_tableWidget_B.setEnabled(False)
		self.s3CentralizerProperties_tableWidget_B.setGeometry(QtCore.QRect(20, 160, 341, 241))
		self.s3CentralizerProperties_tableWidget_B.setFocusPolicy(QtCore.Qt.WheelFocus)
		self.s3CentralizerProperties_tableWidget_B.setRowCount(10)
		self.s3CentralizerProperties_tableWidget_B.setColumnCount(1)
		self.s3CentralizerProperties_tableWidget_B.setObjectName(_fromUtf8("s3CentralizerProperties_tableWidget_B"))
		self.s3CentralizerProperties_tableWidget_B.horizontalHeader().setVisible(False)
		self.s3CentralizerProperties_tableWidget_B.horizontalHeader().setDefaultSectionSize(150)
		self.s3CentralizerProperties_tableWidget_B.horizontalHeader().setMinimumSectionSize(120)
		self.s3CentralizerProperties_tableWidget_B.verticalHeader().setDefaultSectionSize(30)
		self.s3CentralizerProperties_tableWidget_B.verticalHeader().setMinimumSectionSize(28)
		self.s3CentralizerDB_pushButton_B = QtGui.QPushButton(self.tab_B)
		self.s3CentralizerDB_pushButton_B.setEnabled(False)
		self.s3CentralizerDB_pushButton_B.setGeometry(QtCore.QRect(170, 40, 141, 41))
		self.s3CentralizerDB_pushButton_B.setObjectName(_fromUtf8("s3CentralizerDB_pushButton_B"))
		self.s3BowSpringCentralizer_radioButton_B = QtGui.QRadioButton(self.tab_B)
		self.s3BowSpringCentralizer_radioButton_B.setGeometry(QtCore.QRect(24, 20, 109, 25))
		self.s3BowSpringCentralizer_radioButton_B.setObjectName(_fromUtf8("s3BowSpringCentralizer_radioButton_B"))
		self.s3Location_label_B = QtGui.QLabel(self.tab_B)
		self.s3Location_label_B.setGeometry(QtCore.QRect(380, 20, 71, 21))
		self.s3Location_label_B.setObjectName(_fromUtf8("s3Location_label_B"))
		self.s3NoneCentralizer_radioButton_B = QtGui.QRadioButton(self.tab_B)
		self.s3NoneCentralizer_radioButton_B.setGeometry(QtCore.QRect(24, 120, 95, 25))
		self.s3NoneCentralizer_radioButton_B.setChecked(True)
		self.s3NoneCentralizer_radioButton_B.setObjectName(_fromUtf8("s3NoneCentralizer_radioButton_B"))
		self.ABC_tabWidget.addTab(self.tab_B, _fromUtf8(""))
		self.tab_C = QtGui.QWidget()
		self.tab_C.setObjectName(_fromUtf8("tab_C"))
		self.s3BowSpringCentralizer_radioButton_C = QtGui.QRadioButton(self.tab_C)
		self.s3BowSpringCentralizer_radioButton_C.setGeometry(QtCore.QRect(24, 20, 109, 25))
		self.s3BowSpringCentralizer_radioButton_C.setObjectName(_fromUtf8("s3BowSpringCentralizer_radioButton_C"))
		self.s3RigidCentralizer_radioButton_C = QtGui.QRadioButton(self.tab_C)
		self.s3RigidCentralizer_radioButton_C.setGeometry(QtCore.QRect(24, 70, 64, 25))
		self.s3RigidCentralizer_radioButton_C.setObjectName(_fromUtf8("s3RigidCentralizer_radioButton_C"))
		self.s3CentralizerProperties_tableWidget_C = QtGui.QTableWidget(self.tab_C)
		self.s3CentralizerProperties_tableWidget_C.setEnabled(False)
		self.s3CentralizerProperties_tableWidget_C.setGeometry(QtCore.QRect(20, 160, 341, 241))
		self.s3CentralizerProperties_tableWidget_C.setRowCount(10)
		self.s3CentralizerProperties_tableWidget_C.setColumnCount(1)
		self.s3CentralizerProperties_tableWidget_C.setObjectName(_fromUtf8("s3CentralizerProperties_tableWidget_C"))
		self.s3CentralizerProperties_tableWidget_C.horizontalHeader().setVisible(False)
		self.s3CentralizerProperties_tableWidget_C.horizontalHeader().setDefaultSectionSize(150)
		self.s3CentralizerProperties_tableWidget_C.horizontalHeader().setMinimumSectionSize(120)
		self.s3CentralizerProperties_tableWidget_C.verticalHeader().setDefaultSectionSize(30)
		self.s3CentralizerProperties_tableWidget_C.verticalHeader().setMinimumSectionSize(28)
		self.s3Location_label_C = QtGui.QLabel(self.tab_C)
		self.s3Location_label_C.setGeometry(QtCore.QRect(380, 20, 71, 21))
		self.s3Location_label_C.setObjectName(_fromUtf8("s3Location_label_C"))
		self.s3CentralizerRunningForce_tableWidget_C = QtGui.QTableWidget(self.tab_C)
		self.s3CentralizerRunningForce_tableWidget_C.setEnabled(False)
		self.s3CentralizerRunningForce_tableWidget_C.setGeometry(QtCore.QRect(60, 190, 293, 61))
		font = QtGui.QFont()
		font.setPointSize(9)
		self.s3CentralizerRunningForce_tableWidget_C.setFont(font)
		self.s3CentralizerRunningForce_tableWidget_C.setStyleSheet(_fromUtf8(""))
		self.s3CentralizerRunningForce_tableWidget_C.setFrameShape(QtGui.QFrame.WinPanel)
		self.s3CentralizerRunningForce_tableWidget_C.setAlternatingRowColors(True)
		self.s3CentralizerRunningForce_tableWidget_C.setRowCount(10)
		self.s3CentralizerRunningForce_tableWidget_C.setObjectName(_fromUtf8("s3CentralizerRunningForce_tableWidget_C"))
		self.s3CentralizerRunningForce_tableWidget_C.setColumnCount(2)
		item = QtGui.QTableWidgetItem()
		self.s3CentralizerRunningForce_tableWidget_C.setHorizontalHeaderItem(0, item)
		item = QtGui.QTableWidgetItem()
		self.s3CentralizerRunningForce_tableWidget_C.setHorizontalHeaderItem(1, item)
		self.s3CentralizerRunningForce_tableWidget_C.horizontalHeader().setDefaultSectionSize(120)
		self.s3CentralizerRunningForce_tableWidget_C.horizontalHeader().setMinimumSectionSize(100)
		self.s3CentralizerRunningForce_tableWidget_C.verticalHeader().setDefaultSectionSize(25)
		self.s3CentralizerDB_pushButton_C = QtGui.QPushButton(self.tab_C)
		self.s3CentralizerDB_pushButton_C.setEnabled(False)
		self.s3CentralizerDB_pushButton_C.setGeometry(QtCore.QRect(170, 40, 141, 41))
		self.s3CentralizerDB_pushButton_C.setObjectName(_fromUtf8("s3CentralizerDB_pushButton_C"))
		self.s3CentralizerLocation_tableWidget_C = QtGui.QTableWidget(self.tab_C)
		self.s3CentralizerLocation_tableWidget_C.setEnabled(False)
		self.s3CentralizerLocation_tableWidget_C.setGeometry(QtCore.QRect(380, 50, 175, 351))
		font = QtGui.QFont()
		font.setPointSize(9)
		self.s3CentralizerLocation_tableWidget_C.setFont(font)
		self.s3CentralizerLocation_tableWidget_C.setStyleSheet(_fromUtf8(""))
		self.s3CentralizerLocation_tableWidget_C.setFrameShape(QtGui.QFrame.WinPanel)
		self.s3CentralizerLocation_tableWidget_C.setAlternatingRowColors(True)
		self.s3CentralizerLocation_tableWidget_C.setRowCount(1000)
		self.s3CentralizerLocation_tableWidget_C.setObjectName(_fromUtf8("s3CentralizerLocation_tableWidget_C"))
		self.s3CentralizerLocation_tableWidget_C.setColumnCount(1)
		item = QtGui.QTableWidgetItem()
		self.s3CentralizerLocation_tableWidget_C.setHorizontalHeaderItem(0, item)
		self.s3CentralizerLocation_tableWidget_C.horizontalHeader().setDefaultSectionSize(125)
		self.s3CentralizerLocation_tableWidget_C.verticalHeader().setDefaultSectionSize(25)
		self.s3NoneCentralizer_radioButton_C = QtGui.QRadioButton(self.tab_C)
		self.s3NoneCentralizer_radioButton_C.setGeometry(QtCore.QRect(24, 120, 95, 25))
		self.s3NoneCentralizer_radioButton_C.setChecked(True)
		self.s3NoneCentralizer_radioButton_C.setObjectName(_fromUtf8("s3NoneCentralizer_radioButton_C"))
		self.s3CentralizerRunningForce_tableWidget_C.raise_()
		self.s3BowSpringCentralizer_radioButton_C.raise_()
		self.s3RigidCentralizer_radioButton_C.raise_()
		self.s3CentralizerProperties_tableWidget_C.raise_()
		self.s3Location_label_C.raise_()
		self.s3CentralizerDB_pushButton_C.raise_()
		self.s3CentralizerLocation_tableWidget_C.raise_()
		self.s3NoneCentralizer_radioButton_C.raise_()
		self.ABC_tabWidget.addTab(self.tab_C, _fromUtf8(""))
		self.s3InnerStageToolkit_tabWidget.addTab(self.tab_11, _fromUtf8(""))
		self.s3SpecifyCentralization_pushButton = QtGui.QPushButton(self.groupBox_5)
		self.s3SpecifyCentralization_pushButton.setGeometry(QtCore.QRect(600, 500, 251, 41))
		self.s3SpecifyCentralization_pushButton.setObjectName(_fromUtf8("s3SpecifyCentralization_pushButton"))
		self.SO_label = QtGui.QLabel(self.groupBox_5)
		self.SO_label.setGeometry(QtCore.QRect(910, 500, 271, 41))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(True)
		font.setWeight(75)
		self.SO_label.setFont(font)
		self.SO_label.setText(_fromUtf8(""))
		self.SO_label.setObjectName(_fromUtf8("SO_label"))
		self.Menu.addTab(self.tab_4, _fromUtf8(""))
		self.tab_2 = QtGui.QWidget()
		self.tab_2.setObjectName(_fromUtf8("tab_2"))
		self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
		self.groupBox_7.setGeometry(QtCore.QRect(20, 20, 591, 731))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.groupBox_7.setFont(font)
		self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
		self.s4Settings_tableWidget = QtGui.QTableWidget(self.groupBox_7)
		self.s4Settings_tableWidget.setGeometry(QtCore.QRect(10, 40, 401, 152))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.s4Settings_tableWidget.setFont(font)
		self.s4Settings_tableWidget.setAutoFillBackground(False)
		self.s4Settings_tableWidget.setFrameShadow(QtGui.QFrame.Sunken)
		self.s4Settings_tableWidget.setColumnCount(1)
		self.s4Settings_tableWidget.setObjectName(_fromUtf8("s4Settings_tableWidget"))
		self.s4Settings_tableWidget.setRowCount(5)
		item = QtGui.QTableWidgetItem()
		self.s4Settings_tableWidget.setVerticalHeaderItem(0, item)
		item = QtGui.QTableWidgetItem()
		self.s4Settings_tableWidget.setVerticalHeaderItem(1, item)
		item = QtGui.QTableWidgetItem()
		self.s4Settings_tableWidget.setVerticalHeaderItem(2, item)
		item = QtGui.QTableWidgetItem()
		self.s4Settings_tableWidget.setVerticalHeaderItem(3, item)
		item = QtGui.QTableWidgetItem()
		self.s4Settings_tableWidget.setVerticalHeaderItem(4, item)
		self.s4Settings_tableWidget.horizontalHeader().setVisible(False)
		self.s4Settings_tableWidget.horizontalHeader().setCascadingSectionResizes(False)
		self.s4Settings_tableWidget.horizontalHeader().setDefaultSectionSize(100)
		self.s4Settings_tableWidget.horizontalHeader().setHighlightSections(True)
		self.s4Settings_tableWidget.horizontalHeader().setMinimumSectionSize(30)
		self.s4Settings_tableWidget.horizontalHeader().setSortIndicatorShown(False)
		self.s4Settings_tableWidget.horizontalHeader().setStretchLastSection(False)
		self.s4Settings_tableWidget.verticalHeader().setDefaultSectionSize(30)
		self.s4Settings_tableWidget.verticalHeader().setMinimumSectionSize(28)
		self.s4Settings_tableWidget.verticalHeader().setSortIndicatorShown(False)
		self.s4TorqueDragSideforce_tableWidget = QtGui.QTableWidget(self.groupBox_7)
		self.s4TorqueDragSideforce_tableWidget.setGeometry(QtCore.QRect(10, 220, 561, 481))
		self.s4TorqueDragSideforce_tableWidget.setStyleSheet(_fromUtf8(""))
		self.s4TorqueDragSideforce_tableWidget.setFrameShape(QtGui.QFrame.WinPanel)
		self.s4TorqueDragSideforce_tableWidget.setRowCount(10000)
		self.s4TorqueDragSideforce_tableWidget.setObjectName(_fromUtf8("s4TorqueDragSideforce_tableWidget"))
		self.s4TorqueDragSideforce_tableWidget.setColumnCount(9)
		item = QtGui.QTableWidgetItem()
		self.s4TorqueDragSideforce_tableWidget.setHorizontalHeaderItem(0, item)
		item = QtGui.QTableWidgetItem()
		self.s4TorqueDragSideforce_tableWidget.setHorizontalHeaderItem(1, item)
		item = QtGui.QTableWidgetItem()
		self.s4TorqueDragSideforce_tableWidget.setHorizontalHeaderItem(2, item)
		item = QtGui.QTableWidgetItem()
		self.s4TorqueDragSideforce_tableWidget.setHorizontalHeaderItem(3, item)
		item = QtGui.QTableWidgetItem()
		self.s4TorqueDragSideforce_tableWidget.setHorizontalHeaderItem(4, item)
		item = QtGui.QTableWidgetItem()
		self.s4TorqueDragSideforce_tableWidget.setHorizontalHeaderItem(5, item)
		item = QtGui.QTableWidgetItem()
		self.s4TorqueDragSideforce_tableWidget.setHorizontalHeaderItem(6, item)
		item = QtGui.QTableWidgetItem()
		self.s4TorqueDragSideforce_tableWidget.setHorizontalHeaderItem(7, item)
		item = QtGui.QTableWidgetItem()
		self.s4TorqueDragSideforce_tableWidget.setHorizontalHeaderItem(8, item)
		self.s4TorqueDragSideforce_tableWidget.horizontalHeader().setDefaultSectionSize(100)
		self.s4TorqueDragSideforce_tableWidget.verticalHeader().setDefaultSectionSize(30)
		self.s4TorqueDragSideforce_tableWidget.verticalHeader().setMinimumSectionSize(30)
		self.s4Calculate_pushButton = QtGui.QPushButton(self.groupBox_7)
		self.s4Calculate_pushButton.setGeometry(QtCore.QRect(440, 100, 121, 41))
		self.s4Calculate_pushButton.setObjectName(_fromUtf8("s4Calculate_pushButton"))
		self.tabWidget_2 = QtGui.QTabWidget(self.tab_2)
		self.tabWidget_2.setGeometry(QtCore.QRect(620, 30, 621, 721))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.tabWidget_2.setFont(font)
		self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
		self.tab_12 = QtGui.QWidget()
		self.tab_12.setObjectName(_fromUtf8("tab_12"))
		self.s4Drag_graphicsView = MatplotlibWidget(self.tab_12)
		self.s4Drag_graphicsView.setGeometry(QtCore.QRect(30, 60, 551, 600))
		self.s4Drag_graphicsView.setObjectName(_fromUtf8("s4Drag_graphicsView"))
		self.tabWidget_2.addTab(self.tab_12, _fromUtf8(""))
		self.tab_13 = QtGui.QWidget()
		self.tab_13.setObjectName(_fromUtf8("tab_13"))
		self.s4Torque_graphicsView = MatplotlibWidget(self.tab_13)
		self.s4Torque_graphicsView.setGeometry(QtCore.QRect(30, 60, 551, 600))
		self.s4Torque_graphicsView.setObjectName(_fromUtf8("s4Torque_graphicsView"))
		self.tabWidget_2.addTab(self.tab_13, _fromUtf8(""))
		self.tab_14 = QtGui.QWidget()
		self.tab_14.setObjectName(_fromUtf8("tab_14"))
		self.s4Sideforce_graphicsView = MatplotlibWidget(self.tab_14)
		self.s4Sideforce_graphicsView.setGeometry(QtCore.QRect(30, 60, 551, 600))
		self.s4Sideforce_graphicsView.setObjectName(_fromUtf8("s4Sideforce_graphicsView"))
		self.tabWidget_2.addTab(self.tab_14, _fromUtf8(""))
		self.Menu.addTab(self.tab_2, _fromUtf8(""))
		self.msg_label = QtGui.QLabel(self.centralwidget)
		self.msg_label.setGeometry(QtCore.QRect(50, 800, 1251, 41))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(True)
		font.setWeight(75)
		self.msg_label.setFont(font)
		self.msg_label.setText(_fromUtf8(""))
		self.msg_label.setObjectName(_fromUtf8("msg_label"))
		InputWindow.setCentralWidget(self.centralwidget)
		self.iw_toolBar = QtGui.QToolBar(InputWindow)
		self.iw_toolBar.setIconSize(QtCore.QSize(30, 30))
		self.iw_toolBar.setObjectName(_fromUtf8("iw_toolBar"))
		InputWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.iw_toolBar)
		self.actionNew = QtGui.QAction(InputWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/document-new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionNew.setIcon(icon)
		self.actionNew.setObjectName(_fromUtf8("actionNew"))
		self.actionOpen = QtGui.QAction(InputWindow)
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/document-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionOpen.setIcon(icon1)
		self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
		self.actionSave = QtGui.QAction(InputWindow)
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/document-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionSave.setIcon(icon2)
		self.actionSave.setObjectName(_fromUtf8("actionSave"))
		self.actionSave_As = QtGui.QAction(InputWindow)
		self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
		self.actionPrint = QtGui.QAction(InputWindow)
		self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
		self.actionPrint_2 = QtGui.QAction(InputWindow)
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/document-print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionPrint_2.setIcon(icon3)
		self.actionPrint_2.setObjectName(_fromUtf8("actionPrint_2"))
		self.actionExit = QtGui.QAction(InputWindow)
		self.actionExit.setObjectName(_fromUtf8("actionExit"))
		self.actionCopy_Selection = QtGui.QAction(InputWindow)
		self.actionCopy_Selection.setObjectName(_fromUtf8("actionCopy_Selection"))
		self.actionPaste = QtGui.QAction(InputWindow)
		self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
		self.actionOne_Span_Analysis = QtGui.QAction(InputWindow)
		icon4 = QtGui.QIcon()
		icon4.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/games-solve.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionOne_Span_Analysis.setIcon(icon4)
		self.actionOne_Span_Analysis.setObjectName(_fromUtf8("actionOne_Span_Analysis"))
		self.actionUnit_Setting = QtGui.QAction(InputWindow)
		self.actionUnit_Setting.setObjectName(_fromUtf8("actionUnit_Setting"))
		self.actionUnit_Conversion = QtGui.QAction(InputWindow)
		icon5 = QtGui.QIcon()
		icon5.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/measure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionUnit_Conversion.setIcon(icon5)
		self.actionUnit_Conversion.setObjectName(_fromUtf8("actionUnit_Conversion"))
		self.actionCalculator = QtGui.QAction(InputWindow)
		icon6 = QtGui.QIcon()
		icon6.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/accessories-calculator.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionCalculator.setIcon(icon6)
		self.actionCalculator.setObjectName(_fromUtf8("actionCalculator"))
		self.actionNotepad = QtGui.QAction(InputWindow)
		icon7 = QtGui.QIcon()
		icon7.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/story-editor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionNotepad.setIcon(icon7)
		self.actionNotepad.setObjectName(_fromUtf8("actionNotepad"))
		self.actionAbout = QtGui.QAction(InputWindow)
		icon8 = QtGui.QIcon()
		icon8.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/system-help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionAbout.setIcon(icon8)
		self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
		self.actionAbbreviation = QtGui.QAction(InputWindow)
		self.actionAbbreviation.setObjectName(_fromUtf8("actionAbbreviation"))
		self.actionDisclaimer = QtGui.QAction(InputWindow)
		self.actionDisclaimer.setObjectName(_fromUtf8("actionDisclaimer"))
		self.actionStar_Calculation = QtGui.QAction(InputWindow)
		icon9 = QtGui.QIcon()
		icon9.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/arrow-right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionStar_Calculation.setIcon(icon9)
		self.actionStar_Calculation.setObjectName(_fromUtf8("actionStar_Calculation"))
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionStar_Calculation)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionOne_Span_Analysis)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionUnit_Conversion)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionAbout)

		self.retranslateUi(InputWindow)
		self.Menu.setCurrentIndex(0)
		self.tabWidget.setCurrentIndex(0)
		self.s3InnerStageToolkit_tabWidget.setCurrentIndex(0)
		self.ABC_tabWidget.setCurrentIndex(0)
		self.tabWidget_2.setCurrentIndex(0)
		QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), InputWindow.close)
		QtCore.QMetaObject.connectSlotsByName(InputWindow)

	def retranslateUi(self, InputWindow):
		InputWindow.setWindowTitle(_translate("InputWindow", "Central Software - Main Window", None))
		self.Menu.setToolTip(_translate("InputWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
		self.groupBox.setTitle(_translate("InputWindow", "General Information", None))
		item = self.s1Info_tableWidget.verticalHeaderItem(0)
		item.setText(_translate("InputWindow", "Well name", None))
		item = self.s1Info_tableWidget.verticalHeaderItem(1)
		item.setText(_translate("InputWindow", "Location", None))
		item = self.s1Info_tableWidget.verticalHeaderItem(2)
		item.setText(_translate("InputWindow", "Operator", None))
		item = self.s1Info_tableWidget.verticalHeaderItem(3)
		item.setText(_translate("InputWindow", "Contractor", None))
		item = self.s1Info_tableWidget.verticalHeaderItem(4)
		item.setText(_translate("InputWindow", "Date", None))
		item = self.s1Info_tableWidget.verticalHeaderItem(5)
		item.setText(_translate("InputWindow", "Directory", None))
		self.groupBox_2.setTitle(_translate("InputWindow", "Units", None))
		self.s1USOF_radioButton.setText(_translate("InputWindow", "US oil field", None))
		self.s1Metric_radioButton.setText(_translate("InputWindow", "Metric", None))
		self.s1Customized_radioButton.setText(_translate("InputWindow", "Customized", None))
		self.s1UnitSetting_pushButton.setText(_translate("InputWindow", "Unit Setting...", None))
		self.s1SelectDirectory_pushButton.setText(_translate("InputWindow", "Select directory ...", None))
		self.Menu.setTabText(self.Menu.indexOf(self.tab), _translate("InputWindow", "General", None))
		self.s2Import_pushButton.setText(_translate("InputWindow", "Import Survey", None))
		self.s2Remove_pushButton.setText(_translate("InputWindow", "Clear All", None))
		self.s2Calculate_pushButton.setText(_translate("InputWindow", "CALCULATE", None))
		self.s2SurveyTortuosity_groupBox.setTitle(_translate("InputWindow", "Survey tortuosity", None))
		item = self.s2SurveyTortuosity_tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "From", None))
		item = self.s2SurveyTortuosity_tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("InputWindow", "To", None))
		item = self.s2SurveyTortuosity_tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("InputWindow", "Amplitude", None))
		item = self.s2SurveyTortuosity_tableWidget.horizontalHeaderItem(3)
		item.setText(_translate("InputWindow", "Period", None))
		self.s2TortuosityInterval_tableWidget.setSortingEnabled(False)
		item = self.s2TortuosityInterval_tableWidget.verticalHeaderItem(0)
		item.setText(_translate("InputWindow", "Interval [unit]", None))
		self.s2DataSurvey_tableWidget.setSortingEnabled(False)
		item = self.s2DataSurvey_tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "MD", None))
		item = self.s2DataSurvey_tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("InputWindow", "Inc", None))
		item = self.s2DataSurvey_tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("InputWindow", "Azi", None))
		item = self.s2DataSurvey_tableWidget.horizontalHeaderItem(3)
		item.setText(_translate("InputWindow", "TVD", None))
		item = self.s2DataSurvey_tableWidget.horizontalHeaderItem(4)
		item.setText(_translate("InputWindow", "Vsec", None))
		item = self.s2DataSurvey_tableWidget.horizontalHeaderItem(5)
		item.setText(_translate("InputWindow", "N+/S-", None))
		item = self.s2DataSurvey_tableWidget.horizontalHeaderItem(6)
		item.setText(_translate("InputWindow", "E+/W-", None))
		item = self.s2DataSurvey_tableWidget.horizontalHeaderItem(7)
		item.setText(_translate("InputWindow", "Dogleg", None))
		__sortingEnabled = self.s2DataSurvey_tableWidget.isSortingEnabled()
		self.s2DataSurvey_tableWidget.setSortingEnabled(False)
		self.s2DataSurvey_tableWidget.setSortingEnabled(__sortingEnabled)
		self.s2SurveyTortuosity_checkBox.setText(_translate("InputWindow", "Include Survey Tortuosity", None))
		self.s2KOP_tableWidget.setSortingEnabled(False)
		item = self.s2KOP_tableWidget.verticalHeaderItem(0)
		item.setText(_translate("InputWindow", "KOP [unit]", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("InputWindow", "Data", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("InputWindow", "Section View", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("InputWindow", "Plan View", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("InputWindow", "3D View", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("InputWindow", "Dogleg", None))
		self.Menu.setTabText(self.Menu.indexOf(self.tab_3), _translate("InputWindow", "Survey", None))
		self.groupBox_4.setTitle(_translate("InputWindow", "Wellbore Outer Stages (from top down)", None))
		item = self.s3WellboreIntervals_tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "Description", None))
		item = self.s3WellboreIntervals_tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("InputWindow", "ID", None))
		item = self.s3WellboreIntervals_tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("InputWindow", "Drift", None))
		item = self.s3WellboreIntervals_tableWidget.horizontalHeaderItem(3)
		item.setText(_translate("InputWindow", "top MD", None))
		item = self.s3WellboreIntervals_tableWidget.horizontalHeaderItem(4)
		item.setText(_translate("InputWindow", "bottom MD", None))
		item = self.s3WellboreIntervals_tableWidget.horizontalHeaderItem(5)
		item.setText(_translate("InputWindow", "Friction factor", None))
		self.groupBox_5.setTitle(_translate("InputWindow", "Wellbore Inner Stages (from top down) ", None))
		item = self.s3PipeCentralizationStage_tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "Pipes (from top down)", None))
		item = self.s3PipeCentralizationStage_tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("InputWindow", "Length", None))
		item = self.s3PipeCentralizationStage_tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("InputWindow", "MD", None))
		self.s3UpdateAxialF_pushButton.setText(_translate("InputWindow", "UPDATE INNER STAGES", None))
		self.s3ODID_pushButton.setText(_translate("InputWindow", "OD, ID -> Wt", None))
		self.s3ODWt_pushButton.setText(_translate("InputWindow", "OD, Wt -> ID", None))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(0)
		item.setText(_translate("InputWindow", "Pipe", None))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(1)
		item.setText(_translate("InputWindow", "Adjusted Wt                                                 ", None))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(2)
		item.setText(_translate("InputWindow", "OD", None))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(3)
		item.setText(_translate("InputWindow", "ID", None))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(4)
		item.setText(_translate("InputWindow", "Tensile limit", None))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(5)
		item.setText(_translate("InputWindow", "Torsional limit", None))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(6)
		item.setText(_translate("InputWindow", "Density", None))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(7)
		item.setText(_translate("InputWindow", "E", None))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(8)
		item.setText(_translate("InputWindow", "FF reduction", None))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(9)
		item.setText(_translate("InputWindow", "Inner mud density", None))
		item = self.s3PipeProperties_tableWidget.verticalHeaderItem(10)
		item.setText(_translate("InputWindow", "Outer mud density", None))
		self.s3InnerStageToolkit_tabWidget.setTabText(self.s3InnerStageToolkit_tabWidget.indexOf(self.tab_10), _translate("InputWindow", "Pipe", None))
		self.s3BowSpringCentralizer_radioButton_A.setText(_translate("InputWindow", "Bow Spring", None))
		self.s3RigidCentralizer_radioButton_A.setText(_translate("InputWindow", "Rigid", None))
		self.s3Location_label_A.setText(_translate("InputWindow", "Location:", None))
		item = self.s3CentralizerRunningForce_tableWidget_A.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "Hole ID", None))
		item = self.s3CentralizerRunningForce_tableWidget_A.horizontalHeaderItem(1)
		item.setText(_translate("InputWindow", "Running F.", None))
		self.s3CentralizerDB_pushButton_A.setText(_translate("InputWindow", "Centralizer DB...", None))
		item = self.s3CentralizerLocation_tableWidget_A.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "MD", None))
		self.ABC_tabWidget.setTabText(self.ABC_tabWidget.indexOf(self.tab_A), _translate("InputWindow", "A", None))
		item = self.s3CentralizerLocation_tableWidget_B.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "MD", None))
		item = self.s3CentralizerRunningForce_tableWidget_B.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "Hole ID", None))
		item = self.s3CentralizerRunningForce_tableWidget_B.horizontalHeaderItem(1)
		item.setText(_translate("InputWindow", "Running F.", None))
		self.s3RigidCentralizer_radioButton_B.setText(_translate("InputWindow", "Rigid", None))
		self.s3CentralizerDB_pushButton_B.setText(_translate("InputWindow", "Centralizer DB...", None))
		self.s3BowSpringCentralizer_radioButton_B.setText(_translate("InputWindow", "Bow Spring", None))
		self.s3Location_label_B.setText(_translate("InputWindow", "Location:", None))
		self.s3NoneCentralizer_radioButton_B.setText(_translate("InputWindow", "None", None))
		self.ABC_tabWidget.setTabText(self.ABC_tabWidget.indexOf(self.tab_B), _translate("InputWindow", "B", None))
		self.s3BowSpringCentralizer_radioButton_C.setText(_translate("InputWindow", "Bow Spring", None))
		self.s3RigidCentralizer_radioButton_C.setText(_translate("InputWindow", "Rigid", None))
		self.s3Location_label_C.setText(_translate("InputWindow", "Location:", None))
		item = self.s3CentralizerRunningForce_tableWidget_C.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "Hole ID", None))
		item = self.s3CentralizerRunningForce_tableWidget_C.horizontalHeaderItem(1)
		item.setText(_translate("InputWindow", "Running F.", None))
		self.s3CentralizerDB_pushButton_C.setText(_translate("InputWindow", "Centralizer DB...", None))
		item = self.s3CentralizerLocation_tableWidget_C.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "MD", None))
		self.s3NoneCentralizer_radioButton_C.setText(_translate("InputWindow", "None", None))
		self.ABC_tabWidget.setTabText(self.ABC_tabWidget.indexOf(self.tab_C), _translate("InputWindow", "C", None))
		self.s3InnerStageToolkit_tabWidget.setTabText(self.s3InnerStageToolkit_tabWidget.indexOf(self.tab_11), _translate("InputWindow", "Centralization", None))
		self.s3SpecifyCentralization_pushButton.setText(_translate("InputWindow", "MANAGE LOCATIONS...", None))
		self.Menu.setTabText(self.Menu.indexOf(self.tab_4), _translate("InputWindow", "Wellbore", None))
		self.groupBox_7.setTitle(_translate("InputWindow", "Settings and results", None))
		self.s4Settings_tableWidget.setSortingEnabled(False)
		item = self.s4Settings_tableWidget.verticalHeaderItem(0)
		item.setText(_translate("InputWindow", "Traveling Assembly Weight (TAW)", None))
		item = self.s4Settings_tableWidget.verticalHeaderItem(1)
		item.setText(_translate("InputWindow", "Pipe end drag or WOB", None))
		item = self.s4Settings_tableWidget.verticalHeaderItem(2)
		item.setText(_translate("InputWindow", "Pipe end torque or TOB", None))
		item = self.s4Settings_tableWidget.verticalHeaderItem(3)
		item.setText(_translate("InputWindow", "Tripping speed", None))
		item = self.s4Settings_tableWidget.verticalHeaderItem(4)
		item.setText(_translate("InputWindow", "Rotational speed", None))
		item = self.s4TorqueDragSideforce_tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("InputWindow", "MD", None))
		item = self.s4TorqueDragSideforce_tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("InputWindow", "Inc", None))
		item = self.s4TorqueDragSideforce_tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("InputWindow", "Torque hoisting", None))
		item = self.s4TorqueDragSideforce_tableWidget.horizontalHeaderItem(3)
		item.setText(_translate("InputWindow", "Torque static", None))
		item = self.s4TorqueDragSideforce_tableWidget.horizontalHeaderItem(4)
		item.setText(_translate("InputWindow", "Torque lowering", None))
		item = self.s4TorqueDragSideforce_tableWidget.horizontalHeaderItem(5)
		item.setText(_translate("InputWindow", "Drag hoisting", None))
		item = self.s4TorqueDragSideforce_tableWidget.horizontalHeaderItem(6)
		item.setText(_translate("InputWindow", "Drag static", None))
		item = self.s4TorqueDragSideforce_tableWidget.horizontalHeaderItem(7)
		item.setText(_translate("InputWindow", "Drag lowering", None))
		item = self.s4TorqueDragSideforce_tableWidget.horizontalHeaderItem(8)
		item.setText(_translate("InputWindow", "Side Force", None))
		self.s4Calculate_pushButton.setText(_translate("InputWindow", "Calculate", None))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_12), _translate("InputWindow", "Drag", None))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_13), _translate("InputWindow", "Torque", None))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_14), _translate("InputWindow", "Side Force", None))
		self.Menu.setTabText(self.Menu.indexOf(self.tab_2), _translate("InputWindow", "T + D + SF", None))
		self.iw_toolBar.setWindowTitle(_translate("InputWindow", "toolBar", None))
		self.actionNew.setText(_translate("InputWindow", "New", None))
		self.actionNew.setShortcut(_translate("InputWindow", "Ctrl+N", None))
		self.actionOpen.setText(_translate("InputWindow", "Open...", None))
		self.actionOpen.setShortcut(_translate("InputWindow", "Ctrl+O", None))
		self.actionSave.setText(_translate("InputWindow", "Save", None))
		self.actionSave.setShortcut(_translate("InputWindow", "Ctrl+S", None))
		self.actionSave_As.setText(_translate("InputWindow", "Save As...", None))
		self.actionPrint.setText(_translate("InputWindow", "Print Preview...", None))
		self.actionPrint_2.setText(_translate("InputWindow", "Print..", None))
		self.actionPrint_2.setShortcut(_translate("InputWindow", "Ctrl+P", None))
		self.actionExit.setText(_translate("InputWindow", "Exit", None))
		self.actionCopy_Selection.setText(_translate("InputWindow", "Copy Selection", None))
		self.actionPaste.setText(_translate("InputWindow", "Paste", None))
		self.actionOne_Span_Analysis.setText(_translate("InputWindow", "One Span Analysis...", None))
		self.actionUnit_Setting.setText(_translate("InputWindow", "Unit Setting...", None))
		self.actionUnit_Conversion.setText(_translate("InputWindow", "Unit Conversion...", None))
		self.actionCalculator.setText(_translate("InputWindow", "Calculator...", None))
		self.actionNotepad.setText(_translate("InputWindow", "Notepad...", None))
		self.actionAbout.setText(_translate("InputWindow", "About...", None))
		self.actionAbbreviation.setText(_translate("InputWindow", "Abbreviation...", None))
		self.actionDisclaimer.setText(_translate("InputWindow", "Disclaimer...", None))
		self.actionStar_Calculation.setText(_translate("InputWindow", "Star Calculation", None))
		self.actionStar_Calculation.setShortcut(_translate("InputWindow", "F5", None))

from matplotlibwidget import Matplotlib3DWidget, MatplotlibWidget
