# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LocationSetup_Vst.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LocationSetup(object):
	def setupUi(self, LocationSetup):
		LocationSetup.setObjectName("LocationSetup")
		LocationSetup.resize(1441, 636)
		LocationSetup.setWindowOpacity(1.0)
		self.lsCaliperMap_graphicsView = MatplotlibWidget(LocationSetup)
		self.lsCaliperMap_graphicsView.setGeometry(QtCore.QRect(40, 40, 300, 500))
		self.lsCaliperMap_graphicsView.setObjectName("lsCaliperMap_graphicsView")
		self.lsCentralizerLocations_tableWidget = QtWidgets.QTableWidget(LocationSetup)
		self.lsCentralizerLocations_tableWidget.setGeometry(QtCore.QRect(880, 40, 541, 500))
		self.lsCentralizerLocations_tableWidget.setRowCount(1000)
		self.lsCentralizerLocations_tableWidget.setColumnCount(5)
		self.lsCentralizerLocations_tableWidget.setObjectName("lsCentralizerLocations_tableWidget")
		item = QtWidgets.QTableWidgetItem()
		self.lsCentralizerLocations_tableWidget.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.lsCentralizerLocations_tableWidget.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.lsCentralizerLocations_tableWidget.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.lsCentralizerLocations_tableWidget.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.lsCentralizerLocations_tableWidget.setHorizontalHeaderItem(4, item)
		self.lsCentralizerLocations_tableWidget.horizontalHeader().setDefaultSectionSize(110)
		self.lsCentralizerLocations_tableWidget.horizontalHeader().setMinimumSectionSize(30)
		self.lsAccept_pushButton = QtWidgets.QPushButton(LocationSetup)
		self.lsAccept_pushButton.setGeometry(QtCore.QRect(1310, 560, 101, 41))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(True)
		font.setWeight(75)
		self.lsAccept_pushButton.setFont(font)
		self.lsAccept_pushButton.setObjectName("lsAccept_pushButton")
		self.tabWidget = QtWidgets.QTabWidget(LocationSetup)
		self.tabWidget.setGeometry(QtCore.QRect(360, 40, 500, 520))
		font = QtGui.QFont()
		font.setPointSize(10)
		font.setBold(False)
		font.setWeight(50)
		self.tabWidget.setFont(font)
		self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
		self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
		self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
		self.tabWidget.setDocumentMode(True)
		self.tabWidget.setTabsClosable(False)
		self.tabWidget.setObjectName("tabWidget")
		self.tab_3 = QtWidgets.QWidget()
		self.tab_3.setObjectName("tab_3")
		self.lsSideForces_graphicsView = MatplotlibWidget(self.tab_3)
		self.lsSideForces_graphicsView.setGeometry(QtCore.QRect(0, 0, 500, 500))
		self.lsSideForces_graphicsView.setObjectName("lsSideForces_graphicsView")
		self.tabWidget.addTab(self.tab_3, "")
		self.tab = QtWidgets.QWidget()
		self.tab.setObjectName("tab")
		self.lsWellbore3D_graphicsView = Matplotlib3DWidget(self.tab)
		self.lsWellbore3D_graphicsView.setGeometry(QtCore.QRect(0, 0, 500, 500))
		self.lsWellbore3D_graphicsView.setObjectName("lsWellbore3D_graphicsView")
		self.tabWidget.addTab(self.tab, "")
		self.tab_2 = QtWidgets.QWidget()
		self.tab_2.setObjectName("tab_2")
		self.lsSOVisualization_graphicsView = MatplotlibWidget(self.tab_2)
		self.lsSOVisualization_graphicsView.setGeometry(QtCore.QRect(0, 0, 500, 500))
		self.lsSOVisualization_graphicsView.setObjectName("lsSOVisualization_graphicsView")
		self.tabWidget.addTab(self.tab_2, "")
		self.lsMeanSOatC_label = QtWidgets.QLabel(LocationSetup)
		self.lsMeanSOatC_label.setGeometry(QtCore.QRect(880, 560, 331, 21))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.lsMeanSOatC_label.setFont(font)
		self.lsMeanSOatC_label.setObjectName("lsMeanSOatC_label")
		self.lsMeanSOatM_label = QtWidgets.QLabel(LocationSetup)
		self.lsMeanSOatM_label.setGeometry(QtCore.QRect(880, 590, 331, 21))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.lsMeanSOatM_label.setFont(font)
		self.lsMeanSOatM_label.setObjectName("lsMeanSOatM_label")

		self.retranslateUi(LocationSetup)
		self.tabWidget.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(LocationSetup)

	def retranslateUi(self, LocationSetup):
		_translate = QtCore.QCoreApplication.translate
		LocationSetup.setWindowTitle(_translate("LocationSetup", "Centralizers Location Setup"))
		item = self.lsCentralizerLocations_tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("LocationSetup", "MD"))
		item = self.lsCentralizerLocations_tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("LocationSetup", "Inc"))
		item = self.lsCentralizerLocations_tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("LocationSetup", "SO at\\ncentralizer"))
		item = self.lsCentralizerLocations_tableWidget.horizontalHeaderItem(3)
		item.setText(_translate("LocationSetup", "SO at\\nmidspan"))
		item = self.lsCentralizerLocations_tableWidget.horizontalHeaderItem(4)
		item.setText(_translate("LocationSetup", "Stage"))
		self.lsAccept_pushButton.setText(_translate("LocationSetup", "DONE"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("LocationSetup", "Side Forces"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("LocationSetup", "3D View"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("LocationSetup", "SO Visualization"))
		self.lsMeanSOatC_label.setText(_translate("LocationSetup", "Mean SO at centralizers: "))
		self.lsMeanSOatM_label.setText(_translate("LocationSetup", "Mean SO at midspan:"))

from matplotlibwidget import Matplotlib3DWidget, MatplotlibWidget
