# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OutputWindow_Vst.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OutputWindow(object):
	def setupUi(self, OutputWindow):
		OutputWindow.setObjectName("OutputWindow")
		OutputWindow.resize(1321, 872)
		self.centralwidget = QtWidgets.QWidget(OutputWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
		self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1321, 791))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.tabWidget.setFont(font)
		self.tabWidget.setObjectName("tabWidget")
		self.tab = QtWidgets.QWidget()
		self.tab.setObjectName("tab")
		self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
		self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 1321, 761))
		self.tabWidget_2.setObjectName("tabWidget_2")
		self.tab_3 = QtWidgets.QWidget()
		self.tab_3.setObjectName("tab_3")
		self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_3)
		self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 1321, 731))
		self.tabWidget_3.setObjectName("tabWidget_3")
		self.tab_9 = QtWidgets.QWidget()
		self.tab_9.setObjectName("tab_9")
		self.owMechanicalState_graphicsView = MatplotlibWidget(self.tab_9)
		self.owMechanicalState_graphicsView.setGeometry(QtCore.QRect(0, 0, 281, 697))
		self.owMechanicalState_graphicsView.setObjectName("owMechanicalState_graphicsView")
		self.label = QtWidgets.QLabel(self.tab_9)
		self.label.setGeometry(QtCore.QRect(290, 10, 91, 21))
		self.label.setObjectName("label")
		self.owSummary_tableWidget = QtWidgets.QTableWidget(self.tab_9)
		self.owSummary_tableWidget.setGeometry(QtCore.QRect(290, 40, 1021, 657))
		self.owSummary_tableWidget.setObjectName("owSummary_tableWidget")
		self.owSummary_tableWidget.setColumnCount(0)
		self.owSummary_tableWidget.setRowCount(0)
		self.label_2 = QtWidgets.QLabel(self.tab_9)
		self.label_2.setGeometry(QtCore.QRect(420, 10, 121, 20))
		self.label_2.setObjectName("label_2")
		self.label_3 = QtWidgets.QLabel(self.tab_9)
		self.label_3.setGeometry(QtCore.QRect(550, 10, 121, 20))
		self.label_3.setObjectName("label_3")
		self.label_4 = QtWidgets.QLabel(self.tab_9)
		self.label_4.setGeometry(QtCore.QRect(690, 10, 121, 20))
		self.label_4.setObjectName("label_4")
		self.label_5 = QtWidgets.QLabel(self.tab_9)
		self.label_5.setGeometry(QtCore.QRect(836, 10, 121, 20))
		self.label_5.setObjectName("label_5")
		self.tabWidget_3.addTab(self.tab_9, "")
		self.tab_10 = QtWidgets.QWidget()
		self.tab_10.setObjectName("tab_10")
		self.label_6 = QtWidgets.QLabel(self.tab_10)
		self.label_6.setGeometry(QtCore.QRect(556, 10, 121, 20))
		self.label_6.setObjectName("label_6")
		self.label_7 = QtWidgets.QLabel(self.tab_10)
		self.label_7.setGeometry(QtCore.QRect(10, 10, 91, 21))
		self.label_7.setObjectName("label_7")
		self.label_8 = QtWidgets.QLabel(self.tab_10)
		self.label_8.setGeometry(QtCore.QRect(410, 10, 121, 20))
		self.label_8.setObjectName("label_8")
		self.label_9 = QtWidgets.QLabel(self.tab_10)
		self.label_9.setGeometry(QtCore.QRect(140, 10, 121, 20))
		self.label_9.setObjectName("label_9")
		self.label_10 = QtWidgets.QLabel(self.tab_10)
		self.label_10.setGeometry(QtCore.QRect(270, 10, 121, 20))
		self.label_10.setObjectName("label_10")
		self.owCentralizerCalculationDown_pushButton = QtWidgets.QPushButton(self.tab_10)
		self.owCentralizerCalculationDown_pushButton.setGeometry(QtCore.QRect(1278, 70, 31, 31))
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("iconos/arrow-down-double.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.owCentralizerCalculationDown_pushButton.setIcon(icon)
		self.owCentralizerCalculationDown_pushButton.setObjectName("owCentralizerCalculationDown_pushButton")
		self.owCentralizerCalculationUp_pushButton = QtWidgets.QPushButton(self.tab_10)
		self.owCentralizerCalculationUp_pushButton.setGeometry(QtCore.QRect(1278, 33, 31, 31))
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap("iconos/arrow-up-double.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.owCentralizerCalculationUp_pushButton.setIcon(icon1)
		self.owCentralizerCalculationUp_pushButton.setObjectName("owCentralizerCalculationUp_pushButton")
		self.owCentralizerCalculation_tableWidget = QtWidgets.QTableWidget(self.tab_10)
		self.owCentralizerCalculation_tableWidget.setGeometry(QtCore.QRect(0, 35, 1271, 661))
		self.owCentralizerCalculation_tableWidget.setObjectName("owCentralizerCalculation_tableWidget")
		self.owCentralizerCalculation_tableWidget.setColumnCount(0)
		self.owCentralizerCalculation_tableWidget.setRowCount(0)
		self.tabWidget_3.addTab(self.tab_10, "")
		self.tabWidget_2.addTab(self.tab_3, "")
		self.tab_4 = QtWidgets.QWidget()
		self.tab_4.setObjectName("tab_4")
		self.owSpacing_graphicsView = MatplotlibWidget(self.tab_4)
		self.owSpacing_graphicsView.setGeometry(QtCore.QRect(0, 0, 1311, 727))
		self.owSpacing_graphicsView.setObjectName("owSpacing_graphicsView")
		self.tabWidget_2.addTab(self.tab_4, "")
		self.tab_6 = QtWidgets.QWidget()
		self.tab_6.setObjectName("tab_6")
		self.owSideForce_graphicsView = MatplotlibWidget(self.tab_6)
		self.owSideForce_graphicsView.setGeometry(QtCore.QRect(0, 0, 1311, 727))
		self.owSideForce_graphicsView.setObjectName("owSideForce_graphicsView")
		self.tabWidget_2.addTab(self.tab_6, "")
		self.tab_5 = QtWidgets.QWidget()
		self.tab_5.setObjectName("tab_5")
		self.owStandoff_graphicsView = MatplotlibWidget(self.tab_5)
		self.owStandoff_graphicsView.setGeometry(QtCore.QRect(0, 0, 1311, 727))
		self.owStandoff_graphicsView.setObjectName("owStandoff_graphicsView")
		self.tabWidget_2.addTab(self.tab_5, "")
		self.tab_7 = QtWidgets.QWidget()
		self.tab_7.setObjectName("tab_7")
		self.owDogleg_graphicsView = MatplotlibWidget(self.tab_7)
		self.owDogleg_graphicsView.setGeometry(QtCore.QRect(0, 0, 1311, 727))
		self.owDogleg_graphicsView.setObjectName("owDogleg_graphicsView")
		self.tabWidget_2.addTab(self.tab_7, "")
		self.tab_8 = QtWidgets.QWidget()
		self.tab_8.setObjectName("tab_8")
		self.owSideForce2D_graphicsView = MatplotlibWidget(self.tab_8)
		self.owSideForce2D_graphicsView.setGeometry(QtCore.QRect(0, 0, 1311, 727))
		self.owSideForce2D_graphicsView.setObjectName("owSideForce2D_graphicsView")
		self.tabWidget_2.addTab(self.tab_8, "")
		self.tabWidget.addTab(self.tab, "")
		self.tab_2 = QtWidgets.QWidget()
		self.tab_2.setObjectName("tab_2")
		self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_2)
		self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 1321, 761))
		self.tabWidget_4.setObjectName("tabWidget_4")
		self.tab_11 = QtWidgets.QWidget()
		self.tab_11.setObjectName("tab_11")
		self.owTorqueAndDrag_tableWidget = QtWidgets.QTableWidget(self.tab_11)
		self.owTorqueAndDrag_tableWidget.setGeometry(QtCore.QRect(0, 0, 1271, 726))
		self.owTorqueAndDrag_tableWidget.setObjectName("owTorqueAndDrag_tableWidget")
		self.owTorqueAndDrag_tableWidget.setColumnCount(0)
		self.owTorqueAndDrag_tableWidget.setRowCount(0)
		self.owTorqueAndDragDown_pushButton = QtWidgets.QPushButton(self.tab_11)
		self.owTorqueAndDragDown_pushButton.setGeometry(QtCore.QRect(1278, 37, 31, 31))
		self.owTorqueAndDragDown_pushButton.setIcon(icon)
		self.owTorqueAndDragDown_pushButton.setObjectName("owTorqueAndDragDown_pushButton")
		self.owTorqueAndDragUp_pushButton = QtWidgets.QPushButton(self.tab_11)
		self.owTorqueAndDragUp_pushButton.setGeometry(QtCore.QRect(1278, 0, 31, 31))
		self.owTorqueAndDragUp_pushButton.setIcon(icon1)
		self.owTorqueAndDragUp_pushButton.setObjectName("owTorqueAndDragUp_pushButton")
		self.tabWidget_4.addTab(self.tab_11, "")
		self.tab_12 = QtWidgets.QWidget()
		self.tab_12.setObjectName("tab_12")
		self.owHookLoad_graphicsView = MatplotlibWidget(self.tab_12)
		self.owHookLoad_graphicsView.setGeometry(QtCore.QRect(0, 0, 1311, 727))
		self.owHookLoad_graphicsView.setObjectName("owHookLoad_graphicsView")
		self.tabWidget_4.addTab(self.tab_12, "")
		self.tab_13 = QtWidgets.QWidget()
		self.tab_13.setObjectName("tab_13")
		self.owSurfaceTorque_graphicsView = MatplotlibWidget(self.tab_13)
		self.owSurfaceTorque_graphicsView.setGeometry(QtCore.QRect(0, 0, 1311, 727))
		self.owSurfaceTorque_graphicsView.setObjectName("owSurfaceTorque_graphicsView")
		self.tabWidget_4.addTab(self.tab_13, "")
		self.tabWidget.addTab(self.tab_2, "")
		OutputWindow.setCentralWidget(self.centralwidget)
		self.iw_toolBar = QtWidgets.QToolBar(OutputWindow)
		self.iw_toolBar.setIconSize(QtCore.QSize(30, 30))
		self.iw_toolBar.setObjectName("iw_toolBar")
		OutputWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.iw_toolBar)
		self.menubar = QtWidgets.QMenuBar(OutputWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1321, 26))
		self.menubar.setObjectName("menubar")
		self.menuWindows = QtWidgets.QMenu(self.menubar)
		self.menuWindows.setObjectName("menuWindows")
		self.menuUtilities = QtWidgets.QMenu(self.menubar)
		self.menuUtilities.setObjectName("menuUtilities")
		self.menuHelp = QtWidgets.QMenu(self.menubar)
		self.menuHelp.setObjectName("menuHelp")
		self.menuFile = QtWidgets.QMenu(self.menubar)
		self.menuFile.setObjectName("menuFile")
		OutputWindow.setMenuBar(self.menubar)
		self.actionNew = QtWidgets.QAction(OutputWindow)
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap("iconos/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionNew.setIcon(icon2)
		self.actionNew.setObjectName("actionNew")
		self.actionOpen = QtWidgets.QAction(OutputWindow)
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap("iconos/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionOpen.setIcon(icon3)
		self.actionOpen.setObjectName("actionOpen")
		self.actionSave = QtWidgets.QAction(OutputWindow)
		icon4 = QtGui.QIcon()
		icon4.addPixmap(QtGui.QPixmap("iconos/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionSave.setIcon(icon4)
		self.actionSave.setObjectName("actionSave")
		self.actionSave_As = QtWidgets.QAction(OutputWindow)
		self.actionSave_As.setObjectName("actionSave_As")
		self.actionPrint = QtWidgets.QAction(OutputWindow)
		self.actionPrint.setObjectName("actionPrint")
		self.actionPrint_2 = QtWidgets.QAction(OutputWindow)
		icon5 = QtGui.QIcon()
		icon5.addPixmap(QtGui.QPixmap("iconos/document-print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionPrint_2.setIcon(icon5)
		self.actionPrint_2.setObjectName("actionPrint_2")
		self.actionExit = QtWidgets.QAction(OutputWindow)
		self.actionExit.setObjectName("actionExit")
		self.actionCopy_Selection = QtWidgets.QAction(OutputWindow)
		self.actionCopy_Selection.setObjectName("actionCopy_Selection")
		self.actionPaste = QtWidgets.QAction(OutputWindow)
		self.actionPaste.setObjectName("actionPaste")
		self.actionOne_Span_Analysis = QtWidgets.QAction(OutputWindow)
		icon6 = QtGui.QIcon()
		icon6.addPixmap(QtGui.QPixmap("iconos/games-solve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionOne_Span_Analysis.setIcon(icon6)
		self.actionOne_Span_Analysis.setObjectName("actionOne_Span_Analysis")
		self.actionUnit_Setting = QtWidgets.QAction(OutputWindow)
		self.actionUnit_Setting.setObjectName("actionUnit_Setting")
		self.actionUnit_Conversion = QtWidgets.QAction(OutputWindow)
		icon7 = QtGui.QIcon()
		icon7.addPixmap(QtGui.QPixmap("iconos/measure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionUnit_Conversion.setIcon(icon7)
		self.actionUnit_Conversion.setObjectName("actionUnit_Conversion")
		self.actionCalculator = QtWidgets.QAction(OutputWindow)
		icon8 = QtGui.QIcon()
		icon8.addPixmap(QtGui.QPixmap("iconos/accessories-calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionCalculator.setIcon(icon8)
		self.actionCalculator.setObjectName("actionCalculator")
		self.actionNotepad = QtWidgets.QAction(OutputWindow)
		icon9 = QtGui.QIcon()
		icon9.addPixmap(QtGui.QPixmap("iconos/story-editor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionNotepad.setIcon(icon9)
		self.actionNotepad.setObjectName("actionNotepad")
		self.actionAbout = QtWidgets.QAction(OutputWindow)
		icon10 = QtGui.QIcon()
		icon10.addPixmap(QtGui.QPixmap("iconos/system-help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionAbout.setIcon(icon10)
		self.actionAbout.setObjectName("actionAbout")
		self.actionAbbreviation = QtWidgets.QAction(OutputWindow)
		self.actionAbbreviation.setObjectName("actionAbbreviation")
		self.actionDisclaimer = QtWidgets.QAction(OutputWindow)
		self.actionDisclaimer.setObjectName("actionDisclaimer")
		self.actionStar_Calculation = QtWidgets.QAction(OutputWindow)
		icon11 = QtGui.QIcon()
		icon11.addPixmap(QtGui.QPixmap("iconos/arrow-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionStar_Calculation.setIcon(icon11)
		self.actionStar_Calculation.setObjectName("actionStar_Calculation")
		self.actionReturn_to_Input_Window = QtWidgets.QAction(OutputWindow)
		self.actionReturn_to_Input_Window.setObjectName("actionReturn_to_Input_Window")
		self.actionPrint_All = QtWidgets.QAction(OutputWindow)
		self.actionPrint_All.setIcon(icon5)
		self.actionPrint_All.setObjectName("actionPrint_All")
		self.actionPrint_Summary_Only = QtWidgets.QAction(OutputWindow)
		self.actionPrint_Summary_Only.setObjectName("actionPrint_Summary_Only")
		self.actionGenerate_Report = QtWidgets.QAction(OutputWindow)
		self.actionGenerate_Report.setObjectName("actionGenerate_Report")
		self.actionStandoff_Profile = QtWidgets.QAction(OutputWindow)
		self.actionStandoff_Profile.setObjectName("actionStandoff_Profile")
		self.action3D_Wellpath = QtWidgets.QAction(OutputWindow)
		self.action3D_Wellpath.setObjectName("action3D_Wellpath")
		self.actionCentralizer = QtWidgets.QAction(OutputWindow)
		self.actionCentralizer.setObjectName("actionCentralizer")
		self.actionGraph_Settings = QtWidgets.QAction(OutputWindow)
		self.actionGraph_Settings.setObjectName("actionGraph_Settings")
		self.iw_toolBar.addAction(self.actionPrint_2)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionStar_Calculation)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionOne_Span_Analysis)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionUnit_Conversion)
		self.iw_toolBar.addAction(self.actionCalculator)
		self.iw_toolBar.addAction(self.actionNotepad)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionAbout)
		self.menuWindows.addAction(self.actionOne_Span_Analysis)
		self.menuWindows.addAction(self.action3D_Wellpath)
		self.menuWindows.addAction(self.actionCentralizer)
		self.menuUtilities.addAction(self.actionUnit_Conversion)
		self.menuUtilities.addAction(self.actionCalculator)
		self.menuUtilities.addAction(self.actionNotepad)
		self.menuHelp.addAction(self.actionAbout)
		self.menuHelp.addAction(self.actionAbbreviation)
		self.menuHelp.addSeparator()
		self.menuHelp.addAction(self.actionDisclaimer)
		self.menuFile.addAction(self.actionGenerate_Report)
		self.menuFile.addAction(self.actionGraph_Settings)
		self.menuFile.addSeparator()
		self.menuFile.addAction(self.actionPrint_All)
		self.menuFile.addSeparator()
		self.menuFile.addAction(self.actionReturn_to_Input_Window)
		self.menubar.addAction(self.menuFile.menuAction())
		self.menubar.addAction(self.menuWindows.menuAction())
		self.menubar.addAction(self.menuUtilities.menuAction())
		self.menubar.addAction(self.menuHelp.menuAction())

		self.retranslateUi(OutputWindow)
		self.tabWidget.setCurrentIndex(1)
		self.tabWidget_2.setCurrentIndex(0)
		self.tabWidget_3.setCurrentIndex(0)
		self.tabWidget_4.setCurrentIndex(0)
		self.actionExit.triggered.connect(OutputWindow.close)
		QtCore.QMetaObject.connectSlotsByName(OutputWindow)

	def retranslateUi(self, OutputWindow):
		_translate = QtCore.QCoreApplication.translate
		OutputWindow.setWindowTitle(_translate("OutputWindow", "Central Software - Output Window"))
		self.label.setText(_translate("OutputWindow", "Table color:"))
		self.label_2.setText(_translate("OutputWindow", "No Centralizer"))
		self.label_3.setText(_translate("OutputWindow", "Specify spacing"))
		self.label_4.setText(_translate("OutputWindow", "Specify standoff"))
		self.label_5.setText(_translate("OutputWindow", "Specify location"))
		self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("OutputWindow", "Summary"))
		self.label_6.setText(_translate("OutputWindow", "Specify location"))
		self.label_7.setText(_translate("OutputWindow", "Table color:"))
		self.label_8.setText(_translate("OutputWindow", "Specify standoff"))
		self.label_9.setText(_translate("OutputWindow", "No Centralizer"))
		self.label_10.setText(_translate("OutputWindow", "Specify spacing"))
		self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("OutputWindow", "Centralizer Calculation"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("OutputWindow", "Tables"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("OutputWindow", "Spacing"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("OutputWindow", "Side Force"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("OutputWindow", "Standoff (%)"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("OutputWindow", "Dogleg"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("OutputWindow", "Side Force 2D"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("OutputWindow", "Centralizer"))
		self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("OutputWindow", "Table"))
		self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("OutputWindow", "Hook Load"))
		self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), _translate("OutputWindow", "Surface Torque"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("OutputWindow", "Torque and Drag"))
		self.iw_toolBar.setWindowTitle(_translate("OutputWindow", "toolBar"))
		self.menuWindows.setTitle(_translate("OutputWindow", "Windows"))
		self.menuUtilities.setTitle(_translate("OutputWindow", "Utilities"))
		self.menuHelp.setTitle(_translate("OutputWindow", "Help"))
		self.menuFile.setTitle(_translate("OutputWindow", "File"))
		self.actionNew.setText(_translate("OutputWindow", "New"))
		self.actionNew.setShortcut(_translate("OutputWindow", "Ctrl+N"))
		self.actionOpen.setText(_translate("OutputWindow", "Open..."))
		self.actionOpen.setShortcut(_translate("OutputWindow", "Ctrl+O"))
		self.actionSave.setText(_translate("OutputWindow", "Save"))
		self.actionSave.setShortcut(_translate("OutputWindow", "Ctrl+S"))
		self.actionSave_As.setText(_translate("OutputWindow", "Save As..."))
		self.actionPrint.setText(_translate("OutputWindow", "Print Preview..."))
		self.actionPrint_2.setText(_translate("OutputWindow", "Print.."))
		self.actionPrint_2.setShortcut(_translate("OutputWindow", "Ctrl+P"))
		self.actionExit.setText(_translate("OutputWindow", "Exit"))
		self.actionCopy_Selection.setText(_translate("OutputWindow", "Copy Selection"))
		self.actionPaste.setText(_translate("OutputWindow", "Paste"))
		self.actionOne_Span_Analysis.setText(_translate("OutputWindow", "One Span Analysis..."))
		self.actionUnit_Setting.setText(_translate("OutputWindow", "Unit Setting..."))
		self.actionUnit_Conversion.setText(_translate("OutputWindow", "Unit Conversion..."))
		self.actionCalculator.setText(_translate("OutputWindow", "Calculator..."))
		self.actionNotepad.setText(_translate("OutputWindow", "Notepad..."))
		self.actionAbout.setText(_translate("OutputWindow", "About..."))
		self.actionAbbreviation.setText(_translate("OutputWindow", "Abbreviation..."))
		self.actionDisclaimer.setText(_translate("OutputWindow", "Disclaimer..."))
		self.actionStar_Calculation.setText(_translate("OutputWindow", "Star Calculation"))
		self.actionStar_Calculation.setShortcut(_translate("OutputWindow", "F5"))
		self.actionReturn_to_Input_Window.setText(_translate("OutputWindow", "Return to Input Window"))
		self.actionPrint_All.setText(_translate("OutputWindow", "Print Report ..."))
		self.actionPrint_Summary_Only.setText(_translate("OutputWindow", "Print Summary Only ..."))
		self.actionGenerate_Report.setText(_translate("OutputWindow", "Generate Report ..."))
		self.actionStandoff_Profile.setText(_translate("OutputWindow", "Standoff Profile ..."))
		self.action3D_Wellpath.setText(_translate("OutputWindow", "3D Parameter Visualization ..."))
		self.actionCentralizer.setText(_translate("OutputWindow", "Centralizer Spacing Sensitivity Analysis ..."))
		self.actionGraph_Settings.setText(_translate("OutputWindow", "Graph Settings ..."))

from matplotlibwidget import MatplotlibWidget
