# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OutputWindow_Vst.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
	_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
	def _fromUtf8(s):
		return s

try:
	_encoding = QtGui.QApplication.UnicodeUTF8
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig)

class Ui_OutputWindow(object):
	def setupUi(self, OutputWindow):
		OutputWindow.setObjectName(_fromUtf8("OutputWindow"))
		OutputWindow.resize(1321, 872)
		self.centralwidget = QtGui.QWidget(OutputWindow)
		self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
		self.tabWidget = QtGui.QTabWidget(self.centralwidget)
		self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1321, 791))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.tabWidget.setFont(font)
		self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
		self.tab = QtGui.QWidget()
		self.tab.setObjectName(_fromUtf8("tab"))
		self.tabWidget_2 = QtGui.QTabWidget(self.tab)
		self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 1321, 761))
		self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
		self.tab_3 = QtGui.QWidget()
		self.tab_3.setObjectName(_fromUtf8("tab_3"))
		self.tabWidget_3 = QtGui.QTabWidget(self.tab_3)
		self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 1321, 731))
		self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
		self.tab_9 = QtGui.QWidget()
		self.tab_9.setObjectName(_fromUtf8("tab_9"))
		self.owMechanicalState_graphicsView = MatplotlibWidget(self.tab_9)
		self.owMechanicalState_graphicsView.setGeometry(QtCore.QRect(0, 0, 281, 697))
		self.owMechanicalState_graphicsView.setObjectName(_fromUtf8("owMechanicalState_graphicsView"))
		self.label = QtGui.QLabel(self.tab_9)
		self.label.setGeometry(QtCore.QRect(290, 10, 91, 21))
		self.label.setObjectName(_fromUtf8("label"))
		self.owSummary_tableWidget = QtGui.QTableWidget(self.tab_9)
		self.owSummary_tableWidget.setGeometry(QtCore.QRect(290, 40, 1021, 657))
		self.owSummary_tableWidget.setObjectName(_fromUtf8("owSummary_tableWidget"))
		self.owSummary_tableWidget.setColumnCount(0)
		self.owSummary_tableWidget.setRowCount(0)
		self.label_2 = QtGui.QLabel(self.tab_9)
		self.label_2.setGeometry(QtCore.QRect(420, 10, 121, 20))
		self.label_2.setObjectName(_fromUtf8("label_2"))
		self.label_3 = QtGui.QLabel(self.tab_9)
		self.label_3.setGeometry(QtCore.QRect(550, 10, 121, 20))
		self.label_3.setObjectName(_fromUtf8("label_3"))
		self.label_4 = QtGui.QLabel(self.tab_9)
		self.label_4.setGeometry(QtCore.QRect(690, 10, 121, 20))
		self.label_4.setObjectName(_fromUtf8("label_4"))
		self.label_5 = QtGui.QLabel(self.tab_9)
		self.label_5.setGeometry(QtCore.QRect(836, 10, 121, 20))
		self.label_5.setObjectName(_fromUtf8("label_5"))
		self.tabWidget_3.addTab(self.tab_9, _fromUtf8(""))
		self.tab_10 = QtGui.QWidget()
		self.tab_10.setObjectName(_fromUtf8("tab_10"))
		self.label_6 = QtGui.QLabel(self.tab_10)
		self.label_6.setGeometry(QtCore.QRect(556, 10, 121, 20))
		self.label_6.setObjectName(_fromUtf8("label_6"))
		self.label_7 = QtGui.QLabel(self.tab_10)
		self.label_7.setGeometry(QtCore.QRect(10, 10, 91, 21))
		self.label_7.setObjectName(_fromUtf8("label_7"))
		self.label_8 = QtGui.QLabel(self.tab_10)
		self.label_8.setGeometry(QtCore.QRect(410, 10, 121, 20))
		self.label_8.setObjectName(_fromUtf8("label_8"))
		self.label_9 = QtGui.QLabel(self.tab_10)
		self.label_9.setGeometry(QtCore.QRect(140, 10, 121, 20))
		self.label_9.setObjectName(_fromUtf8("label_9"))
		self.label_10 = QtGui.QLabel(self.tab_10)
		self.label_10.setGeometry(QtCore.QRect(270, 10, 121, 20))
		self.label_10.setObjectName(_fromUtf8("label_10"))
		self.owCentralizerCalculationDown_pushButton = QtGui.QPushButton(self.tab_10)
		self.owCentralizerCalculationDown_pushButton.setGeometry(QtCore.QRect(1278, 70, 31, 31))
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/arrow-down-double.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.owCentralizerCalculationDown_pushButton.setIcon(icon)
		self.owCentralizerCalculationDown_pushButton.setObjectName(_fromUtf8("owCentralizerCalculationDown_pushButton"))
		self.owCentralizerCalculationUp_pushButton = QtGui.QPushButton(self.tab_10)
		self.owCentralizerCalculationUp_pushButton.setGeometry(QtCore.QRect(1278, 33, 31, 31))
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/arrow-up-double.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.owCentralizerCalculationUp_pushButton.setIcon(icon1)
		self.owCentralizerCalculationUp_pushButton.setObjectName(_fromUtf8("owCentralizerCalculationUp_pushButton"))
		self.owCentralizerCalculation_tableWidget = QtGui.QTableWidget(self.tab_10)
		self.owCentralizerCalculation_tableWidget.setGeometry(QtCore.QRect(0, 35, 1271, 661))
		self.owCentralizerCalculation_tableWidget.setObjectName(_fromUtf8("owCentralizerCalculation_tableWidget"))
		self.owCentralizerCalculation_tableWidget.setColumnCount(0)
		self.owCentralizerCalculation_tableWidget.setRowCount(0)
		self.tabWidget_3.addTab(self.tab_10, _fromUtf8(""))
		self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
		self.tab_4 = QtGui.QWidget()
		self.tab_4.setObjectName(_fromUtf8("tab_4"))
		self.owSpacing_graphicsView = MatplotlibWidget(self.tab_4)
		self.owSpacing_graphicsView.setGeometry(QtCore.QRect(0, 0, 1311, 727))
		self.owSpacing_graphicsView.setObjectName(_fromUtf8("owSpacing_graphicsView"))
		self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
		self.tab_6 = QtGui.QWidget()
		self.tab_6.setObjectName(_fromUtf8("tab_6"))
		self.owSideForce_graphicsView = MatplotlibWidget(self.tab_6)
		self.owSideForce_graphicsView.setGeometry(QtCore.QRect(0, 0, 1311, 727))
		self.owSideForce_graphicsView.setObjectName(_fromUtf8("owSideForce_graphicsView"))
		self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
		self.tab_5 = QtGui.QWidget()
		self.tab_5.setObjectName(_fromUtf8("tab_5"))
		self.owStandoff_graphicsView = MatplotlibWidget(self.tab_5)
		self.owStandoff_graphicsView.setGeometry(QtCore.QRect(0, 0, 1311, 727))
		self.owStandoff_graphicsView.setObjectName(_fromUtf8("owStandoff_graphicsView"))
		self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
		self.tab_7 = QtGui.QWidget()
		self.tab_7.setObjectName(_fromUtf8("tab_7"))
		self.owDogleg_graphicsView = MatplotlibWidget(self.tab_7)
		self.owDogleg_graphicsView.setGeometry(QtCore.QRect(0, 0, 1311, 727))
		self.owDogleg_graphicsView.setObjectName(_fromUtf8("owDogleg_graphicsView"))
		self.tabWidget_2.addTab(self.tab_7, _fromUtf8(""))
		self.tab_8 = QtGui.QWidget()
		self.tab_8.setObjectName(_fromUtf8("tab_8"))
		self.owSideForce2D_graphicsView = MatplotlibWidget(self.tab_8)
		self.owSideForce2D_graphicsView.setGeometry(QtCore.QRect(0, 0, 1311, 727))
		self.owSideForce2D_graphicsView.setObjectName(_fromUtf8("owSideForce2D_graphicsView"))
		self.tabWidget_2.addTab(self.tab_8, _fromUtf8(""))
		self.tabWidget.addTab(self.tab, _fromUtf8(""))
		self.tab_2 = QtGui.QWidget()
		self.tab_2.setObjectName(_fromUtf8("tab_2"))
		self.tabWidget_4 = QtGui.QTabWidget(self.tab_2)
		self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 1321, 761))
		self.tabWidget_4.setObjectName(_fromUtf8("tabWidget_4"))
		self.tab_11 = QtGui.QWidget()
		self.tab_11.setObjectName(_fromUtf8("tab_11"))
		self.owTorqueAndDrag_tableWidget = QtGui.QTableWidget(self.tab_11)
		self.owTorqueAndDrag_tableWidget.setGeometry(QtCore.QRect(0, 0, 1271, 726))
		self.owTorqueAndDrag_tableWidget.setObjectName(_fromUtf8("owTorqueAndDrag_tableWidget"))
		self.owTorqueAndDrag_tableWidget.setColumnCount(0)
		self.owTorqueAndDrag_tableWidget.setRowCount(0)
		self.owTorqueAndDragDown_pushButton = QtGui.QPushButton(self.tab_11)
		self.owTorqueAndDragDown_pushButton.setGeometry(QtCore.QRect(1278, 37, 31, 31))
		self.owTorqueAndDragDown_pushButton.setIcon(icon)
		self.owTorqueAndDragDown_pushButton.setObjectName(_fromUtf8("owTorqueAndDragDown_pushButton"))
		self.owTorqueAndDragUp_pushButton = QtGui.QPushButton(self.tab_11)
		self.owTorqueAndDragUp_pushButton.setGeometry(QtCore.QRect(1278, 0, 31, 31))
		self.owTorqueAndDragUp_pushButton.setIcon(icon1)
		self.owTorqueAndDragUp_pushButton.setObjectName(_fromUtf8("owTorqueAndDragUp_pushButton"))
		self.tabWidget_4.addTab(self.tab_11, _fromUtf8(""))
		self.tab_12 = QtGui.QWidget()
		self.tab_12.setObjectName(_fromUtf8("tab_12"))
		self.owHookLoad_graphicsView = MatplotlibWidget(self.tab_12)
		self.owHookLoad_graphicsView.setGeometry(QtCore.QRect(0, 0, 1311, 727))
		self.owHookLoad_graphicsView.setObjectName(_fromUtf8("owHookLoad_graphicsView"))
		self.tabWidget_4.addTab(self.tab_12, _fromUtf8(""))
		self.tab_13 = QtGui.QWidget()
		self.tab_13.setObjectName(_fromUtf8("tab_13"))
		self.owSurfaceTorque_graphicsView = MatplotlibWidget(self.tab_13)
		self.owSurfaceTorque_graphicsView.setGeometry(QtCore.QRect(0, 0, 1311, 727))
		self.owSurfaceTorque_graphicsView.setObjectName(_fromUtf8("owSurfaceTorque_graphicsView"))
		self.tabWidget_4.addTab(self.tab_13, _fromUtf8(""))
		self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
		OutputWindow.setCentralWidget(self.centralwidget)
		self.iw_toolBar = QtGui.QToolBar(OutputWindow)
		self.iw_toolBar.setIconSize(QtCore.QSize(30, 30))
		self.iw_toolBar.setObjectName(_fromUtf8("iw_toolBar"))
		OutputWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.iw_toolBar)
		self.menubar = QtGui.QMenuBar(OutputWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1321, 26))
		self.menubar.setObjectName(_fromUtf8("menubar"))
		self.menuWindows = QtGui.QMenu(self.menubar)
		self.menuWindows.setObjectName(_fromUtf8("menuWindows"))
		self.menuUtilities = QtGui.QMenu(self.menubar)
		self.menuUtilities.setObjectName(_fromUtf8("menuUtilities"))
		self.menuHelp = QtGui.QMenu(self.menubar)
		self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
		self.menuFile = QtGui.QMenu(self.menubar)
		self.menuFile.setObjectName(_fromUtf8("menuFile"))
		OutputWindow.setMenuBar(self.menubar)
		self.actionNew = QtGui.QAction(OutputWindow)
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/document-new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionNew.setIcon(icon2)
		self.actionNew.setObjectName(_fromUtf8("actionNew"))
		self.actionOpen = QtGui.QAction(OutputWindow)
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/document-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionOpen.setIcon(icon3)
		self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
		self.actionSave = QtGui.QAction(OutputWindow)
		icon4 = QtGui.QIcon()
		icon4.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/document-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionSave.setIcon(icon4)
		self.actionSave.setObjectName(_fromUtf8("actionSave"))
		self.actionSave_As = QtGui.QAction(OutputWindow)
		self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
		self.actionPrint = QtGui.QAction(OutputWindow)
		self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
		self.actionPrint_2 = QtGui.QAction(OutputWindow)
		icon5 = QtGui.QIcon()
		icon5.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/document-print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionPrint_2.setIcon(icon5)
		self.actionPrint_2.setObjectName(_fromUtf8("actionPrint_2"))
		self.actionExit = QtGui.QAction(OutputWindow)
		self.actionExit.setObjectName(_fromUtf8("actionExit"))
		self.actionCopy_Selection = QtGui.QAction(OutputWindow)
		self.actionCopy_Selection.setObjectName(_fromUtf8("actionCopy_Selection"))
		self.actionPaste = QtGui.QAction(OutputWindow)
		self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
		self.actionOne_Span_Analysis = QtGui.QAction(OutputWindow)
		icon6 = QtGui.QIcon()
		icon6.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/games-solve.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionOne_Span_Analysis.setIcon(icon6)
		self.actionOne_Span_Analysis.setObjectName(_fromUtf8("actionOne_Span_Analysis"))
		self.actionUnit_Setting = QtGui.QAction(OutputWindow)
		self.actionUnit_Setting.setObjectName(_fromUtf8("actionUnit_Setting"))
		self.actionUnit_Conversion = QtGui.QAction(OutputWindow)
		icon7 = QtGui.QIcon()
		icon7.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/measure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionUnit_Conversion.setIcon(icon7)
		self.actionUnit_Conversion.setObjectName(_fromUtf8("actionUnit_Conversion"))
		self.actionCalculator = QtGui.QAction(OutputWindow)
		icon8 = QtGui.QIcon()
		icon8.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/accessories-calculator.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionCalculator.setIcon(icon8)
		self.actionCalculator.setObjectName(_fromUtf8("actionCalculator"))
		self.actionNotepad = QtGui.QAction(OutputWindow)
		icon9 = QtGui.QIcon()
		icon9.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/story-editor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionNotepad.setIcon(icon9)
		self.actionNotepad.setObjectName(_fromUtf8("actionNotepad"))
		self.actionAbout = QtGui.QAction(OutputWindow)
		icon10 = QtGui.QIcon()
		icon10.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/system-help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionAbout.setIcon(icon10)
		self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
		self.actionAbbreviation = QtGui.QAction(OutputWindow)
		self.actionAbbreviation.setObjectName(_fromUtf8("actionAbbreviation"))
		self.actionDisclaimer = QtGui.QAction(OutputWindow)
		self.actionDisclaimer.setObjectName(_fromUtf8("actionDisclaimer"))
		self.actionStar_Calculation = QtGui.QAction(OutputWindow)
		icon11 = QtGui.QIcon()
		icon11.addPixmap(QtGui.QPixmap(_fromUtf8("iconos/arrow-left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionStar_Calculation.setIcon(icon11)
		self.actionStar_Calculation.setObjectName(_fromUtf8("actionStar_Calculation"))
		self.actionReturn_to_Input_Window = QtGui.QAction(OutputWindow)
		self.actionReturn_to_Input_Window.setObjectName(_fromUtf8("actionReturn_to_Input_Window"))
		self.actionPrint_All = QtGui.QAction(OutputWindow)
		self.actionPrint_All.setIcon(icon5)
		self.actionPrint_All.setObjectName(_fromUtf8("actionPrint_All"))
		self.actionPrint_Summary_Only = QtGui.QAction(OutputWindow)
		self.actionPrint_Summary_Only.setObjectName(_fromUtf8("actionPrint_Summary_Only"))
		self.actionGenerate_Report = QtGui.QAction(OutputWindow)
		self.actionGenerate_Report.setObjectName(_fromUtf8("actionGenerate_Report"))
		self.actionStandoff_Profile = QtGui.QAction(OutputWindow)
		self.actionStandoff_Profile.setObjectName(_fromUtf8("actionStandoff_Profile"))
		self.action3D_Wellpath = QtGui.QAction(OutputWindow)
		self.action3D_Wellpath.setObjectName(_fromUtf8("action3D_Wellpath"))
		self.actionCentralizer = QtGui.QAction(OutputWindow)
		self.actionCentralizer.setObjectName(_fromUtf8("actionCentralizer"))
		self.actionGraph_Settings = QtGui.QAction(OutputWindow)
		self.actionGraph_Settings.setObjectName(_fromUtf8("actionGraph_Settings"))
		self.iw_toolBar.addAction(self.actionPrint_2)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionStar_Calculation)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionOne_Span_Analysis)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionUnit_Conversion)
		self.iw_toolBar.addAction(self.actionCalculator)
		self.iw_toolBar.addAction(self.actionNotepad)
		self.iw_toolBar.addSeparator()
		self.iw_toolBar.addAction(self.actionAbout)
		self.menuWindows.addAction(self.actionOne_Span_Analysis)
		self.menuWindows.addAction(self.action3D_Wellpath)
		self.menuWindows.addAction(self.actionCentralizer)
		self.menuUtilities.addAction(self.actionUnit_Conversion)
		self.menuUtilities.addAction(self.actionCalculator)
		self.menuUtilities.addAction(self.actionNotepad)
		self.menuHelp.addAction(self.actionAbout)
		self.menuHelp.addAction(self.actionAbbreviation)
		self.menuHelp.addSeparator()
		self.menuHelp.addAction(self.actionDisclaimer)
		self.menuFile.addAction(self.actionGenerate_Report)
		self.menuFile.addAction(self.actionGraph_Settings)
		self.menuFile.addSeparator()
		self.menuFile.addAction(self.actionPrint_All)
		self.menuFile.addSeparator()
		self.menuFile.addAction(self.actionReturn_to_Input_Window)
		self.menubar.addAction(self.menuFile.menuAction())
		self.menubar.addAction(self.menuWindows.menuAction())
		self.menubar.addAction(self.menuUtilities.menuAction())
		self.menubar.addAction(self.menuHelp.menuAction())

		self.retranslateUi(OutputWindow)
		self.tabWidget.setCurrentIndex(1)
		self.tabWidget_2.setCurrentIndex(0)
		self.tabWidget_3.setCurrentIndex(0)
		self.tabWidget_4.setCurrentIndex(0)
		QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), OutputWindow.close)
		QtCore.QMetaObject.connectSlotsByName(OutputWindow)

	def retranslateUi(self, OutputWindow):
		OutputWindow.setWindowTitle(_translate("OutputWindow", "Central Software - Output Window", None))
		self.label.setText(_translate("OutputWindow", "Table color:", None))
		self.label_2.setText(_translate("OutputWindow", "No Centralizer", None))
		self.label_3.setText(_translate("OutputWindow", "Specify spacing", None))
		self.label_4.setText(_translate("OutputWindow", "Specify standoff", None))
		self.label_5.setText(_translate("OutputWindow", "Specify location", None))
		self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("OutputWindow", "Summary", None))
		self.label_6.setText(_translate("OutputWindow", "Specify location", None))
		self.label_7.setText(_translate("OutputWindow", "Table color:", None))
		self.label_8.setText(_translate("OutputWindow", "Specify standoff", None))
		self.label_9.setText(_translate("OutputWindow", "No Centralizer", None))
		self.label_10.setText(_translate("OutputWindow", "Specify spacing", None))
		self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("OutputWindow", "Centralizer Calculation", None))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("OutputWindow", "Tables", None))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("OutputWindow", "Spacing", None))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("OutputWindow", "Side Force", None))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("OutputWindow", "Standoff (%)", None))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("OutputWindow", "Dogleg", None))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("OutputWindow", "Side Force 2D", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("OutputWindow", "Centralizer", None))
		self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("OutputWindow", "Table", None))
		self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("OutputWindow", "Hook Load", None))
		self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), _translate("OutputWindow", "Surface Torque", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("OutputWindow", "Torque and Drag", None))
		self.iw_toolBar.setWindowTitle(_translate("OutputWindow", "toolBar", None))
		self.menuWindows.setTitle(_translate("OutputWindow", "Windows", None))
		self.menuUtilities.setTitle(_translate("OutputWindow", "Utilities", None))
		self.menuHelp.setTitle(_translate("OutputWindow", "Help", None))
		self.menuFile.setTitle(_translate("OutputWindow", "File", None))
		self.actionNew.setText(_translate("OutputWindow", "New", None))
		self.actionNew.setShortcut(_translate("OutputWindow", "Ctrl+N", None))
		self.actionOpen.setText(_translate("OutputWindow", "Open...", None))
		self.actionOpen.setShortcut(_translate("OutputWindow", "Ctrl+O", None))
		self.actionSave.setText(_translate("OutputWindow", "Save", None))
		self.actionSave.setShortcut(_translate("OutputWindow", "Ctrl+S", None))
		self.actionSave_As.setText(_translate("OutputWindow", "Save As...", None))
		self.actionPrint.setText(_translate("OutputWindow", "Print Preview...", None))
		self.actionPrint_2.setText(_translate("OutputWindow", "Print..", None))
		self.actionPrint_2.setShortcut(_translate("OutputWindow", "Ctrl+P", None))
		self.actionExit.setText(_translate("OutputWindow", "Exit", None))
		self.actionCopy_Selection.setText(_translate("OutputWindow", "Copy Selection", None))
		self.actionPaste.setText(_translate("OutputWindow", "Paste", None))
		self.actionOne_Span_Analysis.setText(_translate("OutputWindow", "One Span Analysis...", None))
		self.actionUnit_Setting.setText(_translate("OutputWindow", "Unit Setting...", None))
		self.actionUnit_Conversion.setText(_translate("OutputWindow", "Unit Conversion...", None))
		self.actionCalculator.setText(_translate("OutputWindow", "Calculator...", None))
		self.actionNotepad.setText(_translate("OutputWindow", "Notepad...", None))
		self.actionAbout.setText(_translate("OutputWindow", "About...", None))
		self.actionAbbreviation.setText(_translate("OutputWindow", "Abbreviation...", None))
		self.actionDisclaimer.setText(_translate("OutputWindow", "Disclaimer...", None))
		self.actionStar_Calculation.setText(_translate("OutputWindow", "Star Calculation", None))
		self.actionStar_Calculation.setShortcut(_translate("OutputWindow", "F5", None))
		self.actionReturn_to_Input_Window.setText(_translate("OutputWindow", "Return to Input Window", None))
		self.actionPrint_All.setText(_translate("OutputWindow", "Print Report ...", None))
		self.actionPrint_Summary_Only.setText(_translate("OutputWindow", "Print Summary Only ...", None))
		self.actionGenerate_Report.setText(_translate("OutputWindow", "Generate Report ...", None))
		self.actionStandoff_Profile.setText(_translate("OutputWindow", "Standoff Profile ...", None))
		self.action3D_Wellpath.setText(_translate("OutputWindow", "3D Parameter Visualization ...", None))
		self.actionCentralizer.setText(_translate("OutputWindow", "Centralizer Spacing Sensitivity Analysis ...", None))
		self.actionGraph_Settings.setText(_translate("OutputWindow", "Graph Settings ...", None))

from matplotlibwidget import MatplotlibWidget
